/**
 * @file
 * BreadrumbItem class.
 */

/* global Breadcrumb */

import Component from "../Component.js";

/**
 * The Breadcrumb Item component.
 *
 * @extends Component
 *
 * Protected fields are documented below.
 *
 * @property {Object<HTMLElement>}         _dom                         - The DOM elements within the breadcrumb.
 * @property {HTMLElement}                 _dom.item                    - The breadcrumb item element.
 * @property {?HTMLElement}                _dom.link                    - The breadcrumb link element.
 * @property {string}                      _rootDOMElement              - The root DOM element of the breadcrumb item.
 * @property {string[]}                    _protectedDOMElements        - The DOM elements within the breadcrumb item that cannot be reset or generated by the breadcrumb item itself.
 * @property {Object<string>}              _selectors                   - The query selectors used by the breadcrumb item.
 * @property {Object<Breadcrumb>}          _elements                    - The instantiated elements within the breadcrumb item.
 * @property {Breadcrumb}                  _elements.parent             - The parent breadcrumb instance of the breadcrumb item.
 * @property {Object<string, string[]>}    _classes                     - The CSS classes to apply when the breadcrumb item is in various states.
 * @property {string|string[]}             _classes.initialize          - The class(es) to apply when the breadcrumb item is initializing.
 * @property {Object<number>}              _durations                   - The duration times (in milliseconds) for various aspects throughout the breadcrumb item.
 * @property {Function}                    _mediaQueryListEventCallback - The callback for media query list events.
 * @property {string}                      _storageKey                  - The key used for storage.
 * @property {boolean}                     _shouldStore                 - A flag to check if the component should be stored in the StorageManager.
 * @property {Object<CustomEvent>}         _events                      - Custom events that can be triggered throughout the breadcrumb item.
 * @property {Object<number>}              _delays                      - The delay times (in milliseconds) for various aspects througho1t the breadcrumb item.
 * @property {string}                      _focusState                  - The current state of the breadcrumb item's focus.
 * @property {string}                      _currentEvent                - The last type of event triggered within the breadcrumb item.
 * @property {string}                      _breakpoint                  - The breakpoint that the breadcrumb item will call media query list events.
 * @property {string}                      _mediaQueryString            - The media query to use to trigger media query list events.
 * @property {MediaQueryList|null}         _mediaQueryList              - The MediaQueryList for the breadcrumb item.
 * @property {Object<Function>}            _intervals                   - Intervals throughout the breadcrumb item.
 * @property {Object<Function>}            _timeouts                    - Timeouts throughout the breadcrumb item.
 * @property {object[]}                    _listeners                   - Event listeners throughout the breadcrumb item.
 * @property {string}                      _prefix                      - The prefix used for CSS custom properties and attributes.
 * @property {string}                      _key                         - The key used to generate IDs throughout the breadcrumb item.
 * @property {string}                      _id                          - The main ID of the breadcrumb item.
 * @property {boolean}                     _valid                       - The validity state of the breadcrumb item.
 * @property {boolean}                     _initialized                 - The initialized state of the breadcrumb item.
 * @property {string[]}                    _errors                      - The errors found throughout the breadcrumb item.
 * @property {boolean}                     _toggle                      - A flag marking whether the breadcrumb item is a toggle item.
 */
class BreadcrumbItem extends Component {
  _rootDOMElement = "item";
  _protectedDOMElements = ["link"];
  _storageKey = "breadcrumbItems";
  _shouldStore = false;
  _toggle = false;

  constructor({
    breadcrumbItemElement,
    breadcrumbLinkElement = null,
    parentBreadcrumb,
    isToggle = false,
    prefix = "graupl-",
    key = null,
    initializeClass = "initializing",
  }) {
    super({
      prefix,
      key,
      initializeClass,
    });

    // Set the DOM elements.
    this._dom.item = breadcrumbItemElement;
    this._dom.link = breadcrumbLinkElement || null;

    // Set the instantiated elements.
    this._elements.parent = parentBreadcrumb;

    // Set the toggle state.
    this._toggle = isToggle;
  }

  /**
   * A flag marking whether the breadcrumb item is a toggle item.
   *
   * @readonly
   *
   * @type {boolean}
   *
   * @see _toggle
   */
  get isToggle() {
    return this._toggle;
  }

  /**
   * Focuses the breadcrumb item's link if the parent breadcrumb's shoudlFOcus value is `true`.
   */
  focus() {
    if (this.elements.parent.shouldFocus && this.dom.link) {
      requestAnimationFrame(() => {
        this.dom.link.focus();
      });
    }
  }

  /**
   * Blurs the breadcrumb item's link if the parent breadcrumb's shouldFocus value is `true`.
   */
  blur() {
    if (this.elements.parent.shouldFocus && this.dom.link) {
      requestAnimationFrame(() => {
        this.dom.link.blur();
      });
    }
  }
}

export default BreadcrumbItem;
