/**
 * @file
 * The Breadcrumb class.
 */

import {
  isValidClassList,
  isValidType,
  isTag,
} from "@graupl/core/src/validate.js";
import { addClass, removeClass } from "@graupl/core/src/domHelpers.js";
import { keyPress, preventEvent } from "@graupl/core/src/eventHandlers.js";
import TransactionalValue from "@graupl/core/src/TransactionalValue.js";
import Component from "@graupl/core/src/Component.js";

/**
 * The event that is triggered when the breadcrumb is shown.
 *
 * @event grauplBreadcrumbExpand
 *
 * @type {CustomEvent}
 *
 * @property {boolean}            bubbles           - A flag to bubble the event
 * @property {Object<Breadcrumb>} detail            - The details object containing the breadcrumb itself.
 * @property {Breadcrumb}         detail.breadcrumb - The breadcrumb.
 */

/**
 * The event that is triggered when the breadcrumb is hidden.
 *
 * @event grauplBreadcrumbCollapse
 *
 * @type {CustomEvent}
 *
 * @property {boolean}            bubbles           - A flag to bubble the event
 * @property {Object<Breadcrumb>} detail            - The details object containing the breadcrumb itself.
 * @property {Breadcrumb}         detail.breadcrumb - The breadcrumb.
 */

/**
 * The Breadcrumb component.
 *
 * @extends Component
 *
 * Protected fields are documented below.
 *
 * @property {Object<HTMLElement>}         _dom                         - The DOM elements within the breadcrumb.
 * @property {HTMLElement}                 _dom.breadcrumb              - The breadcrumb element.
 * @property {HTMLElement}                 _dom.breadcrumbToggle        - The breadcrumb toggle element.
 * @property {HTMLElement}                 _dom.breadcrumbItems         - The breadcrumb item elements.
 * @property {string}                      _rootDOMElement              - The root DOM element of the breadcrumb.
 * @property {string[]}                    _protectedDOMElements        - The DOM elements within the breadcrumb that cannot be reset or generated by the breadcrumb itself.
 * @property {Object<string>}              _selectors                   - The query selectors used by the breadcrumb.
 * @property {string}                      _selectors.breadcrumbItems   - The query selector for the breadcrumb items.
 * @property {string}                      _selectors.breadcrumbToggle  - The query selector for the breadcrumb toggle.
 * @property {Object<string, string[]>}    _classes                     - The CSS classes to apply when the breadcrumb is in various states.
 * @property {string|string[]}             _classes.open                - The class(es) to apply when the breadcrumb is open.
 * @property {string|string[]}             _classes.close               - The class(es) to apply when the breadcrumb is closed.
 * @property {string|string[]}             _classes.transition          - The class(es) to apply when the breadcrumb is transitioning between states.
 * @property {string|string[]}             _classes.initialize          - The class(es) to apply when the breadcrumb is initializing.
 * @property {Object<number>}              _durations                   - The duration times (in milliseconds) for various aspects throughout the breadcrumb.
 * @property {number}                      _durations.transition        - The duration time (in milliseconds) for the transition between open and closed states.
 * @property {number}                      _durations.open              - The duration time (in milliseconds) for the transition from closed to open states.
 * @property {number}                      _durations.close             - The duration time (in milliseconds) for the transition from open to closed states.
 * @property {TransactionalValue<boolean>} _open                        - The open state of the breadcrumb.
 * @property {boolean}                     _shouldOpen                  - A value to force the breadcrumb open when the breakpoint width is passed.
 * @property {boolean}                     _closeOnBlur                 - Whether to close the breadcrumb when it loses focus in the DOM.
 * @property {Function}                    _mediaQueryListEventCallback - The callback for media query list events.
 * @property {string}                      _storageKey                  - The key used for storage.
 * @property {Object<CustomEvent>}         _events                      - Custom events that can be triggered throughout the breadcrumb.
 * @property {grauplBreadcrumbExpand}      _events.expand               - The event triggered when the breadcrumb is expanded.
 * @property {grauplBreadcrumbCollapse}    _events.collapse             - The event triggered when the breadcrumb is collapsed.
 * @property {Object<object>}              _elements                    - The instantiated elements within the breadcrumb.
 * @property {Object<number>}              _delays                      - The delay times (in milliseconds) for various aspects throughout the breadcrumb.
 * @property {string}                      _focusState                  - The current state of the breadcrumb's focus.
 * @property {string}                      _currentEvent                - The last type of event triggered within the breadcrumb.
 * @property {string}                      _breakpoint                  - The breakpoint that the breadcrumb will call media query list events.
 * @property {string}                      _mediaQueryString            - The media query to use to trigger media query list events.
 * @property {MediaQueryList|null}         _mediaQueryList              - The MediaQueryList for the breadcrumb.
 * @property {Object<Function>}            _intervals                   - Intervals throughout the breadcrumb.
 * @property {Object<Function>}            _timeouts                    - Timeouts throughout the breadcrumb.
 * @property {object[]}                    _listeners                   - Event listeners throughout the breadcrumb.
 * @property {string}                      _prefix                      - The prefix used for CSS custom properties and attributes.
 * @property {string}                      _key                         - The key used to generate IDs throughout the breadcrumb.
 * @property {string}                      _id                          - The main ID of the breadcrumb.
 * @property {boolean}                     _valid                       - The validity state of the breadcrumb.
 * @property {boolean}                     _initialized                 - The initialized state of the breadcrumb.
 * @property {string[]}                    _errors                      - The errors found throughout the breadcrumb.
 */
class Breadcrumb extends Component {
  _rootDOMElement = "breadcrumb";
  _open = new TransactionalValue(false);
  _shouldOpen = true;
  _closeOnBlur = false;
  _storageKey = "breadcrumb";
  _mediaQueryListEventCallback = (event) => {
    if (!this.dom.breadcrumbToggle) {
      return;
    }

    if (event.matches && this.isOpen) {
      this.close();
    } else {
      this.open();
    }
  };

  constructor({
    breadcrumbElement,
    breadcrumbItemsSelector = ".breadcrumb-item",
    breadcrumbToggleSelector = ".breadcrumb-toggle",
    openClass = "show",
    closeClass = "hide",
    transitionClass = "transition",
    transitionDuration = 250,
    openDuration = -1,
    closeDuration = -1,
    closeOnBlur = false,
    minWidth = "856px",
    autoOpen = true,
    mediaQuery = "",
    prefix = "graupl-",
    key = null,
    initializeClass = "initializing",
    initialize = false,
  }) {
    super({
      prefix,
      key,
      initializeClass,
    });

    // Set the DOM elements.
    this._dom.breadcrumb = breadcrumbElement;
    this._dom.breadcrumbItems = [];
    this._dom.breadcrumbToggle = null;

    // Set the DOM selectors.
    this._selectors.breadcrumbItems = breadcrumbItemsSelector;
    this._selectors.breadcrumbToggle = breadcrumbToggleSelector;

    // Set the classes.
    this._classes.open = openClass;
    this._classes.close = closeClass;
    this._classes.transition = transitionClass;

    // Set the durations.
    this._durations.transition = transitionDuration;
    this._durations.open = openDuration;
    this._durations.close = closeDuration;

    // Set close on blur.
    this._closeOnBlur = closeOnBlur;

    // Set the collapse width and auto open functionality.
    this._breakpoint = minWidth || "";
    this._shouldOpen = autoOpen;
    this._mediaQueryString = mediaQuery || "";

    this._registerEvent("expand", { detail: { breadcrumb: this } });
    this._registerEvent("collapse", { detail: { breadcrumb: this } });

    // Set up custom initialization.
    this._addEventListener(
      "grauplComponentInitialize",
      this.rootDOMElement,
      () => {
        // Handle auto-opening breadcrumbs with aria-expanded set to true or
        // those that _should_ open.
        requestAnimationFrame(() => {
          if (this.dom.breadcrumbToggle) {
            if (
              this.dom.breadcrumbToggle.getAttribute("aria-expanded") ===
                "true" ||
              (this.shouldOpen && !window.matchMedia(this.mediaQuery).matches)
            ) {
              this._expand({ emit: false, transition: false });
            } else {
              this._collapse({ emit: false, transition: false });
            }
          }
        });
      }
    );

    // Set up custom validation.
    this._addEventListener(
      "grauplComponentValidate",
      this.rootDOMElement,
      () => {
        // Boolean checks.
        const booleans = {
          closeOnBlur: this._closeOnBlur,
          autoOpen: this._shouldOpen,
        };

        // Check the booleans.
        const booleanChecks = isValidType("boolean", booleans, {
          shouldThrow: false,
        });

        // Handle boolean check failure.
        if (!booleanChecks.status) {
          this._errors = [...this._errors, ...booleanChecks.errors];
          this._valid = false;
        }
      }
    );

    if (initialize) {
      this.initialize();
    }
  }

  /**
   * The class(es) to apply when the breadcrumb is open.
   *
   * @type {string|string[]}
   *
   * @see _classes.open
   */
  get openClass() {
    return this._classes.open;
  }

  set openClass(value) {
    isValidClassList({ openClass: value });

    if (this._classes.open !== value) {
      this._classes.open = value;
    }
  }

  /**
   * The class(es) to apply when the breadcrumb is closed.
   *
   * @type {string|string[]}
   *
   * @see _classes.close
   */
  get closeClass() {
    return this._classes.close;
  }

  set closeClass(value) {
    isValidClassList({ closeClass: value });

    if (this._classes.close !== value) {
      this._classes.close = value;
    }
  }

  /**
   * The class(es) to apply when the breadcrumb is transitioning between open and closed.
   *
   * @type {string|string[]}
   *
   * @see _classes.transition
   */
  get transitionClass() {
    return this._classes.transition;
  }

  set transitionClass(value) {
    isValidClassList({ transitionClass: value });

    if (this._classes.transition !== value) {
      this._classes.transition = value;
    }
  }

  /**
   * The duration time (in milliseconds) for the transition between open and closed states.
   *
   * Setting this value will also set the --graupl-transition-duration CSS custom property on the breadcrumb.
   *
   * @type {number}
   *
   * @see _durations.transition
   */
  get transitionDuration() {
    return this._durations.transition;
  }

  set transitionDuration(value) {
    isValidType("number", { transitionDuration: value });

    if (this._durations.transition !== value) {
      this._durations.transition = value;
      this._setCustomProps();
    }
  }

  /**
   * The duration time (in milliseconds) for the transition from closed to open states.
   *
   * If openDuration is set to -1, the transitionDuration value will be used instead.
   *
   * Setting this value will also set the --graupl-open-transition-duration CSS custom property on the breadcrumb.
   *
   * @type {number}
   *
   * @see _durations.open
   */
  get openDuration() {
    if (this._durations.open === -1) return this.transitionDuration;

    return this._durations.open;
  }

  set openDuration(value) {
    isValidType("number", { openDuration: value });

    if (this._durations.open !== value) {
      this._durations.open = value;
      this._setCustomProps();
    }
  }

  /**
   * The duration time (in milliseconds) for the transition from open to closed states.
   *
   * If closeDuration is set to -1, the transitionDuration value will be used instead.
   *
   * Setting this value will also set the --graupl-close-transition-duration CSS custom property on the breadcrumb.
   *
   * @type {number}
   *
   * @see _durations.close
   */
  get closeDuration() {
    if (this._durations.close === -1) return this.transitionDuration;

    return this._durations.close;
  }

  set closeDuration(value) {
    isValidType("number", { closeDuration: value });

    if (this._durations.close !== value) {
      this._durations.close = value;
      this._setCustomProps();
    }
  }

  /**
   * The width of the screen that the breadcrumb will automatically open/close itself.
   *
   * This is just an alias for the generic "breakpoint" used in all components.
   *
   * @type {string}
   *
   * @see breakpoint
   */
  get minWidth() {
    return this.breakpoint;
  }

  set minWidth(value) {
    this.breakpoint = value;
  }

  /**
   * Whether to close the breadcrumb when it loses focus in the DOM.
   *
   * @type {boolean}
   *
   * @see _closeOnBlur
   */
  get closeOnBlur() {
    return this._closeOnBlur;
  }

  set closeOnBlur(value) {
    isValidType("boolean", { closeOnBlur: value });

    if (this._closeOnBlur !== value) {
      this._closeOnBlur = value;
    }
  }

  /**
   * The open state of the breadcrumb.
   *
   * @readonly
   *
   * @type {boolean}
   *
   * @see _open
   */
  get isOpen() {
    return this._open.value;
  }

  /**
   * The open state of the breadcrumb that the user specifically triggered.
   *
   * @readonly
   *
   * @type {boolean}
   *
   * @see _open
   */
  get hasOpened() {
    return this._open.committed;
  }

  /**
   * A value to force opening regardless of user interaction.
   *
   * @type {boolean}
   *
   * @see _shouldOpen
   */
  get shouldOpen() {
    return this._shouldOpen;
  }

  set shouldOpen(value) {
    isValidType("boolean", { shouldOpen: value });

    if (this._shouldOpen !== value) {
      this._shouldOpen = value;
    }
  }

  /**
   * Sets the IDs throughout the breadcrumb.
   *
   * The generated IDs use the key and follow the format:
   *  - breadcrumb: `breadcrumb-${key}`
   *  - toggle: `breadcrumb-toggle-${key}`
   *
   * @protected
   */
  _setIds() {
    this.dom.breadcrumb.id = this.dom.breadcrumb.id || `breadcrumb-${this.key}`;

    if (this.dom.breadcrumbToggle) {
      this.dom.breadcrumbToggle.id =
        this.dom.breadcrumbToggle.id || `breadcrumb-toggle-${this.key}`;
    }

    this._id = this.dom.breadcrumb.id;
  }

  /**
   * Sets ARIA attributes throughout the breadcrumb.
   *
   * The first steps are to ensure that the toggle has `aria-expanded` set to "false"
   * if it's not already explicitly set to "true".
   *
   * Then, set the `aria-controls` attribute on the toggle to the breadcrumb's ID.
   *
   * Finally, ensure the toggle element has a role of "button" if it is not a native button element.
   *
   * @protected
   */
  _setAriaAttributes() {
    if (!this.dom.breadcrumbToggle) return;

    // If the toggle element doesn't have aria-expanded set to true, set it to false.
    if (this.dom.breadcrumbToggle.getAttribute("aria-expanded") !== "true") {
      this.dom.breadcrumbToggle.setAttribute("aria-expanded", "false");
    }

    // Set the aria-controls attribute on the toggle to the breadcrumb's ID.
    this.dom.breadcrumbToggle.setAttribute(
      "aria-controls",
      this.dom.breadcrumb.id
    );

    // If the toggle element is not a button, set its role to button.
    if (
      !isTag(
        "button",
        { toggle: this.dom.breadcrumbToggle },
        { shouldThrow: false }
      ).status
    ) {
      this.dom.breadcrumbToggle.setAttribute("role", "button");
    }
  }

  /**
   * Sets custom props throughout the breadcrumb.
   *
   * The custom properties are:
   *   - `--graupl-breadcrumb-transition-duration`,
   *   - `--graupl-breadcrumb-open-transition-duration`, and
   *   - `--graupl-breadcrumb-close-transition-duration`.
   *
   * The prefix of `graupl-` can be changed by setting the breadcrumb's prefix value.
   *
   * @protected
   */
  _setCustomProps() {
    this.dom.breadcrumb.style.setProperty(
      `--${this.prefix}breadcrumb-transition-duration`,
      `${this.transitionDuration}ms`
    );

    this.dom.breadcrumb.style.setProperty(
      `--${this.prefix}breadcrumb-open-transition-duration`,
      `${this.openDuration}ms`
    );

    this.dom.breadcrumb.style.setProperty(
      `--${this.prefix}breadcrumb-close-transition-duration`,
      `${this.closeDuration}ms`
    );
  }

  /**
   * Sets all DOM elements within the breadcrumb.
   *
   * Utilizes _setDOMElementType and
   * _resetDOMElementType.
   *
   * @protected
   */
  _setDOMElements() {
    this._resetDOMElementType("breadcrumbItems");
    this._setDOMElementType("breadcrumbItems", {
      context: this.dom.breadcrumb,
    });

    this._resetDOMElementType("breadcrumbToggle");
    this._setDOMElementType("breadcrumbToggle", {
      context: this.dom.breadcrumb,
    });
  }

  /**
   * Expands the breadcrumb.
   *
   * Sets the toggle's `aria-expanded` to "true", adds the
   * open class to the breadcrumb, and removes the closed class from the breadcrumb.
   *
   * @protected
   *
   * @fires grauplBreadcrumbExpand
   *
   * @param {Object<boolean>} [options = {}]              - Options for expanding the breadcrumb.
   * @param {boolean}         [options.emit = true]       - Emit the expand event once expanded.
   * @param {boolean}         [options.transition = true] - Respect the transition class.
   */
  _expand({ emit = true, transition = true } = {}) {
    this.dom.breadcrumbToggle.setAttribute("aria-expanded", "true");

    // If we're dealing with transition classes, then we need to utilize
    // requestAnimationFrame to add the transition class, remove the close class,
    // add the open class, and finally remove the transition class.
    if (transition && this.transitionlass !== "") {
      addClass(this.transitionClass, this.dom.breadcrumb);

      requestAnimationFrame(() => {
        removeClass(this.closeClass, this.dom.breadcrumb);

        requestAnimationFrame(() => {
          addClass(this.openClass, this.dom.breadcrumb);

          requestAnimationFrame(() => {
            setTimeout(() => {
              removeClass(this.transitionClass, this.dom.breadcrumb);
            }, this.openDuration);
          });
        });
      });
    } else {
      // Add the open class
      addClass(this.openClass, this.dom.breadcrumb);

      // Remove the close class.
      removeClass(this.closeClass, this.dom.breadcrumb);
    }

    if (emit) {
      this._dispatchEvent("expand", this.dom.breadcrumbToggle);
    }
  }

  /**
   * Collapses the breadcrumb.
   *
   * Sets the toggle's `aria-expanded` to "false", adds the
   * close class to the breadcrumb, and removes the open class from the breadcrumb.
   *
   * @protected
   *
   * @fires grauplBreadcrumbCollapse
   *
   * @param {Object<boolean>} [options = {}]              - Options for collapsing the breadcrumb.
   * @param {boolean}         [options.emit = true]       - Emit the collapse event once collapsed.
   * @param {boolean}         [options.transition = true] - Respect the transition class.
   */
  _collapse({ emit = true, transition = true } = {}) {
    this.dom.breadcrumbToggle.setAttribute("aria-expanded", "false");

    // If we're dealing with transition classes, then we need to utilize
    // requestAnimationFrame to add the transition class, remove the open class,
    // add the close class, and finally remove the transition class.
    if (transition && this.transitionClass !== "") {
      addClass(this.transitionClass, this.dom.breadcrumb);

      requestAnimationFrame(() => {
        removeClass(this.openClass, this.dom.breadcrumb);

        requestAnimationFrame(() => {
          addClass(this.closeClass, this.dom.breadcrumb);

          requestAnimationFrame(() => {
            setTimeout(() => {
              removeClass(this.transitionClass, this.dom.breadcrumb);
            }, this.closeDuration);
          });
        });
      });
    } else {
      // Add the close class
      addClass(this.closeClass, this.dom.breadcrumb);

      // Remove the open class.
      removeClass(this.openClass, this.dom.breadcrumb);
    }

    if (emit) {
      this._dispatchEvent("collapse", this.dom.breadcrumbToggle);
    }
  }

  /**
   * Handles focus events throughout the breadcrumb.
   *
   * - Adds a `focusout` listener to the breadcrumb so when the breadcrumb loses focus it will close.
   */
  _handleFocus() {
    this._addEventListener("focusout", this.dom.breadcrumb, (event) => {
      if (
        !this.closeOnBlur ||
        this.currentEvent !== "keyboard" ||
        event.relatedTarget === null ||
        this.dom.breadcrumb.contains(event.relatedTarget) ||
        this.dom.breadcrumbToggle === event.relatedTarget
      ) {
        return;
      }

      this.close();
    });
  }

  /**
   * Handles click events throughout the breadcrumb.
   *
   * - Adds a `click` listener to the toggle that toggles the breadcrumb.
   * - Adds a `click` listener to the `document` so if the user clicks outside the breadcrumb it will close.
   */
  _handleClick() {
    if (!this.dom.breadcrumbToggle) {
      return;
    }

    this._addEventListener("click", this.dom.breadcrumbToggle, (event) => {
      this.currentEvent = "mouse";

      if (event.button !== 0) return;

      preventEvent(event);
      this.toggle();
    });

    this._addEventListener("click", document, (event) => {
      if (this.focusState !== "self" || !this.closeOnBlur) return;

      this.currentEvent = "mouse";

      if (
        !this.dom.breadcrumb.contains(event.target) &&
        this.dom.breadcrumbToggle !== event.target
      ) {
        this.close();
      }
    });
  }

  /**
   * Handles keydown events throughout the breadcrumb.
   *
   * This method exists to assist the _handleKeyup method.
   *
   * - Adds a `keydown` listener to the toggle.
   *   - Blocks propagation on "Space" and "Enter" keys.
   * - Adds a `keydown` listener to the breadcrumb.
   *   - Blocks propagation on "Escape" keys.
   */
  _handleKeydown() {
    if (!this.dom.breadcrumbToggle) {
      return;
    }

    this._addEventListener("keydown", this.dom.breadcrumbToggle, (event) => {
      this.currentEvent = "keyboard";

      const key = keyPress(event);

      switch (key) {
        case "Space":
        case "Enter":
          preventEvent(event);

          break;
      }
    });

    this._addEventListener("keydown", this.dom.breadcrumb, (event) => {
      this.currentEvent = "keyboard";

      const key = keyPress(event);

      switch (key) {
        case "Escape":
          preventEvent(event);

          break;
      }
    });
  }

  /**
   * Handles keyup events throughout the breadcrumb.
   *
   * - Adds a `keyup` listener to the toggle.
   *   - Toggles the breadcrumb on "Space" and "Enter" keys.
   * - Adds a `keyup` listener to the breadcrumb.
   *   - Closes the breadcrumb on "Escape" keys.
   */
  _handleKeyup() {
    if (!this.dom.breadcrumbToggle) {
      return;
    }

    this._addEventListener("keyup", this.dom.breadcrumbToggle, (event) => {
      this.currentEvent = "keyboard";

      const key = keyPress(event);

      switch (key) {
        case "Space":
        case "Enter":
          this.toggle();

          preventEvent(event);

          break;
      }
    });

    this._addEventListener("keyup", this.dom.breadcrumb, (event) => {
      this.currentEvent = "keyboard";

      const key = keyPress(event);

      switch (key) {
        case "Escape":
          this.close();

          preventEvent(event);

          break;
      }
    });
  }

  /**
   * Opens the breadcrumb.
   *
   * Sets the breadcrumb's focus state to "self", calls expand, and sets isOpen to `true`.
   *
   * @param {Object<boolean>} [options = {}]                  - Options for opening the breadcrumb.
   * @param {boolean}         [options.force = false]         - Whether to force the open action.
   * @param {boolean}         [options.preserveState = false] - Whether to preserve the open state.
   */
  open({ force = false, preserveState = false } = {}) {
    if (this.isOpen && !force) return;

    // Set the focus state.
    this.focusState = "self";

    // Expand the breadcrumb.
    this._expand();

    // Set the open state.
    this._open.value = true;

    if (!preserveState) {
      this._open.commit();
    }
  }

  /**
   * Opens the breadcrumb without entering it.
   *
   * Sets the breadcrumb's focus state to "none", calls expand, and sets isOpen to `true`.
   *
   * @param {Object<boolean>} [options = {}]                  - Options for previewing the breadcrumb.
   * @param {boolean}         [options.force = false]         - Whether to force the preview action.
   * @param {boolean}         [options.preserveState = false] - Whether to preserve the open state.
   */
  preview({ force = false, preserveState = false } = {}) {
    if (this.isOpen && !force) return;

    // Set the focus state.
    this.focusState = "none";

    // Expand the breadcrumb.
    this._expand();

    // Set the open state.
    this._open.value = true;

    if (!preserveState) {
      this._open.commit();
    }
  }

  /**
   * Closes the breadcrumb.
   *
   * Sets the breadcrumb's focus state to "none", calls collapse, and sets isOpen to `false`.
   *
   * @param {Object<boolean>} [options = {}]                  - Options for closing the breadcrumb.
   * @param {boolean}         [options.force = false]         - Whether to force the close action.
   * @param {boolean}         [options.preserveState = false] - Whether to preserve the open state.
   */
  close({ force = false, preserveState = false } = {}) {
    if (!this.isOpen && !force) return;

    // Set the focus state.
    this.focusState = "none";

    // Collapse the breadcrumb.
    this._collapse();

    // Set the open state.
    this._open.value = false;

    if (!preserveState) {
      this._open.commit();
    }
  }

  /**
   * Toggles the open state of the breadcrumb.
   *
   * @param {Object<boolean>} [options = {}]                  - Options for toggling the breadcrumb.
   * @param {boolean}         [options.force = false]         - Whether to force the open or close action.
   * @param {boolean}         [options.preserveState = false] - Whether to preserve the open state.
   */
  toggle({ force = false, preserveState = false } = {}) {
    if (this.isOpen) {
      this.close({ force, preserveState });
    } else {
      this.open({ force, preserveState });
    }
  }
}

export default Breadcrumb;
