/**
 * @file
 * The Breadcrumb class.
 */

import { isValidClassList, isValidType, isTag } from "../validate.js";
import { addClass, removeClass } from "../domHelpers.js";
import { keyPress, preventEvent } from "../eventHandlers.js";
import TransactionalValue from "../TransactionalValue.js";
import Component from "../Component.js";
import BreadcrumbItem from "./BreadcrumbItem.js";

/**
 * The event that is triggered when the breadcrumb is shown.
 *
 * @event grauplBreadcrumbExpand
 *
 * @type {CustomEvent}
 *
 * @property {boolean}            bubbles           - A flag to bubble the event
 * @property {Object<Breadcrumb>} detail            - The details object containing the breadcrumb itself.
 * @property {Breadcrumb}         detail.breadcrumb - The breadcrumb.
 */

/**
 * The event that is triggered when the breadcrumb is hidden.
 *
 * @event grauplBreadcrumbCollapse
 *
 * @type {CustomEvent}
 *
 * @property {boolean}            bubbles           - A flag to bubble the event
 * @property {Object<Breadcrumb>} detail            - The details object containing the breadcrumb itself.
 * @property {Breadcrumb}         detail.breadcrumb - The breadcrumb.
 */

/**
 * The event that is triggered when the breadcrumb is locked.
 *
 * @event grauplBreadcrumbLock
 *
 * @type {CustomEvent}
 *
 * @property {boolean}            bubbles           - A flag to bubble the event
 * @property {Object<Breadcrumb>} detail            - The details object containing the breadcrumb itself.
 * @property {Breadcrumb}         detail.breadcrumb - The breadcrumb.
 */

/**
 * The event that is triggered when the breadcrumb is unlocked.
 *
 * @event grauplBreadcrumbUnlock
 *
 * @type {CustomEvent}
 *
 * @property {boolean}            bubbles           - A flag to bubble the event
 * @property {Object<Breadcrumb>} detail            - The details object containing the breadcrumb itself.
 * @property {Breadcrumb}         detail.breadcrumb - The breadcrumb.
 */

/**
 * The Breadcrumb component.
 *
 * @extends Component
 *
 * Protected fields are documented below.
 *
 * @property {Object<HTMLElement>}         _dom                         - The DOM elements within the breadcrumb.
 * @property {HTMLElement}                 _dom.breadcrumb              - The breadcrumb element.
 * @property {HTMLElement}                 _dom.breadcrumbItems         - The breadcrumb item elements.
 * @property {HTMLElement}                 _dom.breadcrumbLinks         - The breadcrumb link elements.
 * @property {HTMLElement}                 _dom.breadcrumbToggle        - The breadcrumb toggle element.
 * @property {string}                      _rootDOMElement              - The root DOM element of the breadcrumb.
 * @property {string[]}                    _protectedDOMElements        - The DOM elements within the breadcrumb that cannot be reset or generated by the breadcrumb itself.
 * @property {Object<string>}              _selectors                   - The query selectors used by the breadcrumb.
 * @property {string}                      _selectors.breadcrumbItems   - The query selector for the breadcrumb items.
 * @property {string}                      _selectors.breadcrumbToggle  - The query selector for the breadcrumb toggle.
 * @property {Object<object>}              _elements                    - The instantiated elements within the breadcrumb.
 * @property {BreadcrumbItem[]}            _elements.breadcrumbItems    - The breadcrumb item instances within the breadcrumb.
 * @property {BreadcrumbItem}              _elements.breadcrumbToggle   - The breadcrumb toggle instance of the breadcrumb.
 * @property {Object<string, string[]>}    _classes                     - The CSS classes to apply when the breadcrumb is in various states.
 * @property {string|string[]}             _classes.open                - The class(es) to apply when the breadcrumb is open.
 * @property {string|string[]}             _classes.close               - The class(es) to apply when the breadcrumb is closed.
 * @property {string|string[]}             _classes.transition          - The class(es) to apply when the breadcrumb is transitioning between states.
 * @property {string|string[]}             _classes.initialize          - The class(es) to apply when the breadcrumb is initializing.
 * @property {Object<number>}              _durations                   - The duration times (in milliseconds) for various aspects throughout the breadcrumb.
 * @property {number}                      _durations.transition        - The duration time (in milliseconds) for the transition between open and closed states.
 * @property {number}                      _durations.open              - The duration time (in milliseconds) for the transition from closed to open states.
 * @property {number}                      _durations.close             - The duration time (in milliseconds) for the transition from open to closed states.
 * @property {TransactionalValue<boolean>} _open                        - The open state of the breadcrumb.
 * @property {boolean}                     _shouldOpen                  - A value to force the breadcrumb open when the breakpoint width is passed.
 * @property {boolean}                     _closeOnBlur                 - Whether to close the breadcrumb when it loses focus in the DOM.
 * @property {Function}                    _mediaQueryListEventCallback - The callback for media query list events.
 * @property {string}                      _storageKey                  - The key used for storage.
 * @property {boolean}                     _shouldStore                 - A flag to check if the component should be stored in the StorageManager.
 * @property {Object<CustomEvent>}         _events                      - Custom events that can be triggered throughout the breadcrumb.
 * @property {grauplBreadcrumbExpand}      _events.expand               - The event triggered when the breadcrumb is expanded.
 * @property {grauplBreadcrumbCollapse}    _events.collapse             - The event triggered when the breadcrumb is collapsed.
 * @property {grauplBreadcrumbLock}        _events.lock                 - The event triggered when the breadcrumb is locked.
 * @property {grauplBreadcrumbUnlock}      _events.unlock               - The event triggered when the breadcrumb is unlocked.
 * @property {number}                      _currentChild                - The index of the current child node.
 * @property {Object<number>}              _delays                      - The delay times (in milliseconds) for various aspects througho1t the breadcrumb.
 * @property {string}                      _focusState                  - The current state of the breadcrumb's focus.
 * @property {string}                      _currentEvent                - The last type of event triggered within the breadcrumb.
 * @property {string}                      _breakpoint                  - The breakpoint that the breadcrumb will call media query list events.
 * @property {string}                      _mediaQueryString            - The media query to use to trigger media query list events.
 * @property {MediaQueryList|null}         _mediaQueryList              - The MediaQueryList for the breadcrumb.
 * @property {Object<Function>}            _intervals                   - Intervals throughout the breadcrumb.
 * @property {Object<Function>}            _timeouts                    - Timeouts throughout the breadcrumb.
 * @property {object[]}                    _listeners                   - Event listeners throughout the breadcrumb.
 * @property {string}                      _prefix                      - The prefix used for CSS custom properties and attributes.
 * @property {string}                      _key                         - The key used to generate IDs throughout the breadcrumb.
 * @property {string}                      _id                          - The main ID of the breadcrumb.
 * @property {boolean}                     _valid                       - The validity state of the breadcrumb.
 * @property {boolean}                     _initialized                 - The initialized state of the breadcrumb.
 * @property {string[]}                    _errors                      - The errors found throughout the breadcrumb.
 */
class Breadcrumb extends Component {
  _rootDOMElement = "breadcrumb";
  _currentChild = 0;
  _open = new TransactionalValue(false);
  _locked = new TransactionalValue(false);
  _openInsideBreakpoint = false;
  _openOutsideBreakpoint = true;
  _closeInsideBreakpoint = true;
  _closeOutsideBreakpoint = false;
  _lockInsideBreakpoint = false;
  _lockOutsideBreakpoint = true;
  _unlockInsideBreakpoint = false;
  _unlockOutsideBreakpoint = false;
  _openOnFocus = false;
  _closeOnBlur = false;
  _storageKey = "breadcrumbs";
  _name = "Breadcrumb";
  _mediaQueryListEventCallback = (event) => {
    if (event.matches) {
      if (this.unlockInsideBreakpoint) {
        this.unlock();
      }

      if (this.isOpen && this.closeInsideBreakpoint) {
        if (this.isLocked) {
          this.unlock();
        }
        this.close({ preserveState: true });
      } else if (!this.isOpen && this.openInsideBreakpoint) {
        if (this.isLocked) {
          this.unlock();
        }
        this.open();
      }

      if (this.lockInsideBreakpoint) {
        this.lock();
      }
    } else {
      if (this.unlockOutsideBreakpoint) {
        this.unlock();
      }

      if (this.isOpen && this.closeOutsideBreakpoint) {
        if (this.isLocked) {
          this.unlock();
        }
        this.close({ preserveState: true });
      } else if (!this.isOpen && this.openOutsideBreakpoint) {
        if (this.isLocked) {
          this.unlock();
        }
        this.open();
      }

      if (this.lockOutsideBreakpoint) {
        this.lock();
      }
    }
  };

  constructor({
    breadcrumbElement,
    breadcrumbItemsSelector = ".breadcrumb-item",
    breadcrumbLinksSelector = ".breadcrumb-link",
    breadcrumbToggleSelector = ".breadcrumb-toggle",
    lockedClass = "locked",
    unlockedClass = "unlocked",
    openClass = "show",
    closeClass = "hide",
    transitionClass = "transition",
    transitionDuration = 250,
    openDuration = -1,
    closeDuration = -1,
    openOnFocus = false,
    closeOnBlur = false,
    minWidth = "",
    breakpoint = "856px",
    autoOpen = false,
    openInsideBreakpoint = false,
    openOutsideBreakpoint = true,
    closeInsideBreakpoint = true,
    closeOutsideBreakpoint = false,
    lockInsideBreakpoint = false,
    lockOutsideBreakpoint = true,
    unlockInsideBreakpoint = true,
    unlockOutsideBreakpoint = false,
    locked = false,
    mediaQuery = "",
    prefix = "graupl-",
    key = null,
    initializeClass = "initializing",
    initialize = false,
  }) {
    super({
      prefix,
      key,
      initializeClass,
    });

    // Set the DOM elements.
    this._dom.breadcrumb = breadcrumbElement;
    this._dom.breadcrumbItems = [];
    this._dom.breadcrumbLinks = [];
    this._dom.breadcrumbToggle = null;

    // Set the DOM selectors.
    this._selectors.breadcrumbItems = breadcrumbItemsSelector;
    this._selectors.breadcrumbLinks = breadcrumbLinksSelector;
    this._selectors.breadcrumbToggle = breadcrumbToggleSelector;

    // Set the elements.
    this._elements.breadcrumbItems = [];

    // Set the classes.
    this._classes.locked = lockedClass || "";
    this._classes.unlocked = unlockedClass || "";
    this._classes.open = openClass || "";
    this._classes.close = closeClass || "";
    this._classes.transition = transitionClass || "";

    // Set the durations.
    this._durations.transition = transitionDuration;
    this._durations.open = openDuration;
    this._durations.close = closeDuration;

    // Set focus settings.
    this._openOnFocus = openOnFocus;
    this._closeOnBlur = closeOnBlur;

    // @todo Remove minWidth and autoOpen options in favor of breakpoint, openInsideBreakpoint, openOutsideBreakpoint, closeInsideBreakpoint, and closeOutsideBreakpoint options.
    if (minWidth !== "") {
      console.warn(
        "`minWidth` is deprecated and will be removed in a future release. Please set `breakpoint` instead."
      );

      if (breakpoint === "") {
        breakpoint = minWidth;
      }
    }

    if (autoOpen && breakpoint !== "") {
      console.warn(
        "`autoOpen` is deprecated and will be removed in a future release. Please set `openOutsideBreakpoint` and `closeInsideBreakpoint` to `true` instead."
      );

      openOutsideBreakpoint = autoOpen;
      closeInsideBreakpoint = autoOpen;
    }

    // Set the collapse width and auto open functionality.
    this._breakpoint = breakpoint || "";
    this._openInsideBreakpoint = openInsideBreakpoint;
    this._openOutsideBreakpoint = openOutsideBreakpoint;
    this._closeInsideBreakpoint = closeInsideBreakpoint;
    this._closeOutsideBreakpoint = closeOutsideBreakpoint;
    this._lockInsideBreakpoint = lockInsideBreakpoint;
    this._lockOutsideBreakpoint = lockOutsideBreakpoint;
    this._unlockInsideBreakpoint = unlockInsideBreakpoint;
    this._unlockOutsideBreakpoint = unlockOutsideBreakpoint;
    this._mediaQueryString = mediaQuery || "";

    // Set the lock state.
    this._locked.value = locked;
    this._locked.commit();

    this._registerEvent("expand", { detail: { breadcrumb: this } });
    this._registerEvent("collapse", { detail: { breadcrumb: this } });
    this._registerEvent("lock", { detail: { breadcrumb: this } });
    this._registerEvent("unlock", { detail: { breadcrumb: this } });

    // Set up custom initialization.
    this._addEventListener(
      "grauplComponentInitialize",
      this.rootDOMElement,
      () => {
        // Handle auto-opening breadcrumbs with aria-expanded set to true or
        // those that _should_ open.
        requestAnimationFrame(() => {
          if (this.dom.breadcrumbToggle) {
            if (
              this.dom.breadcrumbToggle.getAttribute("aria-expanded") ===
                "true" ||
              (this.openOutsideBreakpoint &&
                !window.matchMedia(this.mediaQuery).matches) ||
              (this.openInsideBreakpoint &&
                window.matchMedia(this.mediaQuery).matches)
            ) {
              this.open({ force: true });
            } else {
              this.close({ force: true });
            }
          }

          // Handle auto-locking breadcrumbs that should be locked.
          if (
            this.isLocked ||
            (this.lockInsideBreakpoint &&
              window.matchMedia(this.mediaQuery).matches) ||
            (this.lockOutsideBreakpoint &&
              !window.matchMedia(this.mediaQuery).matches)
          ) {
            this.lock({ force: true });
          } else {
            this.unlock({ force: true });
          }
        });
      }
    );

    // Set up custom validation.
    this._addEventListener(
      "grauplComponentValidate",
      this.rootDOMElement,
      () => {
        // Boolean checks.
        const booleans = {
          openOnFocus: this._openOnFocus,
          closeOnBlur: this._closeOnBlur,
          openInsideBreakpoint: this._openInsideBreakpoint,
          openOutsideBreakpoint: this._openOutsideBreakpoint,
          closeInsideBreakpoint: this._closeInsideBreakpoint,
          closeOutsideBreakpoint: this._closeOutsideBreakpoint,
          lockInsideBreakpoint: this._lockInsideBreakpoint,
          lockOutsideBreakpoint: this._lockOutsideBreakpoint,
          unlockInsideBreakpoint: this._unlockInsideBreakpoint,
          unlockOutsideBreakpoint: this._unlockOutsideBreakpoint,
          locked: this._locked.value,
        };

        // Check the booleans.
        const booleanChecks = isValidType("boolean", booleans, {
          shouldThrow: false,
        });

        // Handle boolean check failure.
        if (!booleanChecks.status) {
          this._errors = [...this._errors, ...booleanChecks.errors];
          this._valid = false;
        }
      }
    );

    if (initialize) {
      this.initialize();
    }
  }

  /**
   * The class(es) to apply when the breadcrumb is locked.
   *
   * @type {string|string[]}
   *
   * @see _classes.locked
   */
  get lockedClass() {
    return this._classes.locked;
  }

  set lockedClass(value) {
    isValidClassList({ lockedClass: value });

    if (this._classes.locked !== value) {
      this._classes.locked = value;
    }
  }

  /**
   * The class(es) to apply when the breadcrumb is unlocked.
   *
   * @type {string|string[]}
   *
   * @see _classes.unlocked
   */
  get unlockedClass() {
    return this._classes.unlocked;
  }

  set unlockedClass(value) {
    isValidClassList({ unlockedClass: value });

    if (this._classes.unlocked !== value) {
      this._classes.unlocked = value;
    }
  }

  /**
   * The class(es) to apply when the breadcrumb is open.
   *
   * @type {string|string[]}
   *
   * @see _classes.open
   */
  get openClass() {
    return this._classes.open;
  }

  set openClass(value) {
    isValidClassList({ openClass: value });

    if (this._classes.open !== value) {
      this._classes.open = value;
    }
  }

  /**
   * The class(es) to apply when the breadcrumb is closed.
   *
   * @type {string|string[]}
   *
   * @see _classes.close
   */
  get closeClass() {
    return this._classes.close;
  }

  set closeClass(value) {
    isValidClassList({ closeClass: value });

    if (this._classes.close !== value) {
      this._classes.close = value;
    }
  }

  /**
   * The class(es) to apply when the breadcrumb is transitioning between open and closed.
   *
   * @type {string|string[]}
   *
   * @see _classes.transition
   */
  get transitionClass() {
    return this._classes.transition;
  }

  set transitionClass(value) {
    isValidClassList({ transitionClass: value });

    if (this._classes.transition !== value) {
      this._classes.transition = value;
    }
  }

  /**
   * The duration time (in milliseconds) for the transition between open and closed states.
   *
   * Setting this value will also set the --graupl-transition-duration CSS custom property on the breadcrumb.
   *
   * @type {number}
   *
   * @see _durations.transition
   */
  get transitionDuration() {
    return this._durations.transition;
  }

  set transitionDuration(value) {
    isValidType("number", { transitionDuration: value });

    if (this._durations.transition !== value) {
      this._durations.transition = value;
      this._setCustomProps();
    }
  }

  /**
   * The duration time (in milliseconds) for the transition from closed to open states.
   *
   * If openDuration is set to -1, the transitionDuration value will be used instead.
   *
   * Setting this value will also set the --graupl-open-transition-duration CSS custom property on the breadcrumb.
   *
   * @type {number}
   *
   * @see _durations.open
   */
  get openDuration() {
    if (this._durations.open === -1) return this.transitionDuration;

    return this._durations.open;
  }

  set openDuration(value) {
    isValidType("number", { openDuration: value });

    if (this._durations.open !== value) {
      this._durations.open = value;
      this._setCustomProps();
    }
  }

  /**
   * The duration time (in milliseconds) for the transition from open to closed states.
   *
   * If closeDuration is set to -1, the transitionDuration value will be used instead.
   *
   * Setting this value will also set the --graupl-close-transition-duration CSS custom property on the breadcrumb.
   *
   * @type {number}
   *
   * @see _durations.close
   */
  get closeDuration() {
    if (this._durations.close === -1) return this.transitionDuration;

    return this._durations.close;
  }

  set closeDuration(value) {
    isValidType("number", { closeDuration: value });

    if (this._durations.close !== value) {
      this._durations.close = value;
      this._setCustomProps();
    }
  }

  /**
   * Whether to open the breadcrumb when it gains focus in the DOM.
   *
   * @type {boolean}
   *
   * @see _openOnFocus
   */
  get openOnFocus() {
    return this._openOnFocus;
  }

  set openOnFocus(value) {
    isValidType("boolean", { openOnFocus: value });

    if (this._openOnFocus !== value) {
      this._openOnFocus = value;
    }
  }

  /**
   * Whether to close the breadcrumb when it loses focus in the DOM.
   *
   * @type {boolean}
   *
   * @see _closeOnBlur
   */
  get closeOnBlur() {
    return this._closeOnBlur;
  }

  set closeOnBlur(value) {
    isValidType("boolean", { closeOnBlur: value });

    if (this._closeOnBlur !== value) {
      this._closeOnBlur = value;
    }
  }

  /**
   * The open state of the breadcrumb.
   *
   * @readonly
   *
   * @type {boolean}
   *
   * @see _open
   */
  get isOpen() {
    return this._open.value;
  }

  /**
   * The open state of the breadcrumb that the user specifically triggered.
   *
   * @readonly
   *
   * @type {boolean}
   *
   * @see _open
   */
  get hasOpened() {
    return this._open.committed;
  }

  /**
   * A flag to open the breadcrumb when inside the breakpoint.
   *
   * @type {boolean}
   *
   * @see _openInsideBreakpoint
   */
  get openInsideBreakpoint() {
    return this._openInsideBreakpoint;
  }

  set openInsideBreakpoint(value) {
    isValidType("boolean", { openInsideBreakpoint: value });

    if (this._openInsideBreakpoint !== value) {
      this._openInsideBreakpoint = value;
    }
  }

  /**
   * A flag to open the breadcrumb when outside the breakpoint.
   *
   * @type {boolean}
   *
   * @see _openOutsideBreakpoint
   */
  get openOutsideBreakpoint() {
    return this._openOutsideBreakpoint;
  }

  set openOutsideBreakpoint(value) {
    isValidType("boolean", { openOutsideBreakpoint: value });

    if (this._openOutsideBreakpoint !== value) {
      this._openOutsideBreakpoint = value;
    }
  }

  /**
   * A flag to close the breadcrumb when inside the breakpoint.
   *
   * @type {boolean}
   *
   * @see _closeInsideBreakpoint
   */
  get closeInsideBreakpoint() {
    return this._closeInsideBreakpoint;
  }

  set closeInsideBreakpoint(value) {
    isValidType("boolean", { closeInsideBreakpoint: value });

    if (this._closeInsideBreakpoint !== value) {
      this._closeInsideBreakpoint = value;
    }
  }

  /**
   * A flag to close the breadcrumb when outside the breakpoint.
   *
   * @type {boolean}
   *
   * @see _closeOutsideBreakpoint
   */
  get closeOutsideBreakpoint() {
    return this._closeOutsideBreakpoint;
  }

  set closeOutsideBreakpoint(value) {
    isValidType("boolean", { closeOutsideBreakpoint: value });

    if (this._closeOutsideBreakpoint !== value) {
      this._closeOutsideBreakpoint = value;
    }
  }

  /**
   * A flag to lock the breadcrumb in its current state when inside the breakpoint.
   *
   * @type {boolean}
   *
   * @see _lockInsideBreakpoint
   */
  get lockInsideBreakpoint() {
    return this._lockInsideBreakpoint;
  }

  set lockInsideBreakpoint(value) {
    isValidType("boolean", { lockInsideBreakpoint: value });

    if (this._lockInsideBreakpoint !== value) {
      this._lockInsideBreakpoint = value;
    }
  }

  /**
   * A flag to lock the breadcrumb in its current state when outside the breakpoint.
   *
   * @type {boolean}
   *
   * @see _lockOutsideBreakpoint
   */
  get lockOutsideBreakpoint() {
    return this._lockOutsideBreakpoint;
  }

  set lockOutsideBreakpoint(value) {
    isValidType("boolean", { lockOutsideBreakpoint: value });

    if (this._lockOutsideBreakpoint !== value) {
      this._lockOutsideBreakpoint = value;
    }
  }

  /**
   * A flag to indicate if the breadcrumb is locked.
   *
   * @readonly
   *
   * @type {boolean}
   *
   * @see _locked
   */
  get isLocked() {
    return this._locked.value;
  }

  /**
   * The committed lock preference for the breadcrumb.
   *
   * @readonly
   *
   * @type {boolean}
   *
   * @see _locked
   */
  get shouldBeLocked() {
    return this._locked.committed;
  }

  /**
   * The current index of the accordion item.
   *
   * @readonly
   *
   * @type {number}
   *
   * @see _currentChild
   */
  get currentChild() {
    return this._currentChild;
  }

  set currentChild(value) {
    isValidType("number", { currentChild: value });

    if (
      this._currentChild !== value &&
      value >= 0 &&
      value < this.elements.breadcrumbItems.length
    ) {
      this._currentChild = value;
    }
  }

  /**
   * The currently selected breadcrumb item.
   *
   * @readonly
   *
   * @type {BreadcrumbItem}
   */
  get currentBreadcrumbItem() {
    return this.elements.breadcrumbItems[this.currentChild];
  }

  /**
   * Sets the IDs throughout the breadcrumb.
   *
   * The generated IDs use the key and follow the format:
   *  - breadcrumb: `breadcrumb-${key}`
   *  - toggle: `breadcrumb-toggle-${key}`
   *
   * @protected
   */
  _setIds() {
    this.dom.breadcrumb.id = this.dom.breadcrumb.id || `breadcrumb-${this.key}`;

    if (this.dom.breadcrumbToggle) {
      this.dom.breadcrumbToggle.id =
        this.dom.breadcrumbToggle.id || `breadcrumb-toggle-${this.key}`;
    }

    this._id = this.dom.breadcrumb.id;
  }

  /**
   * Sets ARIA attributes throughout the breadcrumb.
   *
   * The first steps are to ensure that the toggle has `aria-expanded` set to "false"
   * if it's not already explicitly set to "true".
   *
   * Then, set the `aria-controls` attribute on the toggle to the breadcrumb's ID.
   *
   * Finally, ensure the toggle element has a role of "button" if it is not a native button element.
   *
   * @protected
   */
  _setAriaAttributes() {
    if (!this.dom.breadcrumbToggle) return;

    // If the toggle element doesn't have aria-expanded set to true, set it to false.
    if (this.dom.breadcrumbToggle.getAttribute("aria-expanded") !== "true") {
      this.dom.breadcrumbToggle.setAttribute("aria-expanded", "false");
    }

    // Set the aria-controls attribute on the toggle to the breadcrumb's ID.
    this.dom.breadcrumbToggle.setAttribute(
      "aria-controls",
      this.dom.breadcrumb.id
    );

    // If the toggle element is not a button, set its role to button.
    if (
      !isTag(
        "button",
        { toggle: this.dom.breadcrumbToggle },
        { shouldThrow: false }
      ).status
    ) {
      this.dom.breadcrumbToggle.setAttribute("role", "button");
    }
  }

  /**
   * Sets custom props throughout the breadcrumb.
   *
   * The custom properties are:
   *   - `--graupl-breadcrumb-transition-duration`,
   *   - `--graupl-breadcrumb-open-transition-duration`, and
   *   - `--graupl-breadcrumb-close-transition-duration`.
   *
   * The prefix of `graupl-` can be changed by setting the breadcrumb's prefix value.
   *
   * @protected
   */
  _setCustomProps() {
    this.dom.breadcrumb.style.setProperty(
      `--${this.prefix}breadcrumb-transition-duration`,
      `${this.transitionDuration}ms`
    );

    this.dom.breadcrumb.style.setProperty(
      `--${this.prefix}breadcrumb-open-transition-duration`,
      `${this.openDuration}ms`
    );

    this.dom.breadcrumb.style.setProperty(
      `--${this.prefix}breadcrumb-close-transition-duration`,
      `${this.closeDuration}ms`
    );
  }

  /**
   * Sets all DOM elements within the breadcrumb.
   *
   * Utilizes _setDOMElementType and
   * _resetDOMElementType.
   *
   * @protected
   */
  _setDOMElements() {
    this._resetDOMElementType("breadcrumbItems");
    this._setDOMElementType("breadcrumbItems", {
      context: this.dom.breadcrumb,
    });

    this._resetDOMElementType("breadcrumbLinks");
    this._setDOMElementType("breadcrumbLinks", {
      context: this.dom.breadcrumb,
    });

    this._resetDOMElementType("breadcrumbToggle");
    this._setDOMElementType("breadcrumbToggle", {
      context: this.dom.breadcrumb,
    });
  }

  /**
   * Creates and initializes child elements within the breadcrumb.
   *
   * @protected
   */
  _createChildElements() {
    this.dom.breadcrumbItems.forEach((element) => {
      const link = element.querySelector(this.selectors.breadcrumbLinks);
      const toggle =
        element.querySelector(this.selectors.breadcrumbToggle) !== null;
      const itemElement = new BreadcrumbItem({
        breadcrumbItemElement: element,
        breadcrumbLinkElement: link,
        parentBreadcrumb: this,
        isToggle: toggle,
      });

      this.elements.breadcrumbItems.push(itemElement);

      if (toggle) {
        this._elements.breadcrumbToggle = itemElement;
      }
    });
  }

  /**
   * Expands the breadcrumb.
   *
   * Sets the toggle's `aria-expanded` to "true", adds the
   * open class to the breadcrumb, and removes the closed class from the breadcrumb.
   *
   * @protected
   *
   * @fires grauplBreadcrumbExpand
   *
   * @param {Object<boolean>} [options = {}]                            - Options for expanding the breadcrumb.
   * @param {boolean}         [options.emit = this.isInitialized]       - Emit the expand event once expanded.
   * @param {boolean}         [options.transition = this.isInitialized] - Respect the transition class.
   */
  _reveal({ emit = this.isInitialized, transition = this.isInitialized } = {}) {
    if (this.dom.breadcrumbToggle) {
      this.dom.breadcrumbToggle.setAttribute("aria-expanded", "true");
    }

    // If we're dealing with transition classes, then we need to utilize
    // requestAnimationFrame to add the transition class, remove the close class,
    // add the open class, and finally remove the transition class.
    if (transition && this.transitionlass !== "") {
      addClass(this.transitionClass, this.dom.breadcrumb);

      requestAnimationFrame(() => {
        removeClass(this.closeClass, this.dom.breadcrumb);

        requestAnimationFrame(() => {
          addClass(this.openClass, this.dom.breadcrumb);

          requestAnimationFrame(() => {
            setTimeout(() => {
              removeClass(this.transitionClass, this.dom.breadcrumb);
            }, this.openDuration);
          });
        });
      });
    } else {
      // Add the open class
      addClass(this.openClass, this.dom.breadcrumb);

      // Remove the close class.
      removeClass(this.closeClass, this.dom.breadcrumb);
    }

    if (emit) {
      if (this.dom.breadcrumbToggle) {
        this._dispatchEvent("expand", this.dom.breadcrumbToggle);
      } else {
        this._dispatchEvent("expand", this.dom.breadcrumb);
      }
    }
  }

  /**
   * Collapses the breadcrumb.
   *
   * Sets the toggle's `aria-expanded` to "false", adds the
   * close class to the breadcrumb, and removes the open class from the breadcrumb.
   *
   * @protected
   *
   * @fires grauplBreadcrumbCollapse
   *
   * @param {Object<boolean>} [options = {}]                            - Options for collapsing the breadcrumb.
   * @param {boolean}         [options.emit = this.isInitialized]       - Emit the collapse event once collapsed.
   * @param {boolean}         [options.transition = this.isInitialized] - Respect the transition class.
   */
  _conceal({
    emit = this.isInitialized,
    transition = this.isInitialized,
  } = {}) {
    if (this.dom.breadcrumbToggle) {
      this.dom.breadcrumbToggle.setAttribute("aria-expanded", "false");
    }

    // If we're dealing with transition classes, then we need to utilize
    // requestAnimationFrame to add the transition class, remove the open class,
    // add the close class, and finally remove the transition class.
    if (transition && this.transitionClass !== "") {
      addClass(this.transitionClass, this.dom.breadcrumb);

      requestAnimationFrame(() => {
        removeClass(this.openClass, this.dom.breadcrumb);

        requestAnimationFrame(() => {
          addClass(this.closeClass, this.dom.breadcrumb);

          requestAnimationFrame(() => {
            setTimeout(() => {
              removeClass(this.transitionClass, this.dom.breadcrumb);
            }, this.closeDuration);
          });
        });
      });
    } else {
      // Add the close class
      addClass(this.closeClass, this.dom.breadcrumb);

      // Remove the open class.
      removeClass(this.openClass, this.dom.breadcrumb);
    }

    if (emit) {
      if (this.dom.breadcrumbToggle) {
        this._dispatchEvent("collapse", this.dom.breadcrumbToggle);
      } else {
        this._dispatchEvent("collapse", this.dom.breadcrumb);
      }
    }
  }

  /**
   * Applies the locked state styling and dispatches the lock event.
   *
   * @protected
   *
   * @param {Object<boolean>} [options = {}]                      - Options for the lock side effects.
   * @param {boolean}         [options.emit = this.isInitialized] - Whether to emit the lock event.
   */
  _lock({ emit = this.isInitialized } = {}) {
    // Add the locked class
    addClass(this.lockedClass, this.dom.breadcrumb);

    // Remove the unlocked class.
    removeClass(this.unlockedClass, this.dom.breadcrumb);

    if (this.dom.breadcrumbToggle) {
      this.dom.breadcrumbToggle.setAttribute("disabled", "true");
    }

    if (emit) {
      if (this.dom.breadcrumbToggle) {
        this._dispatchEvent("lock", this.dom.breadcrumbToggle);
      } else {
        this._dispatchEvent("lock", this.dom.breadcrumb);
      }
    }
  }

  /**
   * Applies the unlocked state styling and dispatches the unlock event.
   *
   * @protected
   *
   * @param {Object<boolean>} [options = {}]                      - Options for the unlock side effects.
   * @param {boolean}         [options.emit = this.isInitialized] - Whether to emit the unlock event.
   */
  _unlock({ emit = this.isInitialized } = {}) {
    // Add the unlocked class
    addClass(this.unlockedClass, this.dom.breadcrumb);

    // Remove the locked class.
    removeClass(this.lockedClass, this.dom.breadcrumb);

    if (this.dom.breadcrumbToggle) {
      this.dom.breadcrumbToggle.removeAttribute("disabled");
    }

    if (emit) {
      if (this.dom.breadcrumbToggle) {
        this._dispatchEvent("unlock", this.dom.breadcrumbToggle);
      } else {
        this._dispatchEvent("unlock", this.dom.breadcrumb);
      }
    }
  }

  /**
   * Handles focus events throughout the breadcrumb.
   *
   * - Adds a `focusout` listener to the breadcrumb so when the breadcrumb loses focus it will close.
   */
  _handleFocus() {
    this.elements.breadcrumbItems.forEach((breadcrumbItem, index) => {
      if (!breadcrumbItem.dom.link) {
        return;
      }

      this._addEventListener("focus", breadcrumbItem.dom.link, () => {
        this.focusState = "self";
        this.currentChild = index;
      });
    });

    this._addEventListener("focusout", this.dom.breadcrumb, (event) => {
      if (
        !this.closeOnBlur ||
        this.currentEvent !== "keyboard" ||
        event.relatedTarget === null ||
        this.dom.breadcrumb.contains(event.relatedTarget) ||
        this.dom.breadcrumbToggle === event.relatedTarget
      ) {
        return;
      }

      this.close();
    });
  }

  /**
   * Handles click events throughout the breadcrumb.
   *
   * - Adds a `click` listener to the toggle that toggles the breadcrumb.
   * - Adds a `click` listener to the `document` so if the user clicks outside the breadcrumb it will close.
   */
  _handleClick() {
    this._addEventListener("click", document, (event) => {
      if (this.focusState !== "self" || !this.closeOnBlur) return;

      this.currentEvent = "mouse";

      if (
        !this.dom.breadcrumb.contains(event.target) &&
        this.dom.breadcrumbToggle !== event.target
      ) {
        this.close();
      }
    });

    if (!this.dom.breadcrumbToggle) return;

    this._addEventListener("click", this.dom.breadcrumbToggle, (event) => {
      this.currentEvent = "mouse";

      if (event.button !== 0) return;

      preventEvent(event);
      this.toggle();
    });
  }

  /**
   * Handles keydown events throughout the breadcrumb.
   *
   * This method exists to assist the _handleKeyup method.
   *
   * - Adds a `keydown` listener to the toggle.
   *   - Blocks propagation on "Space" and "Enter" keys.
   * - Adds a `keydown` listener to the breadcrumb.
   *   - Blocks propagation on "Escape" keys.
   */
  _handleKeydown() {
    this._addEventListener("keydown", this.dom.breadcrumb, (event) => {
      this.currentEvent = "keyboard";

      const key = keyPress(event);

      switch (key) {
        case "Escape":
          preventEvent(event);

          break;
      }
    });

    if (!this.dom.breadcrumbToggle) return;

    this._addEventListener("keydown", this.dom.breadcrumbToggle, (event) => {
      this.currentEvent = "keyboard";

      const key = keyPress(event);

      switch (key) {
        case "Space":
        case "Enter":
          preventEvent(event);

          break;
      }
    });
  }

  /**
   * Handles keyup events throughout the breadcrumb.
   *
   * - Adds a `keyup` listener to the toggle.
   *   - Toggles the breadcrumb on "Space" and "Enter" keys.
   * - Adds a `keyup` listener to the breadcrumb.
   *   - Closes the breadcrumb on "Escape" keys.
   */
  _handleKeyup() {
    this._addEventListener("keyup", this.dom.breadcrumb, (event) => {
      this.currentEvent = "keyboard";

      const key = keyPress(event);

      switch (key) {
        case "Escape":
          preventEvent(event);
          this.close();

          if (
            this.currentChild >
            this.elements.breadcrumbItems.indexOf(
              this.elements.breadcrumbToggle
            )
          ) {
            requestAnimationFrame(() => {
              this.focusToggle();
            });
          }

          break;
      }
    });

    if (!this.dom.breadcrumbToggle) return;

    this._addEventListener("keyup", this.dom.breadcrumbToggle, (event) => {
      this.currentEvent = "keyboard";

      const key = keyPress(event);

      switch (key) {
        case "Space":
        case "Enter":
          preventEvent(event);
          this.toggle();

          if (this.isOpen) {
            requestAnimationFrame(() => {
              this.focusNextChild();
            });
          } else {
            this.focusFirstChild();
          }

          break;

        case "Tab":
          if (this.openOnFocus) {
            preventEvent(event);
            this.open();

            requestAnimationFrame(() => {
              this.focusNextChild();
            });
          }

          break;
      }
    });
  }

  /**
   * Opens the breadcrumb.
   *
   * Sets the breadcrumb's focus state to "self", calls expand, and sets isOpen to `true`.
   *
   * @param {Object<boolean>} [options = {}]                            - Options for opening the breadcrumb.
   * @param {boolean}         [options.force = false]                   - Whether to force the preview action.
   * @param {boolean}         [options.emit = this.isInitialized]       - Whether to emit the expand event once previewed.
   * @param {boolean}         [options.transition = this.isInitialized] - Respect the transition class.
   * @param {boolean}         [options.preserveState = false]           - Whether to preserve the open state.
   */
  open({
    force = false,
    emit = this.isInitialized,
    transition = this.isInitialized,
    preserveState = false,
  } = {}) {
    if (this.isOpen && !force) return;
    if (this.isLocked && !force) return;

    // Set the focus state.
    this.focusState = "self";

    // Expand the breadcrumb.
    this._reveal({ emit, transition });

    // Set the open state.
    this._open.value = true;

    if (!preserveState) {
      // Commit the open state.
      this._open.commit();
    }
  }

  /**
   * Opens the breadcrumb without entering it.
   *
   * Sets the breadcrumb's focus state to "none", calls expand, and sets isOpen to `true`.
   *
   * @param {Object<boolean>} [options = {}]                            - Options for previewing the breadcrumb.
   * @param {boolean}         [options.force = false]                   - Whether to force the preview action.
   * @param {boolean}         [options.emit = this.isInitialized]       - Whether to emit the expand event once previewed.
   * @param {boolean}         [options.transition = this.isInitialized] - Respect the transition class.
   * @param {boolean}         [options.preserveState = false]           - Whether to preserve the open state.
   */
  preview({
    force = false,
    emit = this.isInitialized,
    transition = this.isInitialized,
    preserveState = false,
  } = {}) {
    if (this.isOpen && !force) return;
    if (this.isLocked && !force) return;

    // Set the focus state.
    this.focusState = "none";

    // Expand the breadcrumb.
    this._reveal({ emit, transition });

    // Set the open state.
    this._open.value = true;

    if (!preserveState) {
      // Commit the open state.
      this._open.commit();
    }
  }

  /**
   * Closes the breadcrumb.
   *
   * Sets the breadcrumb's focus state to "none", calls collapse, and sets isOpen to `false`.
   *
   * @param {Object<boolean>} [options = {}]                            - Options for closing the breadcrumb.
   * @param {boolean}         [options.force = false]                   - Whether to force the preview action.
   * @param {boolean}         [options.emit = this.isInitialized]       - Whether to emit the expand event once previewed.
   * @param {boolean}         [options.transition = this.isInitialized] - Respect the transition class.
   * @param {boolean}         [options.preserveState = false]           - Whether to preserve the open state.
   */
  close({
    force = false,
    emit = this.isInitialized,
    transition = this.isInitialized,
    preserveState = false,
  } = {}) {
    if (!this.isOpen && !force) return;
    if (this.isLocked && !force) return;

    // Set the focus state.
    this.focusState = "none";

    // Collapse the breadcrumb.
    this._conceal({ emit, transition });

    // Set the open state.
    this._open.value = false;

    if (!preserveState) {
      // Commit the open state.
      this._open.commit();
    }
  }

  /**
   * Toggles the open state of the breadcrumb.
   *
   * @param {Object<boolean>} [options = {}]                            - Options for toggling the breadcrumb.
   * @param {boolean}         [options.force = false]                   - Whether to force the preview action.
   * @param {boolean}         [options.emit = this.isInitialized]       - Whether to emit the expand event once previewed.
   * @param {boolean}         [options.transition = this.isInitialized] - Respect the transition class.
   * @param {boolean}         [options.preserveState = false]           - Whether to preserve the open state.
   */
  toggle({
    force = false,
    emit = this.isInitialized,
    transition = this.isInitialized,
    preserveState = false,
  } = {}) {
    if (this.isOpen) {
      this.close({
        force,
        emit,
        transition,
        preserveState,
      });
    } else {
      this.open({
        force,
        emit,
        transition,
        preserveState,
      });
    }
  }

  /**
   * Locks the breadcrumb.
   *
   * @param {Object<boolean>} [options = {}]                      - Options for locking the breadcrumb.
   * @param {boolean}         [options.force = false]             - Whether to force the lock action.
   * @param {boolean}         [options.emit = this.isInitialized] - Whether to emit the lock event.
   * @param {boolean}         [options.preserveState = false]     - Whether to preserve the locked state.
   */
  lock({
    force = false,
    emit = this.isInitialized,
    preserveState = false,
  } = {}) {
    // Only lock if the breadcrumb is unlocked.
    if (this.isLocked && !force) return;

    this._locked.value = true;
    this._lock({ emit });

    if (!preserveState) {
      // Commit the locked state.
      this._locked.commit();
    }
  }

  /**
   * Unlocks the breadcrumb.
   *
   * @param {Object<boolean>} [options = {}]                      - Options for unlocking the breadcrumb.
   * @param {boolean}         [options.force = false]             - Whether to force the unlock action.
   * @param {boolean}         [options.emit = this.isInitialized] - Whether to emit the unlock event.
   * @param {boolean}         [options.preserveState = false]     - Whether to preserve the unlocked state.
   */
  unlock({
    force = false,
    emit = this.isInitialized,
    preserveState = false,
  } = {}) {
    // Only unlock if the breadcrumb is locked.
    if (!this.isLocked && !force) return;

    this._locked.value = false;
    this._unlock({ emit });

    if (!preserveState) {
      // Commit the locked state.
      this._locked.commit();
    }
  }

  /**
   * Toggles the locked state of the breadcrumb.
   *
   * @param {Object<boolean>} [options = {}]                      - Options for toggling the lock state.
   * @param {boolean}         [options.force = false]             - Whether to force the toggle action.
   * @param {boolean}         [options.emit = this.isInitialized] - Whether to emit the lock/unlock event.
   * @param {boolean}         [options.preserveState = false]     - Whether to preserve the locked/unlocked state.
   */
  toggleLock({
    force = false,
    emit = this.isInitialized,
    preserveState = false,
  } = {}) {
    if (this.isLocked) {
      this.unlock({ force, emit, preserveState });
    } else {
      this.lock({ force, emit, preserveState });
    }
  }

  /**
   * Focus the breadcrumb's current child.
   */
  focusCurrentChild() {
    this.focusState = "self";

    if (this.currentChild !== -1) {
      this.currentBreadcrumbItem.focus();
    }
  }

  /**
   * Focuses the breadcrumb's child at a given index.
   *
   * @param {number} index - The index of the child to focus.
   */
  focusChild(index) {
    this.blurCurrentChild();
    this.currentChild = index;
    this.focusCurrentChild();
  }

  /**
   * Focuses the breadcrumb's first child.
   */
  focusFirstChild() {
    this.focusChild(0);
  }

  /**
   * Focus the breadcrumb's last child.
   */
  focusLastChild() {
    this.focusChild(this.elements.breadcrumbItems.length - 1);
  }

  /**
   * Focus the breadcrumb's next child.
   */
  focusNextChild() {
    if (this.currentChild < this.elements.breadcrumbItems.length - 1) {
      this.focusChild(this.currentChild + 1);
    } else {
      this.focusCurrentChild();
    }
  }

  /**
   * Focus the breadcrumb's previous child.
   */
  focusPreviousChild() {
    if (this.currentChild > 0) {
      this.focusChild(this.currentChild - 1);
    } else {
      this.focusCurrentChild();
    }
  }

  /**
   * Blurs the breadcrumb's current child.
   */
  blurCurrentChild() {
    this.focusState = "none";

    if (this.currentChild !== -1) {
      this.currentBreadcrumbItem.blur();
    }
  }

  /**
   * Focuses the breadcrumb toggle.
   */
  focusToggle() {
    this.focusState = "self";

    if (this.elements.breadcrumbToggle !== null) {
      this.currentChild =
        this.elements.breadcrumbItems.indexOf(this.elements.breadcrumbToggle) ||
        0;

      this.elements.breadcrumbToggle.focus();
    }
  }
}

export default Breadcrumb;
