import { isValidClassList, isValidType } from "@graupl/core/src/validate.js";
import { isValidSideType } from "../validate.js";
import { keyPress, preventEvent } from "@graupl/core/src/eventHandlers.js";
import {
  addClass,
  removeClass,
  selectFirstFocusableElement,
} from "@graupl/core/src/domHelpers.js";
import TransactionalValue from "@graupl/core/src/TransactionalValue.js";
import Component from "@graupl/core/src/Component.js";

/**
 * The event that is triggered when the shelf expands.
 *
 * @event grauplNavigationShelfExpand
 *
 * @type {CustomEvent}
 *
 * @property {boolean}                 bubbles      - A flag to bubble the event.
 * @property {Object<NavigationShelf>} detail       - The details object containing the NavigationShelf itself.
 * @property {NavigationShelf}         detail.shelf - The navigation shelf.
 */

/**
 * The event that is triggered when the shelf collapses.
 *
 * @event grauplNavigationShelfCollapse
 *
 * @type {CustomEvent}
 *
 * @property {boolean}                 bubbles      - A flag to bubble the event.
 * @property {Object<NavigationShelf>} detail       - The details object containing the NavigationShelf itself.
 * @property {NavigationShelf}         detail.shelf - The navigation shelf.
 */

/**
 * The event that is triggered when the shelf is locked.
 *
 * @event grauplNavigationShelfLock
 *
 * @type {CustomEvent}
 *
 * @property {boolean}                 bubbles      - A flag to bubble the event.
 * @property {Object<NavigationShelf>} detail       - The details object containing the NavigationShelf itself.
 * @property {NavigationShelf}         detail.shelf - The navigation shelf.
 */

/**
 * The event that is triggered when the shelf is unlocked.
 *
 * @event grauplNavigationShelfUnlock
 *
 * @type {CustomEvent}
 *
 * @property {boolean}                 bubbles      - A flag to bubble the event.
 * @property {Object<NavigationShelf>} detail       - The details object containing the NavigationShelf itself.
 * @property {NavigationShelf}         detail.shelf - The navigation shelf.
 */

/**
 * The event that is triggered when the shelf has shifted sides.
 *
 * @event grauplNavigationShelfShiftSide
 *
 * @type {CustomEvent}
 *
 * @property {boolean}                 bubbles      - A flag to bubble the event.
 * @property {Object<NavigationShelf>} detail       - The details object containing the NavigationShelf itself.
 * @property {NavigationShelf}         detail.shelf - The navigation shelf.
 */

/**
 * The event that is triggered when the shelf's hoverability is enabled.
 *
 * @event grauplNavigationShelfEnableHoverable
 *
 * @type {CustomEvent}
 *
 * @property {boolean}                 bubbles      - A flag to bubble the event.
 * @property {Object<NavigationShelf>} detail       - The details object containing the NavigationShelf itself.
 * @property {NavigationShelf}         detail.shelf - The navigation shelf.
 */

/**
 * The event that is triggered when the shelf's hoverability is disabled.
 *
 * @event grauplNavigationShelfDisableHover
 *
 * @type {CustomEvent}
 *
 * @property {boolean}                 bubbles      - A flag to bubble the event.
 * @property {Object<NavigationShelf>} detail       - The details object containing the NavigationShelf itself.
 * @property {NavigationShelf}         detail.shelf - The navigation shelf.
 */

/**
 * The Navigation shelf component.
 *
 * @extends Component
 *
 * Protected fields are documented below.
 *
 * @property {Object<HTMLElement, HTMLElement[]>}   _dom                         - The DOM elements within the navigation shelf.
 * @property {HTMLElement}                          _dom.shelf                   - The shelf element.
 * @property {HTMLElement}                          _dom.controller              - The toggle for the shelf.
 * @property {HTMLElement}                          _dom.lockController          - The toggle for locking the shelf.
 * @property {HTMLElement}                          _dom.hoverController         - The toggle for hoverability of the shelf.
 * @property {HTMLElement}                          _dom.sideController          - The toggle for the side controller of the shelf.
 * @property {HTMLElement[]}                        _dom.dependents              - The list of dependent elements updated when the shelf opens or closes.
 * @property {string}                               _rootDOMElement              - The root DOM element of the navigation shelf.
 * @property {string[]}                             _protectedDOMElements        - The DOM elements within the navigation shelf that cannot be reset or generated by the navigation shelf itself.
 * @property {Object<string>}                       _selectors                   - The query selectors used by the navigation shelf.
 * @property {string}                               _selectors.dependents        - The query selector for dependent elements.
 * @property {Object<string, string[]>}             _classes                     - The classes to apply when the navigation shelf is in various states.
 * @property {string|string[]}                      _classes.locked              - The class(es) to apply to the shelf and dependent elements when the shelf is locked.
 * @property {string|string[]}                      _classes.unlocked            - The class(es) to apply to the shelf and dependent elements when the shelf is unlocked.
 * @property {string|string[]}                      _classes.hover               - The class(es) to apply to the shelf element when the shelf is hoverable.
 * @property {string|string[]}                      _classes.noHover             - The class(es) to apply to the shelf element when the shelf is not hoverable.
 * @property {string|string[]}                      _classes.left                - The class(es) to apply to the shelf and dependent elements when the shelf is on the left side.
 * @property {string|string[]}                      _classes.right               - The class(es) to apply to the shelf and dependent elements when the shelf is on the right side.
 * @property {string|string[]}                      _classes.open                - The class(es) to apply to the shelf when the shelf is open.
 * @property {string|string[]}                      _classes.close               - The class(es) to apply to the shelf when the shelf is closed.
 * @property {string|string[]}                      _classes.transition          - The class(es) to apply to the shelf and dependent elements when the shelf is transitioning between states.
 * @property {string|string[]}                      _classes.initialize          - The class(es) to apply to the shelf when the shelf is initializing.
 * @property {Object<number>}                       _durations                   - The duration times (in milliseconds) for various aspects throughout the navigation shelf.
 * @property {number}                               _durations.transition        - The duration time (in milliseconds) for the transition between open and closed states.
 * @property {number}                               _durations.open              - The duration time (in milliseconds) for the transition from closed to open states.
 * @property {number}                               _durations.close             - The duration time (in milliseconds) for the transition from open to closed states.
 * @property {Object<number>}                       _delays                      - The delay times (in milliseconds) for various aspects throughout the navigation shelf.
 * @property {number}                               _delays.hover                - The delay time (in milliseconds) used for pointerenter/pointerleave events to take place.
 * @property {number}                               _delays.enter                - The delay time (in milliseconds) used for pointerenter events to take place.
 * @property {number}                               _delays.leave                - The delay time (in milliseconds) used for pointerleave events to take place.
 * @property {boolean}                              _hover                       - A flag to indicate if the shelf is hoverable.
 * @property {TransactionalValue<boolean>}          _locked                      - A flag to indicate if the navigation shelf is locked.
 * @property {boolean}                              _softLocked                  - A flag to check if the shelf can dynamically close based on manual interaction.
 * @property {string}                               _side                        - The side of the screen the navigation shelf is on.
 * @property {string}                               _otherSide                   - The opposite side of the screen the navigation shelf is on.
 * @property {boolean}                              _open                        - The open state of the shelf.
 * @property {Function}                             _mediaQueryListEventCallback - The callback for media query list events.
 * @property {Object<CustomEvent>}                  _events                      - Custom events that can be triggered throughout the navigation shelf.
 * @property {grauplNavigationShelfExpand}          _events.expand               - The event triggered when the shelf expands.
 * @property {grauplNavigationShelfCollapse}        _events.collapse             - The event triggered when the shelf collapses.
 * @property {grauplNavigationShelfLock}            _events.lock                 - The event triggered when the shelf is locked.
 * @property {grauplNavigationShelfUnlock}          _events.unlock               - The event triggered when the shelf is unlocked.
 * @property {grauplNavigationShelfShiftSide}       _events.shiftSide            - The event triggered when the shelf shifts sides.
 * @property {grauplNavigationShelfEnableHoverable} _events.enableHover          - The event triggered when hoverability is enabled.
 * @property {grauplNavigationShelfDisableHover}    _events.disableHover         - The event triggered when hoverability is disabled.
 * @property {string}                               _storageKey                  - The key used for storage.
 * @property {boolean}                              _shouldStore                 - A flag to check if the component should be stored in the StorageManager.
 * @property {Object<object>}                       _elements                    - The instantiated elements within the navigation shelf.
 * @property {string}                               _focusState                  - The current state of the navigation shelf's focus.
 * @property {string}                               _currentEvent                - The last type of event triggered within the navigation shelf.
 * @property {string}                               _breakpoint                  - The breakpoint that the navigation shelf will call media query list events.
 * @property {string}                               _mediaQueryString            - The media query to use to trigger media query list events.
 * @property {MediaQueryList|null}                  _mediaQueryList              - The MediaQueryList for the navigation shelf.
 * @property {Object<Function>}                     _intervals                   - Intervals throughout the navigation shelf.
 * @property {Object<Function>}                     _timeouts                    - Timeouts throughout the navigation shelf.
 * @property {object[]}                             _listeners                   - Event listeners throughout the navigation shelf.
 * @property {string}                               _prefix                      - The prefix used for CSS custom properties and attributes.
 * @property {string}                               _key                         - The key used to generate IDs throughout the navigation shelf.
 * @property {string}                               _name                        - The component name of the navigation shelf.
 * @property {string}                               _id                          - The main ID of the navigation shelf.
 * @property {boolean}                              _valid                       - The validity state of the navigation shelf.
 * @property {boolean}                              _initialized                 - The initialized state of the navigation shelf.
 * @property {string[]}                             _errors                      - The errors found throughout the navigation shelf.
 */
class NavigationShelf extends Component {
  _rootDOMElement = "shelf";
  _protectedDOMElements = [
    "controller",
    "lockController",
    "hoverController",
    "sideController",
  ];
  _hover = false;
  _locked = new TransactionalValue(false);
  _softLocked = false;
  _side = "left";
  _otherSide = "right";
  _open = false;
  _mediaQueryListEventCallback = (event) => {
    if (event.matches) {
      if (this.isOpen) {
        this.close({
          preserveLock: this.shouldBeLocked,
        });
      }

      if (this.dom.lockController) {
        this.dom.lockController.setAttribute("disabled", "disabled");
      }
    } else {
      if (this.shouldBeLocked && !this.isOpen) {
        this._locked.reset();
        this.lock({ force: true });
      }

      if (this.dom.lockController) {
        this.dom.lockController.removeAttribute("disabled");
      }
    }
  };
  _storageKey = "navigation-shelves";
  _name = "NavigationShelf";

  /**
   * Constructs a new `NavigationShelf`.
   *
   * @param {object}             [options = {}]                             - The options for generating the navigation shelf.
   * @param {HTMLElement}        options.shelfElement                       - The shelf element in the DOM.
   * @param {?HTMLElement}       [options.controllerElement = null]         - The toggle for this shelf.
   * @param {?HTMLElement}       [options.lockControllerElement = null]     - The toggle for locking this shelf.
   * @param {?HTMLElement}       [options.hoverControllerElement = null]    - The toggle for hoverability of this shelf.
   * @param {?HTMLElement}       [options.sideControllerElement = null]     - The toggle for the side controller of this shelf.
   * @param {string}             [options.dependentSelector = .shelf-aware] - The query selector for dependent elements.
   * @param {?(string|string[])} [options.lockedClass = locked]             - The class(es) to apply when the shelf is locked.
   * @param {?(string|string[])} [options.unlockedClass = unlocked]         - The class(es) to apply when the shelf is unlocked.
   * @param {?(string|string[])} [options.hoverClass = hoverable]           - The class(es) to apply when the shelf is hoverable.
   * @param {?(string|string[])} [options.noHoverClass = not-hoverable]     - The class(es) to apply when the shelf is not hoverable.
   * @param {?(string|string[])} [options.leftClass = left-side]            - The class(es) to apply when the shelf is on the left side.
   * @param {?(string|string[])} [options.rightClass = right-side]          - The class(es) to apply when the shelf is on the right side.
   * @param {?(string|string[])} [options.openClass = show]                 - The class(es) to apply when the shelf is open.
   * @param {?(string|string[])} [options.closeClass = hide]                - The class(es) to apply when the shelf is closed.
   * @param {?(string|string[])} [options.transitionClass = transitioning]  - The class(es) to apply when the shelf is transitioning between states.
   * @param {number}             [options.transitionDuration = 250]         - The duration of the transition between open and closed states (in milliseconds).
   * @param {number}             [options.openDuration = -1]                - The duration of the transition from closed to open states (in milliseconds).
   * @param {number}             [options.closeDuration = -1]               - The duration of the transition from open to closed states (in milliseconds).
   * @param {boolean}            [options.hoverable = false]                - A flag to indicate if the shelf is hoverable.
   * @param {number}             [options.hoverDelay = 250]                 - The delay time (in milliseconds) used for hover events.
   * @param {number}             [options.enterDelay = -1]                  - The delay time (in milliseconds) used for pointerenter events.
   * @param {number}             [options.leaveDelay = -1]                  - The delay time (in milliseconds) used for pointerleave events.
   * @param {boolean}            [options.locked = false]                   - A flag to indicate if the shelf is locked.
   * @param {string}             [options.side = left]                      - The side of the screen the shelf is on.
   * @param {?string}            [options.minWidth = 1023px]                - The minimum width at which the shelf can auto-toggle.
   * @param {?string}            [options.mediaQuery = ""]                  - The media query to use when automatically opening/closing the shelf.
   * @param {?string}            [options.prefix = graupl-]                 - The prefix used for CSS custom properties and attributes.
   * @param {?string}            [options.key = null]                       - The key used to generate IDs throughout the shelf.
   * @param {?(string|string[])} [options.initializeClass = initializing]   - The class(es) to apply when the shelf is initializing.
   * @param {boolean}            [options.initialize = false]               - A flag to initialize the shelf immediately upon creation.
   */
  constructor({
    shelfElement,
    controllerElement,
    lockControllerElement,
    hoverControllerElement,
    sideControllerElement,
    dependentSelector = ".shelf-aware",
    lockedClass = "locked",
    unlockedClass = "unlocked",
    hoverClass = "hoverable",
    noHoverClass = "not-hoverable",
    leftClass = "left-side",
    rightClass = "right-side",
    openClass = "show",
    closeClass = "hide",
    transitionClass = "transitioning",
    transitionDuration = 250,
    openDuration = -1,
    closeDuration = -1,
    hoverable = false,
    hoverDelay = 250,
    enterDelay = -1,
    leaveDelay = -1,
    locked = false,
    side = "left",
    minWidth = "1023px",
    mediaQuery = "",
    prefix = "graupl-",
    key = null,
    initializeClass = "initializing",
    initialize = false,
  } = {}) {
    super({
      prefix,
      key,
      initializeClass,
    });

    // Set DOM elements.
    this._dom.shelf = shelfElement;
    this._dom.controller = controllerElement || null;
    this._dom.lockController = lockControllerElement || null;
    this._dom.hoverController = hoverControllerElement || null;
    this._dom.sideController = sideControllerElement || null;
    this._dom.dependents = [];

    // Set DOM selectors.
    this._selectors.dependents = dependentSelector;

    // Set classes.
    this._classes.locked = lockedClass || "";
    this._classes.unlocked = unlockedClass || "";
    this._classes.hover = hoverClass || "";
    this._classes.noHover = noHoverClass || "";
    this._classes.left = leftClass || "";
    this._classes.right = rightClass || "";
    this._classes.open = openClass || "";
    this._classes.close = closeClass || "";
    this._classes.transition = transitionClass || "";

    // Set transition duration.
    this._durations.transition = transitionDuration;
    this._durations.open = openDuration;
    this._durations.close = closeDuration;

    // Set locked state.
    this._locked = new TransactionalValue(locked);

    // Set the breakpoint and media query.
    this._breakpoint = minWidth;
    this._mediaQueryString = mediaQuery || "";

    // Set side.
    this._side = side;

    if (this._side === "right") {
      this._otherSide = "left";
    }

    // Set hover settings.
    this._hover = hoverable;
    this._delays.hover = hoverDelay;
    this._delays.enter = enterDelay;
    this._delays.leave = leaveDelay;

    // Register custom events.
    this._registerEvent("expand", { detail: { shelf: this } });
    this._registerEvent("collapse", { detail: { shelf: this } });
    this._registerEvent("lock", { detail: { shelf: this } });
    this._registerEvent("unlock", { detail: { shelf: this } });
    this._registerEvent("shiftSide", { detail: { shelf: this } });
    this._registerEvent("enableHover", { detail: { shelf: this } });
    this._registerEvent("disableHover", { detail: { shelf: this } });

    // Set up custom initialization.
    this._addEventListener(
      "grauplComponentInitialize",
      this.rootDOMElement,
      () => {
        // Ensure the initial open state of the shelf.
        if (this._mediaQueryList.matches) {
          this.close({
            force: true,
            emit: false,
            transition: false,
            preserveLock: this.isLocked,
          });

          if (this.dom.lockController) {
            this.dom.lockController.setAttribute("disabled", "disabled");
          }
        } else {
          if (
            this.dom.controller.getAttribute("aria-expanded") === "true" ||
            this.isLocked
          ) {
            this.open({ emit: false, transition: false });

            if (this.isLocked) {
              this.lock({ force: true });
            }
          }

          if (this.dom.lockController) {
            this.dom.lockController.removeAttribute("disabled");
          }
        }

        // Ensure the initial hoverability of the shelf.
        if (this.hover) {
          this._enableHover({ emit: false });
        } else {
          this._disableHover({ emit: false });
        }

        // Ensure the initial side of the shelf.
        this._shiftSide({ emit: false });
      }
    );

    // Set up custom validation.
    this._addEventListener(
      "grauplComponentValidate",
      this.rootDOMElement,
      () => {
        // Boolean checks.
        const booleans = {
          hoverable: this._hover,
          locked: this._locked.value,
        };

        // Check the booleans.
        const booleanChecks = isValidType("boolean", booleans, {
          shouldThrow: false,
        });

        // Handle boolean check failure.
        if (!booleanChecks.status) {
          this._errors = [...this._errors, ...booleanChecks.errors];
          this._valid = false;
        }

        // Side check.
        // Check the side.
        const sideCheck = isValidSideType(
          { side: this._side },
          { shouldThrow: false }
        );

        if (!sideCheck.status) {
          this._errors = [...this._errors, ...sideCheck.errors];
          this._valid = false;
        }
      }
    );

    if (initialize) {
      this.initialize();
    }
  }

  /**
   * The class(es) to apply to the shelf and dependent elements when the shelf is locked.
   *
   * @type {string|string[]}
   *
   * @see _classes
   */
  get lockedClass() {
    return this._classes.locked;
  }

  set lockedClass(value) {
    isValidClassList({ lockedClass: value });

    if (this._classes.locked !== value) {
      this._classes.locked = value;
    }
  }

  /**
   * The class(es) to apply to the shelf and dependent elements when the shelf is unlocked.
   *
   * @type {string|string[]}
   *
   * @see _classes
   */
  get unlockedClass() {
    return this._classes.unlocked;
  }

  set unlockedClass(value) {
    isValidClassList({ unlockedClass: value });

    if (this._classes.unlocked !== value) {
      this._classes.unlocked = value;
    }
  }

  /**
   * The class(es) to apply to the shelf element when the shelf is hoverable.
   *
   * @type {string|string[]}
   *
   * @see _classes
   */
  get hoverClass() {
    return this._classes.hover;
  }

  set hoverClass(value) {
    isValidClassList({ hoverClass: value });

    if (this._classes.hover !== value) {
      this._classes.hover = value;
    }
  }

  /**
   * The class(es) to apply to the shelf element when the shelf is not hoverable.
   *
   * @type {string|string[]}
   *
   * @see _classes
   */
  get noHoverClass() {
    return this._classes.noHover;
  }

  set noHoverClass(value) {
    isValidClassList({ noHoverClass: value });

    if (this._classes.noHover !== value) {
      this._classes.noHover = value;
    }
  }

  /**
   * The class(es) to apply to the shelf and dependent elements when the shelf is on the left side.
   *
   * @type {string|string[]}
   *
   * @see _classes
   */
  get leftClass() {
    return this._classes.left;
  }

  set leftClass(value) {
    isValidClassList({ leftClass: value });

    if (this._classes.left !== value) {
      this._classes.left = value;
    }
  }

  /**
   * The class(es) to apply to the shelf and dependent elements when the shelf is on the right side.
   *
   * @type {string|string[]}
   *
   * @see _classes
   */
  get rightClass() {
    return this._classes.right;
  }

  set rightClass(value) {
    isValidClassList({ rightClass: value });

    if (this._classes.right !== value) {
      this._classes.right = value;
    }
  }

  /**
   * The class(es) to apply to the shelf when the shelf is open.
   *
   * @type {string|string[]}
   *
   * @see _classes
   */
  get openClass() {
    return this._classes.open;
  }

  set openClass(value) {
    isValidClassList({ openClass: value });

    if (this._classes.open !== value) {
      this._classes.open = value;
    }
  }

  /**
   * The class(es) to apply to the shelf when the shelf is closed.
   *
   * @type {string|string[]}
   *
   * @see _classes
   */
  get closeClass() {
    return this._classes.close;
  }

  set closeClass(value) {
    isValidClassList({ closeClass: value });

    if (this._classes.close !== value) {
      this._classes.close = value;
    }
  }

  /**
   * The class(es) to apply to the shelf and dependent elements when the shelf is transitioning between states.
   *
   * @type {string|string[]}
   *
   * @see _classes
   */
  get transitionClass() {
    return this._classes.transition;
  }

  set transitionClass(value) {
    isValidClassList({ transitionClass: value });

    if (this._classes.transition !== value) {
      this._classes.transition = value;
    }
  }

  /**
   * The duration time (in milliseconds) for the transition between open and closed states.
   *
   * Setting this value will also set the --am-transition-duration CSS custom property on the shelf.
   *
   * @type {number}
   *
   * @see _durations
   */
  get transitionDuration() {
    return this._durations.transition;
  }

  set transitionDuration(value) {
    isValidType("number", { transitionDuration: value });

    if (this._durations.transition !== value) {
      this._durations.transition = value;
      this._setTransitionDurations();
    }
  }

  /**
   * The duration time (in milliseconds) for the transition from closed to open states.
   *
   * If openDuration is set to -1, the transitionDuration value will be used instead.
   *
   * Setting this value will also set the --am-open-transition-duration CSS custom property on the shelf.
   *
   * @type {number}
   *
   * @see _durations
   */
  get openDuration() {
    if (this._durations.open === -1) return this.transitionDuration;

    return this._durations.open;
  }

  set openDuration(value) {
    isValidType("number", { openDuration: value });

    if (this._durations.open !== value) {
      this._durations.open = value;
      this._setTransitionDurations();
    }
  }

  /**
   * The duration time (in milliseconds) for the transition from open to closed states.
   *
   * If closeDuration is set to -1, the transitionDuration value will be used instead.
   *
   * Setting this value will also set the --am-close-transition-duration CSS custom property on the shelf.
   *
   * @type {number}
   *
   * @see _durations
   */
  get closeDuration() {
    if (this._durations.close === -1) return this.transitionDuration;

    return this._durations.close;
  }

  set closeDuration(value) {
    isValidType("number", { closeDuration: value });

    if (this._durations.close !== value) {
      this._durations.close = value;
      this._setTransitionDurations();
    }
  }

  /**
   * A flag to indicate if the shelf is hoverable.
   *
   * @readonly
   *
   * @type {boolean}
   *
   * @see _hover
   */
  get hover() {
    return this._hover;
  }

  /**
   * The delay time (in milliseconds) used for pointerenter/pointerleave events to take place.
   *
   * @type {number}
   *
   * @see _delays
   */
  get hoverDelay() {
    return this._delays.hover;
  }

  set hoverDelay(value) {
    isValidType("number", { hoverDelay: value });

    if (this._delays.hover !== value) {
      this._delays.hover = value;
    }
  }

  /**
   * The delay time (in milliseconds) used for pointerenter events to take place.
   *
   * If enterDelay is set to -1, the hoverDelay value will be used instead.
   *
   * @type {number}
   *
   * @see _delays
   */
  get enterDelay() {
    if (this._delays.enter === -1) return this.hoverDelay;

    return this._delays.enter;
  }

  set enterDelay(value) {
    isValidType("number", { enterDelay: value });

    if (this._delays.enter !== value) {
      this._delays.enter = value;
    }
  }

  /**
   * The delay time (in milliseconds) used for pointerleave events to take place.
   *
   * If leaveDelay is set to -1, the hoverDelay value will be used instead.
   *
   * @type {number}
   *
   * @see _delays
   */
  get leaveDelay() {
    if (this._delays.leave === -1) return this.hoverDelay;

    return this._delays.leave;
  }

  set leaveDelay(value) {
    isValidType("number", { leaveDelay: value });

    if (this._delays.leave !== value) {
      this._delays.leave = value;
    }
  }

  /**
   * A flag to indicate if the navigation shelf is locked.
   *
   * @readonly
   *
   * @type {boolean}
   *
   * @see _locked
   */
  get isLocked() {
    return this._locked.value;
  }

  /**
   * The committed lock preference for the navigation shelf.
   *
   * @readonly
   *
   * @type {boolean}
   *
   * @see _locked
   */
  get shouldBeLocked() {
    return this._locked.committed;
  }

  /**
   * The side of the screen the navigation shelf is on.
   *
   * @readonly
   *
   * @type {string}
   *
   * @see _side
   */
  get side() {
    return this._side;
  }

  /**
   * The opposite side of the screen the navigation shelf is on.
   *
   * @readonly
   *
   * @type {string}
   *
   * @see _otherSide
   */
  get otherSide() {
    return this._otherSide;
  }

  /**
   * A flag to check if the shelf can dynamically hover.
   *
   * @type {boolean}
   *
   * @see _softLocked
   */
  get isSoftLocked() {
    return this._softLocked;
  }

  set isSoftLocked(value) {
    isValidType("boolean", { isSoftLocked: value });

    if (this._softLocked !== value) {
      this._softLocked = value;
    }
  }

  /**
   * The open state on the shelf.
   *
   * @readonly
   *
   * @type {boolean}
   *
   * @see _open
   */
  get isOpen() {
    return this._open;
  }

  /**
   * Sets the IDs of the navigation shelf and its elements if they do not already exist.
   *
   * The generated IDs use the key and follow the format:
   *  - navigation shelf: `navigation-shelf-${key}`
   *  - navigation shelf toggle: `navigation-shelf-toggle-${key}`
   *  - navigation shelf lock toggle: `navigation-shelf-lock-toggle-${key}`
   *  - navigation shelf hover toggle: `navigation-shelf-hover-toggle-${key}`
   */
  _setIds() {
    this.dom.shelf.id = this.dom.shelf.id || `navigation-shelf-${this.key}`;
    if (this.dom.controller) {
      this.dom.controller.id =
        this.dom.controller.id || `navigation-shelf-toggle-${this.key}`;
    }
    if (this.dom.lockController) {
      this.dom.lockController.id =
        this.dom.lockController.id ||
        `navigation-shelf-lock-toggle-${this.key}`;
    }
    if (this.dom.hoverController) {
      this.dom.hoverController.id =
        this.dom.hoverController.id ||
        `navigation-shelf-hover-toggle-${this.key}`;
    }

    this._id = this.dom.shelf.id;
  }

  /**
   * Sets the aria attributes for the navigation shelf.
   */
  _setAriaAttributes() {
    if (this.dom.controller) {
      this.dom.controller.setAttribute("aria-controls", this.dom.shelf.id);

      if (this.dom.controller.getAttribute("aria-expanded") !== "true") {
        this.dom.controller.setAttribute("aria-expanded", "false");
      }
    }

    if (this.dom.lockController) {
      this.dom.lockController.setAttribute("aria-controls", this.dom.shelf.id);
      this.dom.lockController.setAttribute(
        "aria-pressed",
        this.isLocked ? "true" : "false"
      );
    }

    if (this.dom.hoverController) {
      this.dom.hoverController.setAttribute("aria-controls", this.dom.shelf.id);
      this.dom.hoverController.setAttribute(
        "aria-pressed",
        this._hoverType === "on" ? "true" : "false"
      );
    }

    if (this.dom.sideController) {
      this.dom.sideController.setAttribute("aria-controls", this.dom.shelf.id);
    }
  }

  /**
   * Sets custom props throughout the navigation shelf.
   *
   * The custom properties are:
   *   - `--graupl-transition-duration`,
   *   - `--graupl-open-transition-duration`, and
   *   - `--graupl-close-transition-duration`.
   *
   * The prefix of `graupl-` can be changed by setting the shelf's prefix value.
   *
   * @protected
   */
  _setCustomProps() {
    this.dom.shelf.style.setProperty(
      `--${this.prefix}navigation-shelf-transition-duration`,
      `${this.transitionDuration}ms`
    );

    this.dom.shelf.style.setProperty(
      `--${this.prefix}navigation-shelf-open-transition-duration`,
      `${this.openDuration}ms`
    );

    this.dom.shelf.style.setProperty(
      `--${this.prefix}navigation-shelf-close-transition-duration`,
      `${this.closeDuration}ms`
    );
  }

  /**
   * Sets all DOM elements within the shelf.
   *
   * Utilizes _setDOMElementType and _resetDOMElementType.
   *
   * @protected
   */
  _setDOMElements() {
    this._setDOMElementType("dependents", { context: document.body });
  }

  /**
   * Handles focus events throughout the navigation shelf.
   *
   * @protected
   */
  _handleFocus() {
    this.dom.shelf.addEventListener("focusin", () => {
      this.focusState = "self";
      this.open();
    });

    this.dom.shelf.addEventListener("focusout", (event) => {
      if (
        event.relatedTarget === null ||
        this.dom.shelf.contains(event.relatedTarget)
      )
        return;

      this.focusState = "none";

      if (!this.isLocked) {
        this.close();
      }
    });
  }

  /**
   * Handles click events throughout the navigation shelf.
   *
   * @protected
   */
  _handleClick() {
    // Prevent pointer down events on all controlled elements.
    for (const element of Object.values(this.dom)) {
      if (!element) continue;
      if (Array.isArray(element)) continue;

      element.addEventListener(
        "pointerdown",
        () => {
          this.currentEvent = "mouse";
          this._clearTimeout();
        },
        { passive: true }
      );
    }

    // Toggle the shelf when the controlled is clicked.
    if (this.dom.controller) {
      this.dom.controller.addEventListener("click", (event) => {
        if (event.button !== 0) return;

        this.currentEvent = "mouse";
        preventEvent(event);
        this.toggle({ preserveLock: false });

        if (this.isOpen) {
          this.focusState = "self";
          this.isSoftLocked = true;
        }
      });
    }

    // Toggle hoverability when the hover controller is clicked.
    if (this.dom.hoverController) {
      this.dom.hoverController.addEventListener("click", (event) => {
        if (event.button !== 0) return;

        this.currentEvent = "mouse";
        preventEvent(event);
        this.focusState = "self";
        this.toggleHover();

        if (this.hover) {
          this.open();
        }
      });
    }

    // Toggle shelf lock when the lock controller is clicked.
    if (this.dom.lockController) {
      this.dom.lockController.addEventListener("click", (event) => {
        if (event.button !== 0) return;

        this.currentEvent = "mouse";
        preventEvent(event);
        this.focusState = "self";
        this.toggleLock();
      });
    }

    // Toggle shifting sides when the side controller is clicked.
    if (this.dom.sideController) {
      this.dom.sideController.addEventListener("click", (event) => {
        if (event.button !== 0) return;

        this.currentEvent = "mouse";
        preventEvent(event);
        this.focusState = "self";
        this.toggleSide();
      });
    }

    // Catch all to open if shelf if there is a click inside of it.
    this.dom.shelf.addEventListener("click", (event) => {
      if (event.button !== 0) return;

      this.currentEvent = "mouse";
      this.focusState = "self";
      this.isSoftLocked = true;
      this.open();
    });

    // Close the shelf if a click happens outside of it.
    document.addEventListener("click", (event) => {
      if (this.focusState === "none") return;
      if (this.isLocked) return;
      if (
        this.dom.shelf === event.target ||
        this.dom.shelf.contains(event.target)
      )
        return;

      this.currentEvent = "mouse";
      this.close();
    });
  }

  /**
   * Handles hover events throughout the navigation shelf.
   *
   * @protected
   */
  _handleHover() {
    this.dom.shelf.addEventListener("pointerenter", (event) => {
      if (event.pointerType === "pen" || event.pointerType === "touch") return;
      if (this.isLocked || this.isSoftLocked) return;
      if (!this.hover) return;

      this.currentEvent = "mouse";

      if (this.enterDelay > 0) {
        this._clearTimeout();
        this._setTimeout(() => {
          if (!this.isOpen) {
            this.open();
          }
        }, this.enterDelay);
      } else {
        this.open();
      }
    });

    this.dom.shelf.addEventListener("pointerleave", (event) => {
      if (event.pointerType === "pen" || event.pointerType === "touch") return;
      if (this.isLocked || this.isSoftLocked) return;
      if (!this.hover) return;

      this.currentEvent = "mouse";

      if (this.leaveDelay > 0) {
        this._clearTimeout();
        this._setTimeout(() => {
          if (this.isOpen) {
            this.close();
          }
        }, this.leaveDelay);
      } else {
        this.close();
      }
    });
  }

  /**
   * Handles keydown events throughout the navigation shelf.
   *
   * @protected
   */
  _handleKeydown() {
    // Prevent keydown events on the shelf if they are `Escape`.
    this.dom.shelf.addEventListener("keydown", (event) => {
      const key = keyPress(event);

      if (key === "Escape") {
        preventEvent(event);
      }
    });

    // Prevent keydown events on all controller elements if they are `Space` or `Enter`.
    for (const element of Object.values(this.dom)) {
      if (!element) continue;
      if (Array.isArray(element)) continue;
      if (element === this.dom.shelf) continue;

      element.addEventListener("keydown", (event) => {
        this.currentEvent = "keyboard";

        const key = keyPress(event);

        if (key === "Space" || key === "Enter") {
          preventEvent(event);
        }
      });
    }
  }

  /**
   * Handles keyup events throughout the navigation shelf.
   *
   * @protected
   */
  _handleKeyup() {
    // Close the shelf on `Escape`.
    this.dom.shelf.addEventListener("keyup", (event) => {
      this.currentEvent = "keyboard";

      const key = keyPress(event);

      if (key === "Escape") {
        this.close();
      }
    });

    // Toggle the shelf on `Space` or `Enter` on the controller.
    if (this.dom.controller) {
      this.dom.controller.addEventListener("keyup", (event) => {
        this.currentEvent = "keyboard";

        const key = keyPress(event);

        if (key === "Space" || key === "Enter") {
          preventEvent(event);
          this.toggle();

          if (this.isOpen) {
            const element = selectFirstFocusableElement(this.dom.shelf);
            element.focus();
          }
        }
      });
    }

    // Toggle hover on `Space` or `Enter` on the hover controller.
    if (this.dom.hoverController) {
      this.dom.hoverController.addEventListener("keyup", (event) => {
        this.currentEvent = "keyboard";

        const key = keyPress(event);

        if (key === "Space" || key === "Enter") {
          preventEvent(event);
          this.toggleHover();
        }
      });
    }

    // Toggle lock on `Space` or `Enter` on the lock controller.
    if (this.dom.lockController) {
      this.dom.lockController.addEventListener("keyup", (event) => {
        this.currentEvent = "keyboard";

        const key = keyPress(event);

        if (key === "Space" || key === "Enter") {
          preventEvent(event);
          this.toggleLock();
        }
      });
    }

    // Shift sides on `Space` or `Enter` on the side controller.
    if (this.dom.sideController) {
      this.dom.sideController.addEventListener("keyup", (event) => {
        this.currentEvent = "keyboard";

        const key = keyPress(event);

        if (key === "Space" || key === "Enter") {
          preventEvent(event);
          this.toggleSide();
        }
      });
    }
  }

  /**
   * Reveals the shelf.
   *
   * @protected
   *
   * @fires grauplNavigationShelfExpand
   *
   * @param {Object<boolean>} [options = {}]              - Options for revealing the shelf.
   * @param {boolean}         [options.emit = true]       - Emit the expand event once revealed.
   * @param {boolean}         [options.transition = true] - Respect the transition class.
   */
  _reveal({ emit = true, transition = true } = {}) {
    if (this.dom.controller) {
      this.dom.controller.setAttribute("aria-expanded", "true");
    }

    // If the shelf hasn't been initialized, we need to add the initialize class
    // before opening the shelf for the first time.
    //
    // If we're dealing with transition classes, then we need to utilize
    // requestAnimationFrame to add the transition class, remove the close class,
    // add the open class, and finally remove the transition class.
    if (!this.isInitialized) {
      // @todo this isn't needed anymore. Components handle adding/removing initialize classes.
      addClass(this.initializeClass, this.dom.shelf);

      requestAnimationFrame(() => {
        addClass(this.openClass, this.dom.shelf);

        removeClass(this.closeClass, this.dom.shelf);

        requestAnimationFrame(() => {
          removeClass(this.initializeClass, this.dom.shelf);
        });
      });
    } else if (transition && this.transitionClass !== "") {
      addClass(this.transitionClass, this.dom.shelf);

      requestAnimationFrame(() => {
        removeClass(this.closeClass, this.dom.shelf);

        requestAnimationFrame(() => {
          addClass(this.openClass, this.dom.shelf);

          requestAnimationFrame(() => {
            setTimeout(() => {
              removeClass(this.transitionClass, this.dom.shelf);
            }, this.openDuration);
          });
        });
      });
    } else {
      // Add the open class
      addClass(this.openClass, this.dom.shelf);

      // Remove the close class.
      removeClass(this.closeClass, this.dom.shelf);
    }

    if (emit) {
      this._dispatchEvent("expand", this.dom.shelf);
    }
  }

  /**
   * Conceals the shelf.
   *
   * @protected
   *
   * @fires grauplNavigationShelfCollapse
   *
   * @param {Object<boolean>} [options = {}]              - Options for conceal the shelf.
   * @param {boolean}         [options.emit = true]       - Emit the collapse event once concealed.
   * @param {boolean}         [options.transition = true] - Respect the transition class.
   */
  _conceal({ emit = true, transition = true } = {}) {
    if (this.dom.controller) {
      this.dom.controller.setAttribute("aria-expanded", "false");
    }
    this.isSoftLocked = false;

    // If the shelf hasn't been initialized, we need to add the initialize class
    // before closing the shelf for the first time.
    //
    // If we're dealing with transition classes, then we need to utilize
    // requestAnimationFrame to add the transition class, remove the open class,
    // add the close class, and finally remove the transition class.
    if (!this.isInitialized) {
      // @todo this isn't needed anymore. Components handle adding/removing initialize classes.
      addClass(this.initializeClass, this.dom.shelf);

      requestAnimationFrame(() => {
        addClass(this.closeClass, this.dom.shelf);

        removeClass(this.openClass, this.dom.shelf);

        requestAnimationFrame(() => {
          removeClass(this.initializeClass, this.dom.shelf);
        });
      });
    } else if (transition && this.transitionClass !== "") {
      addClass(this.transitionClass, this.dom.shelf);

      requestAnimationFrame(() => {
        removeClass(this.openClass, this.dom.shelf);

        requestAnimationFrame(() => {
          addClass(this.closeClass, this.dom.shelf);

          requestAnimationFrame(() => {
            setTimeout(() => {
              removeClass(this.transitionClass, this.dom.shelf);
            }, this.closeDuration);
          });
        });
      });
    } else {
      // Add the close class
      addClass(this.closeClass, this.dom.shelf);

      // Remove the open class.
      removeClass(this.openClass, this.dom.shelf);
    }

    if (emit) {
      this._dispatchEvent("collapse", this.dom.shelf);
    }
  }

  /**
   * Applies the locked state styling and dispatches the lock event.
   *
   * @protected
   *
   * @param {Object<boolean>} [options = {}]        - Options for the lock side effects.
   * @param {boolean}         [options.emit = true] - Whether to emit the lock event.
   */
  _lock({ emit = true } = {}) {
    if (this.dom.lockController) {
      this.dom.lockController.setAttribute("aria-pressed", "true");
    }

    // Add the locked class
    addClass(this.lockedClass, this.dom.shelf);

    // Add the locked class to dependent elements.
    this.dom.dependents.forEach((dependent) => {
      addClass(this.lockedClass, dependent);
    });

    // Remove the unlocked class.
    removeClass(this.unlockedClass, this.dom.shelf);

    // Remove the unlocked class from dependent elements.
    this.dom.dependents.forEach((dependent) => {
      removeClass(this.unlockedClass, dependent);
    });

    if (emit) {
      this._dispatchEvent("lock", this.dom.shelf);
    }
  }

  /**
   * Applies the unlocked state styling and dispatches the unlock event.
   *
   * @protected
   *
   * @param {Object<boolean>} [options = {}]        - Options for the unlock side effects.
   * @param {boolean}         [options.emit = true] - Whether to emit the unlock event.
   */
  _unlock({ emit = true } = {}) {
    if (this.dom.lockController) {
      this.dom.lockController.setAttribute("aria-pressed", "false");
    }

    // Add the unlocked class
    addClass(this.unlockedClass, this.dom.shelf);

    // Add the unlocked class to dependent elements.
    this.dom.dependents.forEach((dependent) => {
      addClass(this.unlockedClass, dependent);
    });

    // Remove the locked class.
    removeClass(this.lockedClass, this.dom.shelf);

    // Remove the locked class from dependent elements.
    this.dom.dependents.forEach((dependent) => {
      removeClass(this.lockedClass, dependent);
    });

    if (emit) {
      this._dispatchEvent("unlock", this.dom.shelf);
    }
  }

  /**
   * Updates all dependent elements to reflect the shelf side.
   *
   * @protected
   *
   * @param {Object<boolean>} [options = {}]      - Options for shifting side.
   * @param {boolean}         [options.emit=true] - Whether to emit the shift event.
   */
  _shiftSide({ emit = true } = {}) {
    const toClass = this._classes[this.side];
    const fromClass = this._classes[this.otherSide];

    // Add the to class
    addClass(toClass, this.dom.shelf);

    // Add the to class to dependent elements.
    this.dom.dependents.forEach((dependent) => {
      addClass(toClass, dependent);
    });

    // Remove the from class.
    removeClass(fromClass, this.dom.shelf);

    // Remove the from class from dependent elements.
    this.dom.dependents.forEach((dependent) => {
      removeClass(fromClass, dependent);
    });

    if (emit) {
      this._dispatchEvent("shiftSide", this.dom.shelf);
    }
  }

  /**
   * Enables hover mode on the shelf.
   *
   * @protected
   *
   * @param {Object<boolean>} [options = {}]        - Options for enabling hoverability.
   * @param {boolean}         [options.emit = true] - Whether to emit the enable hover event.
   */
  _enableHover({ emit = true } = {}) {
    if (this.dom.hoverController) {
      this.dom.hoverController.setAttribute("aria-pressed", "true");
    }

    addClass(this.hoverClass, this.dom.shelf);

    removeClass(this.noHoverClass, this.dom.shelf);

    if (emit) {
      this._dispatchEvent("enableHover", this.dom.shelf);
    }
  }

  /**
   * Disables hover mode on the shelf.
   *
   * @protected
   *
   * @param {Object<boolean>} [options = {}]        - Options for disabling hoverability.
   * @param {boolean}         [options.emit = true] - Whether to emit the disable hover event.
   */
  _disableHover({ emit = true } = {}) {
    if (this.dom.hoverController) {
      this.dom.hoverController.setAttribute("aria-pressed", "false");
    }

    addClass(this.noHoverClass, this.dom.shelf);

    removeClass(this.hoverClass, this.dom.shelf);

    if (emit) {
      this._dispatchEvent("disableHover", this.dom.shelf);
    }
  }

  /**
   * Opens the shelf.
   *
   * @param {Object<boolean>} [options = {}]              - Options for opening the shelf.
   * @param {boolean}         [options.force = false]     - Whether to force the open action.
   * @param {boolean}         [options.emit = true]       - Whether to emit the expand event once opened.
   * @param {boolean}         [options.transition = true] - Respect the transition class.
   */
  open({ force = false, emit = true, transition = true } = {}) {
    // Only open if the shelf is closed.
    if (this.isOpen && !force) return;

    this._reveal({ emit, transition });

    // Set the open flag.
    this._open = true;
  }

  /**
   * Closes the shelf and optionally preserves the committed lock state.
   *
   * @param {Object<boolean>} [options = {}]                - Options for closing the shelf.
   * @param {boolean}         [options.force = false]       - Whether to force the close action.
   * @param {boolean}         [options.emit = true]         - Whether to emit the collapse event once closed.
   * @param {boolean}         [options.transition = true]   - Respect the transition class.
   * @param {boolean}         [options.preserveLock = true] - Whether to keep the current lock preference unchanged.
   */
  close({
    force = false,
    emit = true,
    transition = true,
    preserveLock = true,
  } = {}) {
    // Only close if the shelf is open.
    if (!this.isOpen && !force) return;

    this.unlock({ updateLock: !preserveLock });
    this._conceal({ emit, transition });

    // Set the open flag.
    this._open = false;
  }

  /**
   * Toggles the shelf open or closed.
   *
   * @param {Object<boolean>} [options = {}]                - Options for toggling the shelf.
   * @param {boolean}         [options.force = false]       - Whether to force the transition.
   * @param {boolean}         [options.emit = true]         - Whether to emit the expand/collapse events.
   * @param {boolean}         [options.transition = true]   - Respect the transition class.
   * @param {boolean}         [options.preserveLock = true] - Whether to keep the current lock preference unchanged when closing.
   */
  toggle({
    force = false,
    emit = true,
    transition = true,
    preserveLock = true,
  } = {}) {
    if (this.isOpen) {
      this.close({ force, emit, transition, preserveLock });
    } else {
      this.open({ force, emit, transition });
    }
  }

  /**
   * Locks the shelf and ensures it remains open.
   *
   * @param {Object<boolean>} [options = {}]              - Options for locking the shelf.
   * @param {boolean}         [options.emit = true]       - Whether to force the lock even if already locked.
   * @param {boolean}         [options.force = false]     - Whether to emit the expand event.
   * @param {boolean}         [options.transition = true] - Respect the transition class.
   */
  lock({ force = false, emit = true, transition = true } = {}) {
    // Only lock if the shelf is unlocked.
    if (this.isLocked && !force) return;

    this._locked.value = true;
    this._lock();

    // Commit the locked preference.
    this._locked.commit();

    // Open the shelf.
    this.open({ force: true, emit, transition });
  }

  /**
   * Unlocks the shelf.
   *
   * @param {Object<boolean>} [options = {}]              - Options for unlocking the shelf.
   * @param {boolean}         [options.emit = true]       - Whether to emit the unlock event.
   * @param {boolean}         [options.updateLock = true] - Whether to commit the unlocked state as the new preference.
   */
  unlock({ emit = true, updateLock = true } = {}) {
    // Only unlock if the shelf is locked.
    if (!this.isLocked) {
      this._locked.value = false;

      if (updateLock) {
        this._locked.commit();
      }

      return;
    }

    this._locked.value = false;
    this._unlock({ emit });

    if (updateLock) {
      this._locked.commit();
    }
  }

  /**
   * Toggles the locked state of the shelf.
   *
   * @param {Object<boolean>} [options = {}]              - Options for toggling the lock state.
   * @param {boolean}         [options.force = false]     - Whether to force the toggle action.
   * @param {boolean}         [options.emit = true]       - Whether to emit the lock/unlock event.
   * @param {boolean}         [options.transition = true] - Respect the transition class.
   * @param {boolean}         [options.updateLock = true] - Whether to commit the new lock state as the preference.
   */
  toggleLock({
    force = false,
    emit = true,
    transition = true,
    updateLock = true,
  } = {}) {
    if (this.isLocked) {
      this.unlock({ emit, updateLock });
    } else {
      this.lock({ force, emit, transition });
    }
  }

  /**
   * Shift the shelf to the left side.
   *
   * @param {Object<boolean>} [options = {}]        - Options for shifting side.
   * @param {boolean}         [options.emit = true] - Whether to emit the shift event.
   */
  toLeft({ emit = true } = {}) {
    if (this.side === "left") return;

    this._side = "left";
    this._otherSide = "right";
    this._shiftSide({ emit });
  }

  /**
   * Shift the shelf to the right side.
   *
   * @param {Object<boolean>} [options = {}]        - Options for shifting side.
   * @param {boolean}         [options.emit = true] - Whether to emit the shift event.
   */
  toRight({ emit = true } = {}) {
    if (this.side === "right") return;

    this._side = "right";
    this._otherSide = "left";
    this._shiftSide({ emit });
  }

  /**
   * Toggles the shelf side between left and right.
   *
   * @param {Object<boolean>} [options = {}]        - Options for shifting side.
   * @param {boolean}         [options.emit = true] - Whether to emit the shift event.
   */
  toggleSide({ emit = true } = {}) {
    if (this.side === "left") {
      this.toRight({ emit });
    } else {
      this.toLeft({ emit });
    }
  }

  /**
   * Enables hover mode on the shelf.
   *
   * @param {Object<boolean>} [options = {}]        - Options for enabling hoverability.
   * @param {boolean}         [options.emit = true] - Whether to emit the enable hover event.
   */
  enableHover({ emit = true } = {}) {
    if (this.hover) return;

    this._enableHover({ emit });

    this._hover = true;
  }

  /**
   * Disables hover mode on the shelf.
   *
   * @param {Object<boolean>} [options = {}]        - Options for disabling hoverability.
   * @param {boolean}         [options.emit = true] - Whether to emit the disable hover event.
   */
  disableHover({ emit = true } = {}) {
    if (!this.hover) return;

    this._disableHover({ emit });

    this._hover = false;
  }

  /**
   * Toggles hover mode on the shelf.
   *
   * @param {Object<boolean>} [options = {}]        - Options for toggling hoverability.
   * @param {boolean}         [options.emit = true] - Whether to emit the enable/disable hover event.
   */
  toggleHover({ emit = true } = {}) {
    if (this.hover) {
      this.disableHover({ emit });
    } else {
      this.enableHover({ emit });
    }
  }
}

export default NavigationShelf;
