/**
 * @file
 * A generic component class.
 */

class Component {
  /**
   * The DOM elements within the component.
   *
   * @protected
   *
   * @type {Object<HTMLElement, HTMLElement[]>}
   */
  _dom = {};

  /**
   * The DOM elements within the component that cannot be reset or generated by the component itself.
   *
   * @protected
   *
   * @type {string[]}
   */
  _protectedDOMElements = [];

  /**
   * The query selectors used by the component.
   *
   * @protected
   *
   * @type {Object<string>}
   */
  _selectors = {};

  /**
   * The instantiated elements within the component.
   *
   * @protected
   *
   * @type {object}
   */
  _elements = {};

  /**
   * The CSS classes to apply when the component is in various states.
   *
   * @protected
   *
   * @type {Object<string, string[]>}
   */
  _classes = {};

  /**
   * The duration times (in milliseconds) for variouse aspects throughout the component.
   *
   * @protected
   *
   * @type {Object<number>}
   */
  _durations = {};

  /**
   * The current state of the component's focus.
   *
   * @protected
   *
   * @type {string}
   */
  _focusState = "none";

  /**
   * The last type of event triggered within the component.
   *
   * @protected
   *
   * @type {string}
   */
  _currentEvent = "none";

  /**
   * The prefix used for CSS custom properties and attributes.
   *
   * @protected
   *
   * @type {string}
   */
  _prefix = "graupl-";

  /**
   * The key used to generate IDs throughout the component.
   *
   * @protected
   *
   * @type {string}
   */
  _key = "";

  /**
   * The errors found throughout the component.
   *
   * @protected
   *
   * @type {string[]}
   */
  _errors = [];

  /**
   * Constructs a new component.
   *
   * @param {object}             options                                  - The options for generating the component.
   * @param {?string}            [options.prefix = graupl-]               - The prefix used for CSS custom properties and attributes.
   * @param {?string}            [options.key = null]                     - The key used to generate IDs throughout the component.
   * @param {?(string|string[])} [options.initializeClass = initializing] - The class(es) to apply when the component is initializing.
   * @param {boolean}            [options.initialize = false]             - A flag to initialize the component immediately upon creation.
   */
  constructor({
    prefix = "graupl-",
    key = null,
    initializeClass = "initializing",
    initialize = false,
  } = {}) {
    // Set the classes.
    this._classes.initialize = initializeClass || "";

    // Set the prefix and key.
    this._prefix = prefix || "";
    this._key = key || "";

    if (initialize) {
      this._initialize();
    }
  }

  _initialize() {
    try {
    } catch (error) {}
  }

  initialize() {}
}

export default Component;
