/**
 * @file
 * The Carousel class.
 */

import { addClass, removeClass } from "../domHelpers.js";
import { preventEvent, keyPress } from "../eventHandlers.js";
import { isTag, isValidClassList, isValidType } from "../validate.js";
import Component from "../Component.js";
import CarouselItem from "./CarouselItem.js";

/**
 * The Carousel component.
 *
 * @extends Component
 *
 * Protected fields are documented below.
 *
 * @property {Object<HTMLElement, HTMLElement[]>} _dom                                - The DOM elements within the carousel.
 * @property {HTMLElement}                        _dom.carousel                       - The carousel element.
 * @property {HTMLElement[]}                      _dom.carouselItems                  - The carousel items.
 * @property {HTMLElement}                        _dom.carouselItemContainer          - The carousel item container.
 * @property {HTMLElement[]}                      _dom.carouselControls               - The carousel controls.
 * @property {HTMLElement}                        _dom.carouselControlContainer       - The carousel control container.
 * @property {HTMLElement[]}                      _dom.carouselTabs                   - The carousel tabs.
 * @property {HTMLElement}                        _dom.carouselTabContainer           - The carousel tab container.
 * @property {HTMLElement}                        _dom.autoplay                       - The autoplay button.
 * @property {HTMLElement}                        _dom.next                           - The next button.
 * @property {HTMLElement}                        _dom.previous                       - The previous button.
 * @property {string}                             _rootDOMElement                     - The root DOM element of the carousel.
 * @property {string[]}                           _protectedDOMElements               - The DOM elements within the carousel that cannot be reset or generated by the carousel itself.
 * @property {Object<string>}                     _selectors                          - The query selectors used by the carousel.
 * @property {string}                             _selectors.carouselItems            - The query selector string for carousel items.
 * @property {string}                             _selectors.carouselItemContainer    - The query selector string for the carousel item container.
 * @property {string}                             _selectors.carouselControls         - The query selector string for carousel controls.
 * @property {string}                             _selectors.carouselControlContainer - The query selector string for the carousel control container.
 * @property {string}                             _selectors.carouselTabs             - The query selector string for the carousel tabs.
 * @property {string}                             _selectors.carouselTabContainer     - The query selector string for the carousel tab container.
 * @property {string}                             _selectors.autoplay                 - The query selector string for the autoplay button.
 * @property {string}                             _selectors.next                     - The query selector string for the next button.
 * @property {string}                             _selectors.previous                 - The query selector string for the previous button.
 * @property {Object<CarouselItem[]>}             _elements                           - The instantiated carousel items within the carousel.
 * @property {CarouselItem[]}                     _elements.carouselItems             - The instantiated carousel items within the carousel.
 * @property {Object<string, string[]>}           _classes                            - The CSS classes to apply when the carousel is in various states.
 * @property {string|string[]}                    _classes.active                     - The class(es) to apply when a carousel item is active.
 * @property {string|string[]}                    _classes.previous                   - The class(es) to apply to a carousel item that is the previously active item.
 * @property {string|string[]}                    _classes.next                       - The class(es) to apply to a carousel item that is the next active item.
 * @property {string|string[]}                    _classes.play                       - The class(es) to apply to the autoplay button when the carousel is paused.
 * @property {string|string[]}                    _classes.pause                      - The class(es) to apply to the autoplay button when the carousel is playing.
 * @property {string|string[]}                    _classes.initialize                 - The class(es) to apply when the carousel is initializing.
 * @property {Object<number>}                     _durations                          - The duration times (in milliseconds) for various aspects throughout the carousel.
 * @property {number}                             _durations.transition               - The duration time (in milliseconds) for the transition between carousel items.
 * @property {Object<number>}                     _delays                             - The delay times (in milliseconds) for various aspects throughout the carousel.
 * @property {number}                             _delays.transition                  - The delay time (in milliseconds) for the transition between carousel items.
 * @property {number}                             _currentItem                        - The index of the currently active carousel item.
 * @property {boolean}                            _autoplay                           - A flag to indicate if the carousel is currently playing.
 * @property {string}                             _playText                           - The label for the autoplay button when the carousel is paused.
 * @property {string}                             _pauseText                          - The label for the autoplay button when the carousel is playing.
 * @property {string}                             _currentAction                      - The current action being performed by the carousel.
 * @property {string}                             _storageKey                         - The key used for storage.
 * @property {boolean}                            _shouldStore                        - A flag to check if the component should be stored in the StorageManager.
 * @property {Object<CustomEvent>}                _events                             - Custom events that can be triggered throughout the carousel.
 * @property {Object<object>}                     _elements                           - The instantiated elements within the carousel.
 * @property {string}                             _focusState                         - The current state of the carousel's focus.
 * @property {string}                             _currentEvent                       - The last type of event triggered within the carousel.
 * @property {string}                             _breakpoint                         - The breakpoint that the carousel will call media query list events.
 * @property {string}                             _mediaQueryString                   - The media query to use to trigger media query list events.
 * @property {MediaQueryList|null}                _mediaQueryList                     - The MediaQueryList for the carousel.
 * @property {Function}                           _mediaQueryListEventCallback        - The callback for media query list events.
 * @property {Object<Function>}                   _intervals                          - Intervals throughout the carousel.
 * @property {Object<Function>}                   _timeouts                           - Timeouts throughout the carousel.
 * @property {object[]}                           _listeners                          - Event listeners throughout the carousel.
 * @property {string}                             _prefix                             - The prefix used for CSS custom properties and attributes.
 * @property {string}                             _key                                - The key used to generate IDs throughout the carousel.
 * @property {string}                             _name                               - The component name of the carousel.
 * @property {string}                             _id                                 - The main ID of the carousel.
 * @property {boolean}                            _valid                              - The validity state of the carousel.
 * @property {boolean}                            _initialized                        - The initialized state of the carousel.
 * @property {string[]}                           _errors                             - The errors found throughout the carousel.
 */
class Carousel extends Component {
  _rootDOMElement = "carousel";
  _currentItem = 0;
  _autoplay = true;
  _playText = "Play";
  _pauseText = "Pause";
  _currentAction = "next";
  _storageKey = "carousels";
  _name = "Carousel";
  _itemsPerPage = 1;
  _loop = true;

  /**
   * Constructs a new `Carousel`.
   *
   * @param {object}             options                                                                  - The options for the generated carousel.
   * @param {HTMLElement}        options.carouselElement                                                  - The carousel element in the DOM.
   * @param {string}             [options.carouselItemsSelector = .carousel-item]                         - The query selector string for carousel items.
   * @param {string}             [options.carouselItemContainerSelector = .carousel-item-container]       - The query selector string for the carousel item container.
   * @param {string}             [options.carouselControlsSelector = .carousel-control]                   - The query selector string for carousel controls.
   * @param {string}             [options.carouselControlContainerSelector = .carousel-control-container] - The query selector string for carousel control container.
   * @param {string}             [options.carouselTabsSelector = .carousel-tab]                           - The query selector string for carousel tabs.
   * @param {string}             [options.carouselTabContainerSelector = .carousel-tab-container]         - The query selector string for the carousel tab container.
   * @param {string}             [options.autoplaySelector = .autoplay]                                   - The query selector string for the autoplay button.
   * @param {string}             [options.nextSelector = .next]                                           - The query selector string for the next button.
   * @param {string}             [options.previousSelector = .previous]                                   - The query selector string for the previous button.
   * @param {?(string|string[])} [options.activeClass = active]                                           - The class(es) to apply when a carousel item is active.
   * @param {?(string|string[])} [options.previousClass = previous]                                       - The class(es) to apply to a carousel item that is the previously active item.
   * @param {?(string|string[])} [options.nextClass = next]                                               - The class(es) to apply to a carousel item that is the next active item.
   * @param {?(string|string[])} [options.playClass = play]                                               - The class(es) to apply to the autoplay button when the carousel is paused.
   * @param {?(string|string[])} [options.pauseClass = pause]                                             - The class(es) to apply to the autoplay button when the carousel is playing.
   * @param {boolean}            [options.autoplay = true]                                                - A flag to indicate if the carousel should autoplay.
   * @param {number}             [options.transitionDelay = 10000]                                        - A flag to initialize the carousel immediately upon creation.
   * @param {number}             [options.transitionDuration = 500]                                       - The duration time (in milliseconds) for the transition between carousel items.
   * @param {?string}            [options.playText = Play]                                                - The text to use for the play button.
   * @param {?string}            [options.pauseText = Pause]                                              - The text to use for the pause button.
   * @param {number}             [options.itemsPerPage = 1]                                               - The number of items to show per page.
   * @param {boolean}            [options.loop = true]                                                    - A flag to indicate if the carousel should loop infinitely.
   * @param {?string}            [options.prefix = graupl-]                                               - The prefix used for CSS custom properties and attributes.
   * @param {?string}            [options.key = null]                                                     - The key used to generate IDs throughout the carousel.
   * @param {?(string|string[])} [options.initializeClass = initializing]                                 - The class(es) to apply when the carousel is initializing.
   * @param {boolean}            [options.initialize = false]                                             - A flag to initialize the carousel immediately upon creation.
   */
  constructor({
    carouselElement,
    carouselItemsSelector = ".carousel-item",
    carouselItemContainerSelector = ".carousel-item-container",
    carouselControlsSelector = ".carousel-control",
    carouselControlContainerSelector = ".carousel-control-container",
    carouselTabsSelector = ".carousel-tab",
    carouselTabContainerSelector = ".carousel-tab-container",
    autoplaySelector = ".autoplay",
    nextSelector = ".next",
    previousSelector = ".previous",
    activeClass = "active",
    previousClass = "previous",
    nextClass = "next",
    playClass = "play",
    pauseClass = "pause",
    autoplay = true,
    transitionDelay = 10000,
    transitionDuration = 500,
    playText = "Play",
    pauseText = "Pause",
    itemsPerPage = 1,
    loop = true,
    prefix = "graupl-",
    key = null,
    initializeClass = "initializing",
    initialize = false,
  }) {
    super({
      prefix,
      key,
      initializeClass,
    });

    // Set DOM elements.
    this._dom.carousel = carouselElement;
    this._dom.carouselItems = [];
    this._dom.carouselItemContainer = null;
    this._dom.carouselControls = [];
    this._dom.carouselControlContainer = null;
    this._dom.carouselTabs = [];
    this._dom.carouselTabContainer = null;
    this._dom.autoplay = null;
    this._dom.next = null;
    this._dom.previous = null;

    // Set query selectors.
    this._selectors.carouselItems = carouselItemsSelector;
    this._selectors.carouselItemContainer = carouselItemContainerSelector;
    this._selectors.carouselControls = carouselControlsSelector;
    this._selectors.carouselControlContainer = carouselControlContainerSelector;
    this._selectors.carouselTabs = carouselTabsSelector;
    this._selectors.carouselTabContainer = carouselTabContainerSelector;
    this._selectors.autoplay = autoplaySelector;
    this._selectors.next = nextSelector;
    this._selectors.previous = previousSelector;

    // Set the elements.
    this._elements.carouselItems = [];

    // Set class names.
    this._classes.active = activeClass || "";
    this._classes.previous = previousClass || "";
    this._classes.next = nextClass || "";
    this._classes.play = playClass || "";
    this._classes.pause = pauseClass || "";

    // Set flags.
    this._autoplay = autoplay;
    this._itemsPerPage = itemsPerPage;
    this._loop = loop;

    // Set transition options.
    this._delays.transition = transitionDelay;
    this._durations.transition = transitionDuration;

    // Set labels.
    this._playText = playText || "";
    this._pauseText = pauseText || "";

    // Set up custom initialization.
    this._addEventListener(
      "grauplComponentInitialize",
      this.rootDOMElement,
      () => {
        // Handle events.
        this._handleAutoplay();

        // Make sure all carousel items are inert so they are not focusable until activated.
        this.dom.carouselItems.forEach((item) => {
          item.setAttribute("inert", "true");
        });

        if (this.loop) {
          this._handleLoop();
        }

        // this._handleIntersection();

        // Activate the first item.
        this.activateFirstItem();
      }
    );

    // Set up custom validation.
    this._addEventListener(
      "grauplComponentValidate",
      this.rootDOMElement,
      () => {
        // Boolean checks.
        const booleans = {
          autoplay: this._autoplay,
          loop: this._loop,
        };

        // Check the booleans.
        const booleanChecks = isValidType("boolean", booleans, {
          shouldThrow: false,
        });

        // Handle boolean check failure.
        if (!booleanChecks.status) {
          this._errors = [...this._errors, ...booleanChecks.errors];
          this._valid = false;
        }

        // String checks.
        const strings = {
          playText: this._playText,
          pauseText: this._pauseText,
        };

        // Check the strings.
        const stringChecks = isValidType("string", strings, {
          shouldThrow: false,
        });

        // Handle string check failures.
        if (!stringChecks.status) {
          this._errors = [...this._errors, ...stringChecks.errors];
          this._valid = false;
        }

        // Number checks.
        const numbers = {
          itemsPerPage: this._itemsPerPage,
        };

        // Check the numbers.
        const numberChecks = isValidType("number", numbers, {
          shouldThrow: false,
        });

        // Handle number check failures.
        if (!numberChecks.status) {
          this._errors = [...this._errors, ...numberChecks.errors];
          this._valid = false;
        }
      }
    );

    if (initialize) {
      this.initialize();
    }
  }

  /**
   * The class(es) to apply when a carousel item is active.
   *
   * @type {string|string[]}
   *
   * @see _classes.active
   */
  get activeClass() {
    return this._classes.active;
  }

  set activeClass(value) {
    isValidClassList({ activeClass: value });

    if (this._classes.active !== value) {
      this._classes.active = value;
    }
  }

  /**
   * The class(es) to apply to a carousel item that is the next active item.
   *
   * @type {string|string[]}
   *
   * @see _classes.previous
   */
  get previousClass() {
    return this._classes.previous;
  }

  set previousClass(value) {
    isValidClassList({ previousClass: value });

    if (this._classes.previous !== value) {
      this._classes.previous = value;
    }
  }

  /**
   * The class(es) to apply to a carousel item that is the next active item.
   *
   * @type {string|string[]}
   *
   * @see _classes.next
   */
  get nextClass() {
    return this._classes.next;
  }

  set nextClass(value) {
    isValidClassList({ nextClass: value });

    if (this._classes.next !== value) {
      this._classes.next = value;
    }
  }

  /**
   * The class(es) to apply to the autoplay button when the carousel is paused.
   *
   * @type {string|string[]}
   *
   * @see _classes.play
   */
  get playClass() {
    return this._classes.play;
  }

  set playClass(value) {
    isValidClassList({ playClass: value });

    if (this._classes.play !== value) {
      this._classes.play = value;
    }
  }

  /**
   * The class(es) to apply to the autoplay button when the carousel is playing.
   *
   * @type {string|string[]}
   *
   * @see _classes.pause
   */
  get pauseClass() {
    return this._classes.pause;
  }

  set pauseClass(value) {
    isValidClassList({ pauseClass: value });

    if (this._classes.pause !== value) {
      this._classes.pause = value;
    }
  }

  /**
   * The index of the currently active carousel item.
   *
   * @type {number}
   *
   * @see _currentItem
   */
  get currentItem() {
    return this._currentItem;
  }

  set currentItem(value) {
    isValidType("number", { currentItem: value });

    if (value === this.currentItem) {
      return;
    }

    if (value < 0) {
      this._currentItem = 0;
    } else if (value >= this.dom.carouselItems.length) {
      this._currentItem = this.dom.carouselItems.length - 1;
    } else {
      this._currentItem = value;
    }

    // Keep the aria selected in sync with the current item.
    const tabs = this._dom.carousel.querySelectorAll(
      this.selectors.carouselTab
    );
    if (tabs) {
      this.dom.carouselItems.forEach((item, index) => {
        item.setAttribute("aria-selected", index === this._currentItem);
      });
    }
  }

  /**
   * The currently active carousel item.
   *
   * @readonly
   *
   * @type {CarouselItem}
   */
  get currentCarouselItem() {
    return this.elements.carouselItems[this.currentItem];
  }

  /**
   * A flag to indicate if the carousel is currently playing.
   *
   * @type {boolean}
   *
   * @see _autoplay
   */
  get autoplay() {
    return this._autoplay;
  }

  set autoplay(value) {
    isValidType("boolean", { autoplay: value });

    if (this._autoplay !== value) {
      this._autoplay = value;
    }
  }

  /**
   * The number of items to show per page.
   *
   * @readonly
   *
   * @type {number}
   *
   * @see _itemsPerPage
   */
  get itemsPerPage() {
    return this._itemsPerPage;
  }

  /**
   * A flag to indicate if the carousel should loop infinitely.
   *
   * @readonly
   *
   * @type {boolean}
   *
   * @see _loop
   */
  get loop() {
    return this._loop;
  }

  /**
   * The delay in milliseconds before transitioning slides.
   *
   * @type {number}
   *
   * @see _delays.transition
   */
  get transitionDelay() {
    return this._delays.transition;
  }

  set transitionDelay(value) {
    isValidType("number", { transitionDelay: value });

    if (value !== this.transitionDelay && value >= 0) {
      this._delays.transition = value;
    }
  }

  /**
   * The duration time (in milliseconds) for the transition between carousel items.
   *
   * @type {number}
   *
   * @see _durations.transition
   */
  get transitionDuration() {
    return this._durations.transition;
  }

  set transitionDuration(value) {
    isValidType("number", { transitionDuration: value });

    if (this._durations.transition !== value && value >= 0) {
      this._durations.transition = value;
      this._setTransitionDuration();
    }
  }

  /**
   * The label for the autoplay button when the carousel is paused.
   *
   * @type {string}
   *
   * @see _playText
   */
  get playText() {
    return this._playText;
  }

  set playText(value) {
    isValidType("string", { playText: value });

    if (this._playText !== value) {
      this._playText = value;
    }
  }

  /**
   * The label for the autoplay button when the carousel is playing.
   *
   * @type {string}
   *
   * @see _pauseText
   */
  get pauseText() {
    return this._pauseText;
  }

  set pauseText(value) {
    isValidType("string", { pauseText: value });

    if (this._pauseText !== value) {
      this._pauseText = value;
    }
  }

  /**
   * The current action being performed by the carousel.
   *
   * @type {string}
   *
   * @see _currentAction
   */
  get currentAction() {
    return this._currentAction;
  }

  /**
   * Sets all DOM elements within the carousel.
   *
   * Utilizes _setDOMElementType and _resetDOMElementType.
   *
   * @protected
   */
  _setDOMElements() {
    this._setDOMElementType("carouselItemContainer", {
      context: this.dom.carousel,
    });
    this._setDOMElementType("carouselControlContainer", {
      context: this.dom.carousel,
    });
    this._setDOMElementType("carouselTabContainer", {
      context: this.dom.carousel,
    });

    if (this.dom.carouselItemContainer) {
      this._setDOMElementType("carouselItems", {
        context: this.dom.carouselItemContainer,
      });
    }
    if (this.dom.carouselControlContainer) {
      this._setDOMElementType("carouselControls", {
        context: this.dom.carouselControlContainer,
      });
      this._setDOMElementType("autoplay", {
        context: this.dom.carouselControlContainer,
      });
      this._setDOMElementType("next", {
        context: this.dom.carouselControlContainer,
      });
      this._setDOMElementType("previous", {
        context: this.dom.carouselControlContainer,
      });
    }

    if (this._dom.carouselTabContainer) {
      this._setDOMElementType("carouselTabs", {
        context: this.dom.carouselTabContainer,
      });
    }
  }

  /**
   * Creates and initializes all carousel items.
   *
   * @protected
   */
  _createChildElements() {
    this.dom.carouselItems.forEach((item, index) => {
      const carouselItem = new CarouselItem({
        carouselItemElement: item,
        tabElement: this.dom.carouselTabs ? this.dom.carouselTabs[index] : null,
        parent: this,
        prefix: this.prefix,
        initializeClass: this.classes.initialize,
        initialize: true,
      });

      this._elements.carouselItems.push(carouselItem);
    });
  }

  /**
   * Sets the IDs of the carousel and its children if they do not already exist.
   *
   * The generated IDs use the key and follow the format:
   *  - carousel: `carousel-${key}`
   *  - carousel items: `carousel-item-${key}-${index}`
   *  - carousel tabs: `carousel-tab-${key}-${index}`
   */
  _setIds() {
    this.dom.carousel.id = this.dom.carousel.id || `carousel-${this.key}`;

    this.dom.carouselItems.forEach((item, index) => {
      item.id = item.id || `carousel-item-${this.key}-${index}`;
    });

    this.dom.carouselTabs.forEach((tab, index) => {
      tab.id = tab.id || `carousel-tab-${this.key}-${index}`;
    });

    this._id = this.dom.carousel.id;
  }

  /**
   * Sets ARIA attributes throughout the carousel.
   */
  _setAriaAttributes() {
    // Make sure the carousel has a proper role.
    // Sections and role="region" are acceptable in certain cases, so
    // we only need to fallback to role="group" if neither of those are present.
    if (
      !isTag("section", { carousel: this.dom.carousel }, { shouldThrow: false })
        .status &&
      !this.dom.carousel.getAttribute("role") !== "region"
    ) {
      this.dom.carousel.setAttribute("role", "group");
    }

    // Set the role description for the carousel.
    this._dom.carousel.setAttribute("aria-roledescription", "carousel");

    if (this.dom.carouselTabContainer) {
      this.dom.carouselTabContainer.setAttribute("role", "tablist");
    }

    this.dom.carouselTabs.forEach((tab, index) => {
      if (!isTag("button", { tab: tab }, { shouldThrow: false }).status) {
        tab.setAttribute("role", "button");
      }

      tab.setAttribute("aria-selected", index === 0);
      tab.setAttribute("aria-controls", this.dom.carouselItems[index].id);
    });
  }

  /**
   * Sets the transition duration for the carousel as a CSS custom property.
   *
   * The custom property is set as `--graupl-carousel-transition-duration`.
   *
   * @protected
   */
  _setCustomProps() {
    this.dom.carousel.style.setProperty(
      `--${this.prefix}carousel-transition-duration`,
      `${this.transitionDuration}ms`
    );
  }

  /**
   * Handles the autoplay functionality of the carousel.
   *
   * - Adds the appropriate class to the autoplay button.
   * - Removes the appropriate class from the autoplay button.
   * - Sets the appropriate aria-label for the autoplay button.
   * - Sets the appropriate aria-live for the carousel.
   * - Sets/clears the interval for autoplaying the carousel.
   *
   * @protected
   */
  _handleAutoplay() {
    if (this.autoplay) {
      addClass(this.pauseClass, this.dom.autoplay);
      removeClass(this.playClass, this.dom.autoplay);

      this.dom.autoplay.setAttribute("aria-label", this.pauseText);
      this.dom.carousel.setAttribute("aria-live", "off");

      this._setInterval(() => this.activateNextItem(), this.transitionDelay);
    } else {
      addClass(this.playClass, this.dom.autoplay);
      removeClass(this.pauseClass, this.dom.autoplay);

      this.dom.autoplay.setAttribute("aria-label", this.playText);
      this.dom.carousel.setAttribute("aria-live", "polite");

      this._clearInterval();
    }
  }

  /**
   * Handles the intersection observer functionality for the carousel.
   *
   * Sets up an intersection observer to observe the carousel items and update
   * the current item when the carousel is scrolled manually.
   */
  _handleIntersection() {
    const options = {
      root: this.dom.carousel,
      threshold: 0.75,
    };

    const observer = new IntersectionObserver((entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting && !this.isTransitioning) {
          const index = this.dom.carouselItems.indexOf(entry.target);
          if (index !== -1) {
            this.activateItem(index, { scroll: false });
          }
        }
      });
    }, options);

    this.dom.carouselItems.forEach((item) => {
      observer.observe(item);
    });
  }

  /**
   * Handles the focus events throughout the carousel for proper use.
   *
   * - Adds a `focusin` listener to the carousel element to pause autoplay.
   * - Adds a `focusout` listener to the carousel element to resume autoplay.
   */
  _handleFocus() {
    // Pause autoplay when anything in the carousel is focused.
    this._addEventListener("focusin", this.dom.carousel, () => {
      if (this.autoplay) {
        this._clearInterval();
      }
    });

    this._addEventListener("focusout", this.dom.carousel, () => {
      if (this.autoplay) {
        this._setInterval(() => this.activateNextItem(), this.transitionDelay);
      }
    });
  }

  /**
   * Handles the click events throughout the carousel.
   *
   * - Adds a `click` listener to the next control to activate the next item.
   * - Adds a `click` listener to the previous control to activate the previous item.
   * - Adds a `click` listener to the autoplay control to toggle autoplay.
   * - Adds a `click` listener to each tab control to activate the corresponding item.
   */
  _handleClick() {
    this._addEventListener("click", this.dom.next, (event) => {
      if (event.button !== 0) {
        return;
      }

      preventEvent(event);

      this.currentEvent = "mouse";
      this.activateNextItem();
    });

    this._addEventListener("click", this.dom.previous, (event) => {
      if (event.button !== 0) {
        return;
      }

      preventEvent(event);

      this.currentEvent = "mouse";
      this.activatePreviousItem();
    });

    this._addEventListener("click", this.dom.autoplay, (event) => {
      if (event.button !== 0) {
        return;
      }

      preventEvent(event);

      this.currentEvent = "mouse";
      this.toggleAutoplay();
    });

    this.elements.carouselItems.forEach((item) => {
      if (!item.dom.tab) {
        return;
      }

      this._addEventListener("click", item.dom.tab, (event) => {
        if (event.button !== 0) {
          return;
        }

        preventEvent(event);

        this.currentEvent = "mouse";
        this.activateItem(
          this.dom.carouselItems.indexOf(item.dom.carouselItem)
        );
      });
    });
  }

  /**
   * Handles the hover events throughout the carousel for proper use.
   *
   * - Adds a `pointerover` listener to the carousel to pause autoplay.
   * - Adds a `pointerleave` listener to the carousel to resume autoplay.
   */
  _handleHover() {
    // Pause autoplay when anything in the carousel is hovered.
    this._addEventListener("pointerover", this.dom.carousel, () => {
      if (this.autoplay) {
        this._clearInterval();
      }
    });

    this._addEventListener("pointerleave", this.dom.carousel, () => {
      if (this.autoplay) {
        this._setInterval(() => this.activateNextItem(), this.transitionDelay);
      }
    });
  }

  /**
   * Handles keydown events throughout the carousel for proper use.
   *
   * - Adds a `keydown` listener to all control elements.
   *   - Prevents Space and Enter key events.
   * - Adds a `keydown` listener to all tab elements.
   *   - Prevents Space and Enter key events.
   */
  _handleKeydown() {
    this.dom.carouselControls.forEach((control) => {
      this._addEventListener("keydown", control, (event) => {
        const key = keyPress(event);

        switch (key) {
          case "Space":
          case "Enter":
            // Prevent the default action of the event.
            preventEvent(event);

            break;
        }
      });
    });

    this.dom.carouselTabs.forEach((tab) => {
      this._addEventListener("keydown", tab, (event) => {
        const key = keyPress(event);

        switch (key) {
          case "Space":
          case "Enter":
            // Prevent the default action of the event.
            preventEvent(event);

            break;
        }
      });
    });
  }

  /**
   * Handles keyup events throughout the carousel for proper use.
   *
   * - Adds a `keyup` listener to all control elements.
   *   - Activates the next/previous item depending on which control is pressed.
   *   - Toggles autoplay if the autoplay control is pressed.
   *
   */
  _handleKeyup() {
    // Activate the next item if the space or enter key on the next control.
    this._addEventListener("keyup", this.dom.next, (event) => {
      const key = keyPress(event);

      switch (key) {
        case "Space":
        case "Enter":
          this.activateNextItem();

          // Prevent the default action of the event.
          preventEvent(event);

          break;
      }
    });

    // Activate the previous item if the space or enter key on the previous control.
    this._addEventListener("keyup", this.dom.previous, (event) => {
      const key = keyPress(event);

      switch (key) {
        case "Space":
        case "Enter":
          this.activatePreviousItem();

          // Prevent the default action of the event.
          preventEvent(event);

          break;
      }
    });

    // Toggle autoplay if the space or enter key on the autoplay control.
    this._addEventListener("keyup", this.dom.autoplay, (event) => {
      const key = keyPress(event);

      switch (key) {
        case "Space":
        case "Enter":
          this.toggleAutoplay();

          // Prevent the default action of the event.
          preventEvent(event);

          break;
      }
    });

    // Activate the item if the space or enter key on the tab control.
    this.dom.carouselTabs.forEach((tab, index) => {
      this._addEventListener("keyup", tab, (event) => {
        const key = keyPress(event);

        switch (key) {
          case "Space":
          case "Enter":
            this.activateItem(index);

            // Prevent the default action of the event.
            preventEvent(event);

            break;
        }
      });
    });
  }

  /**
   * Appends and prepends a number of carousel items to the end of the carousel item container.
   *
   * This is used for infinite scrolling.
   *
   * The number of items appended is determined by the itemsPerPage property.
   */
  _handleLoop() {
    const itemsToAppend = new Map();
    const itemsToPrepend = new Map();
    const container = this.dom.carouselItemContainer;

    for (let i = 0; i < this.itemsPerPage; i++) {
      itemsToAppend.set(
        this.dom.carouselItems[i],
        this.dom.carouselItems.indexOf(this.dom.carouselItems[i])
      );
    }

    for (
      let i = this.dom.carouselItems.length - this.itemsPerPage;
      i < this.dom.carouselItems.length;
      i++
    ) {
      itemsToPrepend.set(
        this.dom.carouselItems[i],
        this.dom.carouselItems.indexOf(this.dom.carouselItems[i])
      );
    }

    itemsToAppend.forEach((index, item) => {
      const clone = item.cloneNode(true);
      clone.setAttribute("aria-hidden", "true");
      clone.setAttribute("inert", "true");
      clone.setAttribute("id", `${item.id}-clone`);

      container.appendChild(clone);

      const carouselItem = new CarouselItem({
        carouselItemElement: clone,
        clone: this._elements.carouselItems[index],
        parent: this,
        prefix: this.prefix,
        initializeClass: this.classes.initialize,
        initialize: true,
      });

      this.dom.carouselItems.push(clone);
      this._elements.carouselItems.push(carouselItem);
    });

    itemsToPrepend.forEach((index, item) => {
      const clone = item.cloneNode(true);
      clone.setAttribute("aria-hidden", "true");
      clone.setAttribute("inert", "true");
      clone.setAttribute("id", `${item.id}-clone`);

      container.insertBefore(clone, container.firstChild);

      const carouselItem = new CarouselItem({
        carouselItemElement: clone,
        clone: this._elements.carouselItems[index],
        parent: this,
        prefix: this.prefix,
        initializeClass: this.classes.initialize,
        initialize: true,
      });

      this.dom.carouselItems.unshift(clone);
      this._elements.carouselItems.unshift(carouselItem);
    });
  }

  /**
   * Activates the current carousel item.
   *
   * @param root0
   * @param root0.scroll
   */
  activateCurrentItem({ scroll = true } = {}) {
    this.currentCarouselItem.activate({ scroll });
  }

  /**
   * Deactivates the current carousel item.
   */
  deactivateCurrentItem() {
    this.currentCarouselItem.deactivate();
  }

  /**
   * Activates the carousel item at a given index.
   *
   * @param {number}  index                   - The index of the carousel item to activate.
   * @param {object}  [options = {}]          - Additional options for activating the item.
   * @param {boolean} [options.scroll = true] - A flag to indicate if the carousel should scroll to the activated item.
   */
  activateItem(index, { scroll = true } = {}) {
    if (this.autoplay) {
      this._clearInterval();
    }

    this.deactivateCurrentItem();
    this.currentItem = index;
    this.activateCurrentItem({ scroll });

    if (this.autoplay) {
      this._setInterval(() => this.activateNextItem(), this.transitionDelay);
    }

    if (index < this.itemsPerPage) {
      this.currentItem = this.itemsPerPage;
    } else if (index > this.dom.carouselItems.length - this.itemsPerPage) {
      this.currentItem = this.dom.carouselItems.length - this.itemsPerPage;
    }
  }

  /**
   * Activates the first carousel item.
   */
  activateFirstItem() {
    this.activateItem(0);
  }

  /**
   * Activates the last carousel item.
   */
  activateLastItem() {
    this.activateItem(this.dom.carouselItems.length - 1);
  }

  /**
   * Activates the next carousel item.
   */
  activateNextItem() {
    if (this.currentItem + 1 >= this.dom.carouselItems.length) {
      this.activateFirstItem();
    } else {
      this.activateItem(this.currentItem + 1);
    }
  }

  /**
   * Activates the previous carousel item.
   */
  activatePreviousItem() {
    if (
      this.currentItem - 1 < 0 ||
      (this.loop && this.currentItem - 1 < this.itemsPerPage)
    ) {
      this.activateLastItem();
    } else {
      this.activateItem(this.currentItem - 1);
    }
  }

  /**
   * Toggles autoplay on the carousel.
   */
  toggleAutoplay() {
    this.autoplay = !this.autoplay;

    this._handleAutoplay();
  }
}

export default Carousel;
