/**
 * @file
 * The Tabs class.
 */

import TabToggle from "./TabToggle.js";
import { isValidType, isValidClassList } from "../validate.js";
import { addClass, removeClass } from "../domHelpers.js";
import { keyPress, preventEvent } from "../eventHandlers.js";
import Component from "../Component.js";

/**
 * The Tabs component.
 *
 * @extends Component
 *
 * Protected fields are documented below.
 *
 * @property {Object<HTMLElement, HTMLElement[]>} _dom                         - The DOM elements within the tabs.
 * @property {HTMLElement}                        _dom.tabs                    - The tabs element.
 * @property {HTMLElement}                        _dom.tabList                 - The tab list element.
 * @property {HTMLElement[]}                      _dom.tabToggles              - An array of tab toggles.
 * @property {HTMLElement[]}                      _dom.tabContents             - An array of tab contents.
 * @property {string}                             _rootDOMElement              - The root DOM element of the tabs.
 * @property {string[]}                           _protectedDOMElements        - The DOM elements within the tabs that cannot be reset or generated by the tabs themselves.
 * @property {Object<string>}                     _selectors                   - The query selectors used by the tabs.
 * @property {string}                             _selectors.tabList           - The query selector for the tab list.
 * @property {string}                             _selectors.tabToggles        - The query selector for tab toggles.
 * @property {string}                             _selectors.tabContents       - The query selector for tab contents.
 * @property {Object<TabToggle[]>}                _elements                    - The instantiated elements within the tabs.
 * @property {TabToggle[]}                        _elements.tabToggles         - The list of tab toggles.
 * @property {Object<string, string[]>}           _classes                     - The CSS classes to apply when the tabs are in various states.
 * @property {string|string[]}                    _classes.open                - The class(es) to apply when the tab is open.
 * @property {string|string[]}                    _classes.close               - The class(es) to apply when the tab is closed.
 * @property {string|string[]}                    _classes.transition          - The class(es) to apply when the tab is transitioning between states.
 * @property {string|string[]}                    _classes.initialize          - The class(es) to apply when the tab is initializing.
 * @property {Object<number>}                     _durations                   - The duration times (in milliseconds) for various aspects throughout the tabs.
 * @property {number}                             _durations.transition        - The duration time (in milliseconds) for the transition between open and closed states.
 * @property {number}                             _durations.open              - The duration time (in milliseconds) for the transition from closed to open states.
 * @property {number}                             _durations.close             - The duration time (in milliseconds) for the transition from open to closed states.
 * @property {boolean}                            _automatic                   - A flag to set if focusing a tab toggle will automatically activate it.
 * @property {number}                             _currentChild                - The index of the current child node.
 * @property {string}                             _storageKey                  - The key used for storage.
 * @property {Object<CustomEvent>}                _events                      - Custom events that can be triggered throughout the tabs.
 * @property {Object<number>}                     _delays                      - The delay times (in milliseconds) for various aspects throughout the tabs.
 * @property {string}                             _focusState                  - The current state of the tabs' focus.
 * @property {string}                             _currentEvent                - The last type of event triggered within the tabs.
 * @property {string}                             _breakpoint                  - The breakpoint that the tabs will call media query list events.
 * @property {string}                             _mediaQueryString            - The media query to use to trigger media query list events.
 * @property {MediaQueryList|null}                _mediaQueryList              - The MediaQueryList for the tabs.
 * @property {Function}                           _mediaQueryListEventCallback - The callback for media query list events.
 * @property {Object<Function>}                   _intervals                   - Intervals throughout the tabs.
 * @property {Object<Function>}                   _timeouts                    - Timeouts throughout the tabs.
 * @property {object[]}                           _listeners                   - Event listeners throughout the tabs.
 * @property {string}                             _prefix                      - The prefix used for CSS custom properties and attributes.
 * @property {string}                             _key                         - The key used to generate IDs throughout the tabs.
 * @property {string}                             _id                          - The main ID of the tabs.
 * @property {boolean}                            _valid                       - The validity state of the tabs.
 * @property {boolean}                            _initialized                 - The initialized state of the tabs.
 * @property {string[]}                           _errors                      - The errors found throughout the tabs.
 */
class Tabs extends Component {
  _rootDOMElement = "tabs";
  _automatic = false;
  _currentChild = 0;
  _storageKey = "tabs";

  /**
   * Constructs a new `Tab`.
   *
   * @param {object}             options                                      - The options for generating the tab.
   * @param {HTMLElement}        [options.tabsElement]                        - The tab element in the DOM.
   * @param {string}             [options.tabListSelector = .tab-list]        - The query selector string for the tab list.
   * @param {string}             [options.tabTogglesSelector = .tab-toggle]   - The query selector string for tab toggle.
   * @param {string}             [options.tabContentsSelector = .tab-content] - The query selector string for tab content.
   * @param {?(string|string[])} [options.openClass = show]                   - The class to apply when a tab is "open".
   * @param {?(string|string[])} [options.closeClass = hide]                  - The class to apply when a tab is "closed".
   * @param {?(string|string[])} [options.transitionClass = null]             - The class to apply when a tab is transitioning between "open" and "closed" states.
   * @param {number}             [options.transitionDuration = 300]           - The duration of the transition between "open" and "closed" states (in milliseconds).
   * @param {number}             [options.openDuration = -1]                  - The duration of the transition from "closed" to "open" states (in milliseconds).
   * @param {number}             [options.closeDuration = -1]                 - The duration of the transition from "open" to "closed" states (in milliseconds).
   * @param {boolean}            [options.automaticActivation = false]        - A flag to set if focusing a tab item toggle will automatically activate it.
   * @param {?string}            [options.prefix = graupl-]                   - The prefix to use for CSS custom properties.
   * @param {?string}            [options.key = null]                         - The key used to generate IDs throughout the tab.
   * @param {?(string|string[])} [options.initializeClass = initializing]     - The class to apply when tabs are initializing.
   * @param {boolean}            [options.initialize = false]                 - A flag to initialize the tab immediately upon creation.
   */
  constructor({
    tabsElement,
    tabListSelector = ".tab-list",
    tabTogglesSelector = ".tab-toggle",
    tabContentsSelector = ".tab-content",
    openClass = "show",
    closeClass = "hide",
    transitionClass = null,
    transitionDuration = 300,
    openDuration = -1,
    closeDuration = -1,
    automaticActivation = false,
    prefix = "graupl-",
    key = null,
    initializeClass = "initializing",
    initialize = false,
  }) {
    super({
      prefix,
      key,
      initializeClass,
    });

    // Set DOM elements.
    this._dom.tabs = tabsElement;
    this._dom.tabList = null;
    this._dom.tabToggles = [];
    this._dom.tabContents = [];

    // Set DOM selectors.
    this._selectors.tabList = tabListSelector;
    this._selectors.tabToggles = tabTogglesSelector;
    this._selectors.tabContents = tabContentsSelector;

    // Set elements.
    this._elements.tabToggles = [];

    // Set open/close classes.
    this._classes.open = openClass || "";
    this._classes.close = closeClass || "";
    this._classes.transition = transitionClass || "";

    // Set transition duration.
    this._durations.transition = transitionDuration;
    this._durations.open = openDuration;
    this._durations.close = closeDuration;

    // Set automatic activation.
    this._automatic = automaticActivation;

    if (initialize) {
      this.initialize();
    }
  }

  /**
   * Initializes the tabs.
   */
  initialize() {
    this._addEventListener(
      "grauplComponentPreinitialize",
      this.rootDOMElement,
      () => {
        // Add the initialization class.
        addClass(this.initializeClass, this.dom.tabs);
      }
    );

    this._addEventListener("grauplComponentInitialize", this.dom.tabs, () => {
      // Make sure the first tab is open if no other tab is active.
      if (
        this.elements.tabToggles.filter((toggle) => toggle.isActive).length ===
        0
      ) {
        this.elements.tabToggles[0].show();
      }
    });

    this._addEventListener(
      "grauplComponentPostinitialize",
      this.rootDOMElement,
      () => {
        // Remove the initialization class.
        requestAnimationFrame(() => {
          removeClass(this.initializeClass, this.dom.tabs);
        });
      }
    );

    super.initialize();
  }

  /**
   * The class(es) to apply when the tab is open.
   *
   * @type {string|string[]}
   *
   * @see _classes.open
   */
  get openClass() {
    return this._classes.open;
  }

  set openClass(value) {
    isValidClassList({ openClass: value });

    if (this._classes.open !== value) {
      this._classes.open = value;
    }
  }

  /**
   * The class(es) to apply when the tab is closed.
   *
   * @type {string|string[]}
   *
   * @see _classes.close
   */
  get closeClass() {
    return this._classes.close;
  }

  set closeClass(value) {
    isValidClassList({ closeClass: value });

    if (this._classes.close !== value) {
      this._classes.close = value;
    }
  }

  /**
   * The class(es) to apply when the tab is transitioning between open and closed.
   *
   * @type {string|string[]}
   *
   * @see _classes.transition
   */
  get transitionClass() {
    return this._classes.transition;
  }

  set transitionClass(value) {
    isValidClassList({ transitionClass: value });

    if (this._classes.transition !== value) {
      this._classes.transition = value;
    }
  }

  /**
   * The duration time (in milliseconds) for the transition between open and closed states.
   *
   * @type {number}
   *
   * @see _durations.transition
   */
  get transitionDuration() {
    return this._durations.transition;
  }

  set transitionDuration(value) {
    isValidType("number", { transitionDuration: value });

    if (this._durations.transition !== value) {
      this._durations.transition = value;
      this._setTransitionDurations();
    }
  }

  /**
   * The duration time (in milliseconds) for the transition from closed to open states.
   *
   * If openDuration is set to -1, the transitionDuration will be used instead.
   *
   * @type {number}
   *
   * @see _durations.open
   */
  get openDuration() {
    return this._durations.open === -1
      ? this.transitionDuration
      : this._durations.open;
  }

  set openDuration(value) {
    isValidType("number", { openDuration: value });

    if (this._durations.open !== value) {
      this._durations.open = value;
      this._setTransitionDurations();
    }
  }

  /**
   * The duration time (in milliseconds) for the transition from open to closed states.
   *
   * If closeDuration is set to -1, the transitionDuration will be used instead.
   *
   * @type {number}
   *
   * @see _durations.close
   */
  get closeDuration() {
    return this._durations.close === -1
      ? this.transitionDuration
      : this._durations.close;
  }

  set closeDuration(value) {
    isValidType("number", { closeDuration: value });

    if (this._durations.close !== value) {
      this._durations.close = value;
      this._setTransitionDurations();
    }
  }

  /**
   * A flag to set if focusing a tab item toggle will automatically activate it.
   *
   * @type {boolean}
   *
   * @see _automatic
   */
  get isAutomatic() {
    return this._automatic;
  }

  set isAutomatic(value) {
    isValidType("boolean", { isAutomatic: value });

    if (this._automatic !== value) {
      this._automatic = value;
    }
  }

  /**
   * The current index of the tab item.
   *
   * @readonly
   *
   * @type {number}
   *
   * @see _currentChild
   */
  get currentChild() {
    return this._currentChild;
  }

  set currentChild(value) {
    isValidType("number", { currentChild: value });

    if (
      this._currentChild !== value &&
      value >= 0 &&
      value < this.elements.tabToggles.length
    ) {
      this._currentChild = value;
    }
  }
  /**
   * The currently selected tab item.
   *
   * @readonly
   *
   * @type {TabToggle}
   */
  get currentTabToggle() {
    return this.elements.tabToggles[this.currentChild];
  }

  /**
   * Validates all aspects of the tabs to ensure proper functionality.
   *
   * Keys are altered to match the arguments passed in during creation where possible.
   *
   * @protected
   *
   * @return {boolean} - The result of the validation.
   */
  _validate() {
    this._addEventListener(
      "grauplComponentValidate",
      this.rootDOMElement,
      () => {
        // Boolean checks.
        const booleans = {
          automaticActivation: this._automatic,
        };

        // Check the booleans.
        const booleanChecks = isValidType("boolean", booleans, {
          shouldThrow: false,
        });

        // Handle boolean check failure.
        if (!booleanChecks.status) {
          this._errors = [...this._errors, ...booleanChecks.errors];
          this._valid = false;
        }
      }
    );

    return super._validate();
  }

  /**
   * Sets the IDs throughout the tabs.
   *
   * The generated IDs use the key and follow the format:
   *  - tabs: `tabs-${key}`
   *  - tab-list: `tab-list-${key}`
   *
   * @protected
   */
  _setIds() {
    this.dom.tabs.id = this.dom.tabs.id || `tabs-${this.key}`;
    this.dom.tabList.id = this.dom.tabList.id || `tab-list-${this.key}`;

    this._id = this.dom.tabs.id;
  }

  /**
   * Sets ARIA attributes throughout the tabs.
   *
   * @protected
   */
  _setAriaAttributes() {
    this.dom.tabList.setAttribute("role", "tablist");
  }

  /**
   * Sets custom props throughout the tabs.
   *
   * The custom properties are:
   *   - `--graupl-tabs-transition-duration`,
   *   - `--graupl-tabs-open-transition-duration`, and
   *   - `--graupl-tabs-close-transition-duration`.
   *
   * The prefix of `graupl-` can be changed by setting the tab's prefix value.
   *
   * @protected
   */
  _setCustomProps() {
    this.dom.tabs.style.setProperty(
      `--${this.prefix}tabs-transition-duration`,
      `${this.transitionDuration}ms`
    );

    this.dom.tabs.style.setProperty(
      `--${this.prefix}tabs-open-transition-duration`,
      `${this.openDuration}ms`
    );

    this.dom.tabs.style.setProperty(
      `--${this.prefix}tabs-close-transition-duration`,
      `${this.closeDuration}ms`
    );
  }

  /**
   * Sets all DOM elements within the tabs.
   *
   * Utilizes _setDOMElementType and
   * _resetDOMElementType.
   *
   * @protected
   */
  _setDOMElements() {
    this._resetDOMElementType("tabList");
    this._setDOMElementType("tabList", { context: this.dom.tabs });

    if (this.dom.tabList) {
      this._resetDOMElementType("tabToggles");
      this._setDOMElementType("tabToggles", { context: this.dom.tabList });
    }

    this._resetDOMElementType("tabContents");
    this._setDOMElementType("tabContents", { context: this.dom.tabs });
  }

  /**
   * Creates and initializes all tab toggles.
   *
   * @protected
   */
  _createChildElements() {
    this.dom.tabToggles.forEach((tabToggles, index) => {
      const toggle = new TabToggle({
        toggleElement: tabToggles,
        contentElement: this.dom.tabContents[index],
        parentTab: this,
      });

      toggle.initialize();

      this._elements.tabToggles.push(toggle);
    });
  }

  /**
   * Handles focus events throughout the tab for proper use.
   *
   * - Adds a `focus` listener to every tab item so when it gains focus,
   *   it will set the tab's current child to the index of the item.
   *
   * @protected
   */
  _handleFocus() {
    this.elements.tabToggles.forEach((toggle, index) => {
      this._addEventListener("focus", toggle.dom.toggle, () => {
        this.currentChild = index;

        if (this.isAutomatic) {
          this.currentTabToggle.show();
        }
      });
    });
  }

  /**
   * Handles click events throughout the tab item for proper use.
   *
   * - Adds a `click` listener to the tab item toggles that will toggle each tab item.
   *
   * @protected
   */
  _handleClick() {
    this.elements.tabToggles.forEach((toggle, index) => {
      this._addEventListener("click", toggle.dom.toggle, () => {
        this.currentChild = index;
        toggle.show();
      });
    });
  }

  /**
   * Handles keydown events throughout the tab item for proper use.
   *
   * This method exists to assist the _handleKeyup method.
   *
   * - Adds a `keydown` listener to all tab item toggles.
   *   - Blocks propagation on "Space", "Enter", "ArrowRight", "ArrowLeft", "Home", and "End" keys.
   */
  _handleKeydown() {
    this.dom.tabToggles.forEach((tabToggles) => {
      this._addEventListener("keydown", tabToggles, (event) => {
        const key = keyPress(event);
        const ToggleKeys = [
          "Space",
          "Enter",
          "ArrowRight",
          "ArrowLeft",
          "Home",
          "End",
        ];

        // Prevent default behavior for space and enter keys.
        if (ToggleKeys.includes(key)) {
          preventEvent(event);
        }
      });
    });
  }

  /**
   * Handles keyup events throughout the tab item for proper use.
   *
   * Adds the follow keybindings (explanations are taken from the WAI ARIA Practices Guide Tab Pattern):
   *
   * - `Enter` or `Space`:
   *   - When focus is on the tab link for a collapsed panel, expands the associated panel. If the implementation allows only one panel to be expanded, and if another panel is expanded, collapses that panel.
   *   - When focus is on the tab link for an expanded panel, collapses the panel if the implementation supports collapsing. Some implementations require one panel to be expanded at all times and allow only one panel to be expanded; so, they do not support a collapse function.
   * - `Tab`: Moves focus to the next focusable element; all focusable elements in the tab are included in the page `Tab` sequence.
   * - `Shift + Tab`: Moves focus to the previous focusable element; all focusable elements in the tab are included in the page `Tab` sequence.
   * - `Down Arrow` (Optional): If focus is on an tab link, moves focus to the next tab link. If focus is on the last tab link, either does nothing or moves focus to the first tab link.
   * - `Up Arrow` (Optional): If focus is on an tab link, moves focus to the previous tab link. If focus is on the first tab link, either does nothing or moves focus to the last tab link.
   * - `Home` (Optional): When focus is on an tab link, moves focus to the first tab link.
   * - `End` (Optional): When focus is on an tab link, moves focus to the last tab link.
   *
   * Note: When the above explanations mention "tab link", they are referring to the tab item toggle.
   */
  _handleKeyup() {
    this.dom.tabToggles.forEach((tabToggles) => {
      this._addEventListener("keyup", tabToggles, (event) => {
        const key = keyPress(event);

        switch (key) {
          case "Space":
          case "Enter":
            preventEvent(event);
            this.currentTabToggle.show();

            break;
          case "Home":
            preventEvent(event);
            this.focusFirstChild();

            break;
          case "End":
            preventEvent(event);
            this.focusLastChild();

            break;
          case "ArrowRight":
            preventEvent(event);
            this.focusNextChild();

            break;
          case "ArrowLeft":
            preventEvent(event);
            this.focusPreviousChild();

            break;
        }
      });
    });
  }

  /**
   * Focus the tab's current child.
   */
  focusCurrentChild() {
    if (this.currentChild !== -1) {
      this.currentTabToggle.focus();
    }
  }

  /**
   * Focuses the tab's child at a given index.
   *
   * @param {number} index - The index of the child to focus.
   */
  focusChild(index) {
    this.blurCurrentChild();
    this.currentChild = index;
    this.focusCurrentChild();
  }

  /**
   * Focuses the tab's first child.
   */
  focusFirstChild() {
    this.focusChild(0);
  }

  /**
   * Focus the tab's last child.
   */
  focusLastChild() {
    this.focusChild(this.elements.tabToggles.length - 1);
  }

  /**
   * Focus the tab's next child.
   */
  focusNextChild() {
    if (this.currentChild < this.elements.tabToggles.length - 1) {
      this.focusChild(this.currentChild + 1);
    } else {
      this.focusFirstChild();
    }
  }

  /**
   * Focus the tab's previous child.
   */
  focusPreviousChild() {
    if (this.currentChild > 0) {
      this.focusChild(this.currentChild - 1);
    } else {
      this.focusLastChild();
    }
  }

  /**
   * Blurs the tab's current child.
   */
  blurCurrentChild() {
    if (this.currentChild !== -1) {
      this.currentTabToggle.blur();
    }
  }
}

export default Tabs;
