/**
 * @file
 * The TabToggle class.
 */

/* global Tabs */

import { addClass, removeClass } from "../domHelpers.js";
import TransactionalValue from "../TransactionalValue.js";
import Component from "../Component.js";

/**
 * @event grauplTabToggleActivate
 * Fired when the tab toggle is activated.
 *
 * @type {CustomEvent}
 *
 * @property {boolean}           bubbles       - Whether the event bubbles.
 * @property {Object<TabToggle>} detail        - The event details.
 * @property {TabToggle}         detail.toggle - The tab toggle that was activated.
 */

/**
 * @event grauplTabToggleDeactivate
 * Fired when the tab toggle is deactivated.
 *
 * @type {CustomEvent}
 *
 * @property {boolean}           bubbles       - Whether the event bubbles.
 * @property {Object<TabToggle>} detail        - The event details.
 * @property {TabToggle}         detail.toggle - The tab toggle that was deactivated.
 */

/**
 * The Tab toggle component.
 *
 * @extends Component
 *
 * Protected fields are documented below.
 *
 * @property {Object<HTMLElement>}       _dom                          - The DOM elements within the tab toggle.
 * @property {HTMLElement}               _dom.toggle                   - The toggle element.
 * @property {HTMLElement}               _dom.content                  - The content element.
 * @property {string}                    _rootDOMElement               - The root DOM element of the tab toggle.
 * @property {string[]}                  _protectedDOMElements         - The DOM elements within the tab toggle that cannot be reset or generated by the tab toggle itself.
 * @property {Object<Tabs>}              _elements                     - The instantiated elements within the tab toggle.
 * @property {Tabs}                      _elements.parent              - The parent tabs element.
 * @property {TransactionalValue}        _active                       - The active state of the tab toggle.
 * @property {Object<CustomEvent>}       _events                       - Custom events that can be triggered throughout the tab toggle.
 * @property {grauplTabToggleActivate}   _events.activate              - The event triggered when the tab toggle is activated.
 * @property {grauplTabToggleDeactivate} _events.deactivate            - The event triggered when the tab toggle is deactivated.
 * @property {Object<string>}            _selectors                    - The query selectors used by the tab toggle.
 * @property {Object<string, string[]>}  _classes                      - The CSS classes to apply when the tab toggle is in various states.
 * @property {Object<number>}            _durations                    - The duration times (in milliseconds) for various aspects throughout the tab toggle.
 * @property {Object<number>}            _delays                       - The delay times (in milliseconds) for various aspects throughout the tab toggle.
 * @property {string}                    _focusState                   - The current state of the tab toggle's focus.
 * @property {string}                    _currentEvent                 - The last type of event triggered within the tab toggle.
 * @property {string}                    _breakpoint                   - The breakpoint that the tab toggle will call media query list events.
 * @property {string}                    _mediaQueryString             - The media query to use to trigger media query list events.
 * @property {MediaQueryList|null}       _mediaQueryList               - The MediaQueryList for the tab toggle.
 * @property {Function}                  _mediaQueryListEventCallback  - The callback for media query list events.
 * @property {Object<Function>}          _intervals                    - Intervals throughout the tab toggle.
 * @property {Object<Function>}          _timeouts                     - Timeouts throughout the tab toggle.
 * @property {object[]}                  _listeners                    - Event listeners throughout the tab toggle.
 * @property {string}                    _prefix                       - The prefix used for CSS custom properties and attributes.
 * @property {string}                    _key                          - The key used to generate IDs throughout the tab toggle.
 * @property {string}                    _storageKey                   - The key used for storage.
 * @property {boolean}                   _shouldStore                  - A flag to check if the component should be stored in the StorageManager.
 * @property {string}                    _id                           - The main ID of the tab toggle.
 * @property {boolean}                   _valid                        - The validity state of the tab toggle.
 * @property {boolean}                   _initialized                  - The initialized state of the tab toggle.
 * @property {string[]}                  _errors                       - The errors found throughout the tab toggle.
 */
class TabToggle extends Component {
  _rootDOMElement = "toggle";
  _protectedDOMElements = ["content"];
  _storageKey = "tabToggles";
  _name = "TabToggle";
  _shouldStore = false;
  _active = new TransactionalValue(false);

  /**
   * Constructs a new TabToggle.
   *
   * @param {object}      [options = {}]         - The options for generating the tab toggle.
   * @param {HTMLElement} options.toggleElement  - The tab toggle DOM element.
   * @param {HTMLElement} options.contentElement - The tab content DOM element.
   * @param {Tabs}        options.parentTab      - The Tabs element the toggle belongs to.
   */
  constructor({ toggleElement, contentElement, parentTab } = {}) {
    super({
      prefix: parentTab.prefix,
      key: parentTab.key,
    });

    // Set DOM elements.
    this._dom.toggle = toggleElement;
    this._dom.content = contentElement;

    // Set the parent tab instance.
    this._elements.parent = parentTab;

    // Register custom events.
    this._registerEvent("activate", {
      detail: {
        toggle: this,
      },
    });
    this._registerEvent("deactivate", {
      detail: {
        toggle: this,
      },
    });

    // Set up custom initialization.
    this._addEventListener(
      "grauplComponentInitialize",
      this.rootDOMElement,
      () => {
        // Automatically show or hide the tab toggle based on its aria-selected attribute.
        if (this.dom.toggle.getAttribute("aria-selected") === "true") {
          this.show({ force: true, emit: false, transition: false });
        } else {
          this.hide({ force: true, emit: false, transition: false });
        }
      }
    );
  }

  /**
   * The active state of the tab toggle.
   *
   * @readonly
   *
   * @type {TransactionalValue}
   *
   * @see _active
   */
  get isActive() {
    return this._active.value;
  }

  /**
   * Sets the IDs of the tab toggle and its content if they do not already exist.
   *
   * The generated IDs use the following format:
   *   - toggle: `tab-toggle-${key}-${index}`
   *   - content: `tab-content-${key}-${index}`
   *
   * Where `${key}` is the parent's key and `${index}` is the toggles index in the list of the parent's toggles.
   *
   * @protected
   */
  _setIds() {
    // Get the required information for IDs.
    const { key } = this.elements.parent;
    const index = this.elements.parent.dom.tabToggles.indexOf(this.dom.toggle);

    this.dom.toggle.id = this.dom.toggle.id || `tab-toggle-${key}-${index}`;
    this.dom.content.id = this.dom.content.id || `tab-content-${key}-${index}`;

    this._id = this.dom.toggle.id;
  }

  /**
   * Sets the ARIA attributes on the tab toggle and its content.
   */
  _setAriaAttributes() {
    // Set the ARIA attributes for the tab item toggle.
    this.dom.toggle.setAttribute("role", "tab");

    // If aria-selected is not explicitly set to "true", then set it to "false".
    if (this.dom.toggle.getAttribute("aria-selected") !== "true") {
      this.dom.toggle.setAttribute("aria-selected", "false");
    }

    // Set the aria-controls attribute for the toggle.
    this.dom.toggle.setAttribute("aria-controls", this.dom.content.id);

    // Set the role for the content.
    this.dom.content.setAttribute("role", "tabpanel");
  }

  /**
   * Reveal the toggle.
   *
   * Sets the toggle's `aria-selected` to "true", adds the
   * open class to the content, and removes the closed class from the content.
   *
   * @protected
   *
   * @fires grauplTabToggleActivate
   *
   * @param {Object<boolean>} [options = {}]              - Options for revealing the toggle.
   * @param {boolean}         [options.emit = true]       - Emit the activate event once revealed.
   * @param {boolean}         [options.transition = true] - Respect the transition class.
   */
  _reveal({ emit = true, transition = true } = {}) {
    const { closeClass, openClass, transitionClass, openDuration } =
      this.elements.parent;

    // Set aria-selected to true when showing the tab toggle.
    this.dom.toggle.setAttribute("aria-selected", "true");

    // If we're dealing with transition classes, then we need to utilize
    // requestAnimationFrame to add the transition class, remove the hide class,
    // add the show class, and finally remove the transition class.
    //
    // If `transition` is false, then it doesn't matter if the transition class
    // is set. Do not use the transition.
    if (transition && transitionClass !== "") {
      addClass(transitionClass, this.dom.content);

      requestAnimationFrame(() => {
        removeClass(closeClass, this.dom.content);

        requestAnimationFrame(() => {
          addClass(openClass, this.dom.content);

          requestAnimationFrame(() => {
            this._setTimeout(
              () => removeClass(transitionClass, this.dom.content),
              openDuration
            );
          });
        });
      });
    } else {
      // Add the show class
      addClass(openClass, this.dom.content);

      // Remove the hide class.
      removeClass(closeClass, this.dom.content);
    }

    if (emit) {
      this._dispatchEvent("activate", this.dom.toggle);
    }
  }

  /**
   * Conceals the toggle.
   *
   * Sets the toggle's `aria-expanded` to "false", adds the
   * close class to the content, and removes the open class from the content.
   *
   * @protected
   *
   * @fires grauplTabToggleDeactivate
   *
   * @param {Object<boolean>} [options = {}]              - Options for concealing the toggle.
   * @param {boolean}         [options.emit = true]       - Emit the deactivate event once concealed.
   * @param {boolean}         [options.transition = true] - Respect the transition class.
   */
  _conceal({ emit = true, transition = true } = {}) {
    const { closeClass, openClass, transitionClass, closeDuration } =
      this.elements.parent;

    // Set aria-selected to false when hiding the tab toggle.
    this.dom.toggle.setAttribute("aria-selected", "false");

    // If we're dealing with transition classes, then we need to utilize
    // requestAnimationFrame to add the transition class, remove the show class,
    // add the hide class, and finally remove the transition class.
    //
    // If `transition` is false, then it doesn't matter if the transition class
    // is set. Do not use the transition.
    if (transition && transitionClass !== "") {
      addClass(transitionClass, this.dom.content);

      requestAnimationFrame(() => {
        removeClass(openClass, this.dom.content);

        requestAnimationFrame(() => {
          addClass(closeClass, this.dom.content);

          requestAnimationFrame(() => {
            this._setTimeout(
              () => removeClass(transitionClass, this.dom.content),
              closeDuration
            );
          });
        });
      });
    } else {
      // Add the hide class
      addClass(closeClass, this.dom.content);

      // Remove the show class.
      removeClass(openClass, this.dom.content);
    }

    if (emit) {
      this._dispatchEvent("deactivate", this.dom.toggle);
    }
  }

  /**
   * Shows the tab toggle's content.
   *
   * @param {Object<boolean>} [options = {}]                  - The options for showing the tab toggle.
   * @param {boolean}         [options.force = false]         - Whether to force the open action.
   * @param {boolean}         [options.preserveState = false] - Whether to preserve the open state.
   * @param {boolean}         [options.emit = true]           - Emit the deactivate event once revealed.
   * @param {boolean}         [options.transition = true]     - Respect the transition class.
   */
  show({
    force = false,
    preserveState = false,
    emit = true,
    transition = true,
  } = {}) {
    if (this.isActive && !force) return;

    // Set the focus state of the parent tabs element.
    this.elements.parent.focusState = "self";

    // Reveal the toggle.
    this._reveal({ emit, transition });

    // Set the active state
    this._active.value = true;

    if (!preserveState) {
      this._active.commit();
    }

    // Set the tabindex to 0 so it can be focused.
    this.dom.toggle.setAttribute("tabindex", "0");

    // Hide all sibling tab toggles.
    this.hideSiblings();
  }

  /**
   * Hides the tab toggle's content.
   *
   * @param {Object<boolean>} [options = {}]                  - The options for hiding the tab toggle.
   * @param {boolean}         [options.force = false]         - Whether to force the hide action.
   * @param {boolean}         [options.preserveState = false] - Whether to preserve the open state.
   * @param {boolean}         [options.emit = true]           - Emit the deactivate event once concealed.
   * @param {boolean}         [options.transition = true]     - Respect the transition class.
   */
  hide({
    force = false,
    preserveState = false,
    emit = true,
    transition = true,
  } = {}) {
    if (!this.isActive && !force) return;

    // Set the focus state of the parent tabs element.
    this.elements.parent.focusState = "none";

    // Conceal the toggle.
    this._conceal({ emit, transition });

    // Set the active state
    this._active.value = false;

    if (!preserveState) {
      this._active.commit();
    }

    // Set the tabindex to -1.
    this.dom.toggle.setAttribute("tabindex", "-1");
  }

  /**
   * Focuses the tab toggle.
   */
  focus() {
    this.dom.toggle.focus();
  }

  /**
   * Blurs the tab toggle.
   */
  blur() {
    this.dom.toggle.blur();
  }

  /**
   * Hides all sibling toggles within the same Tabs element.
   */
  hideSiblings() {
    if (this.elements.parent) {
      this.elements.parent.elements.tabToggles.forEach((toggle) => {
        if (toggle !== this) {
          toggle.hide();
        }
      });
    }
  }
}

export default TabToggle;
