/**
 * @file
 * The Tooltip class.
 */

import { isValidClassList, isValidType } from "../validate.js";
import { addClass, removeClass } from "../domHelpers.js";
import { keyPress, preventEvent } from "../eventHandlers.js";
import TransactionalValue from "../TransactionalValue.js";
import Component from "../Component.js";

/**
 * @event grauplTooltipShow
 * Fired when the tooltip is shown.
 *
 * @type {CustomEvent}
 *
 * @property {boolean}         bubbles      - Whether the event bubbles.
 * @property {Object<Tooltip>} detail       - The detail object.
 * @property {Tooltip}         detail.tooltip - The tooltip that was shown.
 */

/**
 * @event grauplTooltipHide
 * Fired when the tooltip is hidden.
 *
 * @type {CustomEvent}
 *
 * @property {boolean}         bubbles      - Whether the event bubbles.
 * @property {Object<Tooltip>} detail       - The detail object.
 * @property {Tooltip}         detail.tooltip - The tooltip that was hidden.
 */

/**
 * The Tooltip component.
 *
 * @extends Component
 *
 * Protected fields are documented below.
 *
 * @property {Object<HTMLElement>}         _dom                         - The DOM elements within the tooltip.
 * @property {HTMLElement}                 _dom.tooltip                  - The tooltip element.
 * @property {HTMLElement}                 _dom.tooltipButton              - The tooltip button element.
 * @property {string}                      _rootDOMElement              - The root DOM element of the tooltip.
 * @property {string[]}                    _protectedDOMElements        - The DOM elements within the tooltip that cannot be reset or generated by the tooltip itself.
 * @property {Object<string, string[]>}    _classes                     - The CSS classes to apply when the tooltip is in various states.
 * @property {string|string[]}             _classes.show                - The class(es) to apply when the tooltip is shown.
 * @property {string|string[]}             _classes.hide                - The class(es) to apply when the tooltip is hidden.
 * @property {string|string[]}             _classes.transition          - The class(es) to apply when the tooltip is transitioning between states.
 * @property {string|string[]}             _classes.initialize          - The class(es) to apply when the tooltip is initializing.
 * @property {Object<number>}              _durations                   - The duration times (in milliseconds) for various aspects throughout the tooltip.
 * @property {number}                      _durations.transition        - The duration time (in milliseconds) for the transition between shown and hidden states.
 * @property {number}                      _durations.show              - The duration time (in milliseconds) for the transition from hidden to shown states.
 * @property {number}                      _durations.hide              - The duration time (in milliseconds) for the transition from shown to hidden states.
 * @property {TransactionalValue<boolean>} _hidden                      - The hidden state of the tooltip.
 * @property {Object<CustomEvent>}         _events                      - Custom events that can be triggered throughout the tooltip.
 * @property {grauplTooltipShow}           _events.show                 - The event triggered when the tooltip is shown.
 * @property {grauplTooltipHide}           _events.hide                 - The event triggered when the tooltip is hidden.
 * @property {string}                      _storageKey                  - The key used for storage.
 * @property {boolean}                     _shouldStore                 - A flag to check if the component should be stored in the StorageManager.
 * @property {Object<string>}              _selectors                   - The query selectors used by the tooltip.
 * @property {Object<Tooltip>}             _elements                    - The instantiated elements within the tooltip.
 * @property {Object<number>}              _delays                      - The delay times (in milliseconds) for various aspects throughout the tooltip.
 * @property {string}                      _focusState                  - The current state of the tooltip's focus.
 * @property {string}                      _currentEvent                - The last type of event triggered within the tooltip.
 * @property {string}                      _breakpoint                  - The breakpoint that the tooltip will call media query list events.
 * @property {string}                      _mediaQueryString            - The media query to use to trigger media query list events.
 * @property {MediaQueryList|null}         _mediaQueryList              - The MediaQueryList for the tooltip.
 * @property {Function}                    _mediaQueryListEventCallback - The callback for media query list events.
 * @property {Object<Function>}            _intervals                   - Intervals throughout the tooltip.
 * @property {Object<Function>}            _timeouts                    - Timeouts throughout the tooltip.
 * @property {object[]}                    _listeners                   - Event listeners throughout the tooltip.
 * @property {string}                      _prefix                      - The prefix used for CSS custom properties and attributes.
 * @property {string}                      _key                         - The key used to generate IDs throughout the tooltip.
 * @property {string}                      _name                        - The component name of the tooltip.
 * @property {string}                      _id                          - The main ID of the tooltip.
 * @property {boolean}                     _valid                       - The validity state of the tooltip.
 * @property {boolean}                     _initialized                 - The initialized state of the tooltip.
 * @property {string[]}                    _errors                      - The errors found throughout the tooltip.
 */
console.log("hello");

class Tooltip extends Component {
  _rootDOMElement = "tooltip";
  _protectedDOMElements = ["button"];
  _hidden = new TransactionalValue(false);
  _storageKey = "tooltips";
  _name = "Tooltip";

  /**
   * Constructs a new `Tooltip`.
   *
   * @param {object}               [options = {}]                            - The options object.
   * @param {HTMLElement}          options.tooltipElement                      - The tooltip element.
   * @param {?HTMLElement}         [options.tooltipButtonElement = null]        - The button element.
   * @param {string|string[]|null} [options.showClass = show]                - The class(es) to apply when the tooltip is shown.
   * @param {string|string[]|null} [options.hideClass = hide]                - The class(es) to apply when the tooltip is hidden.
   * @param {string|string[]|null} [options.transitionClass = transitioning] - The class(es) to apply when the tooltip is transitioning between states.
   * @param {number}               [options.transitionDuration = 150]        - The duration of the transition between "shown" and "hidden" states (in milliseconds).
   * @param {boolean}              [options.showDuration = -1]               - The duration of the transition from "hidden" to "shown" states (in milliseconds).
   * @param {boolean}              [options.hideDuration = -1]               - The duration of the transition from "shown" to "hidden" states (in milliseconds).
   * @param {boolean}              [options.isHidden = false]                - A flag to determine the initial state of the tooltip.
   * @param {?string}              [options.prefix = graupl-]                - The prefix used for CSS custom properties and attributes.
   * @param {?string}              [options.key = null]                      - The key used to generate IDs throughout the tooltip.
   * @param {?(string|string[])}   [options.initializeClass = initializing]  - The class(es) to apply when the tooltip is initializing.
   * @param {boolean}              [options.initialize = false]              - A flag to initialize the tooltip immediately upon creation.
   */
  constructor({
    tooltipElement,
    tooltipButtonElement = ".tooltip-button",
    showClass = "show",
    hideClass = "hide",
    transitionClass = "transitioning",
    transitionDuration = 150,
    showDuration = -1,
    hideDuration = -1,
    isHidden = false,
    prefix = "graupl-",
    key = null,
    initializeClass = "initializing",
    initialize = false,
  } = {}) {
    super({
      prefix,
      key,
      initializeClass,
    });

    console.log(tooltipButtonElement);

    // Set the DOM elements.
    this._dom.tooltip = tooltipElement;
    this._dom.tooltipButton = tooltipButtonElement;

    // Set the classes.
    this._classes.show = showClass || "";
    this._classes.hide = hideClass || "";
    this._classes.transition = transitionClass || "";

    // Set the durations.
    this._durations.transition = transitionDuration;
    this._durations.show = showDuration;
    this._durations.hide = hideDuration;

    // Set hidden.
    this._hidden.value = isHidden;
    this._hidden.commit();

    // Register custom events.
    this._registerEvent("show", {
      detail: {
        tooltip: this,
      },
    });
    this._registerEvent("hide", {
      detail: {
        tooltip: this,
      },
    });

    // Set up custom initialization.
    this._addEventListener(
      "grauplComponentInitialize",
      this.rootDOMElement,
      () => {
        // Handle hiding the tooltip by default.
        if (this.isHidden) {
          this._conceal({ emit: false, transition: false });
        }
      }
    );

    // Set up custom validation.
    this._addEventListener(
      "grauplComponentValidate",
      this.rootDOMElement,
      () => {
        // Boolean checks.
        const booleans = {
          isHidden: this._hidden.value,
        };

        // Check the booleans.
        const booleanChecks = isValidType("boolean", booleans, {
          shouldThrow: false,
        });

        // Handle boolean check failure.
        if (!booleanChecks.status) {
          this._errors = [...this._errors, ...booleanChecks.errors];
          this._valid = false;
        }
      }
    );

    if (initialize) {
      this.initialize();
    }
  }

  /**
   * The class to use to show the tooltip.
   *
   * @type {string|string[]}
   *
   * @see _classes.show
   */
  get showClass() {
    return this._classes.show;
  }

  set showClass(value) {
    isValidClassList({ showClass: value });

    if (this._classes.show !== value) {
      this._classes.show = value;
    }
  }

  /**
   * The class to use to hide the tooltip.
   *
   * @type {string|string[]}
   *
   * @see _classes.hide
   */
  get hideClass() {
    return this._classes.hide;
  }

  set hideClass(value) {
    isValidClassList({ hideClass: value });

    if (this._classes.hide !== value) {
      this._classes.hide = value;
    }
  }

  /**
   * The class to use when transitioning the tooltip.
   *
   * @type {string|string[]}
   *
   * @see _classes.transition
   */
  get transitionClass() {
    return this._classes.transition;
  }

  set transitionClass(value) {
    isValidClassList({ transitionClass: value });

    if (this._classes.transition !== value) {
      this._classes.transition = value;
    }
  }

  /**
   * The time in milliseconds the transition will take.
   *
   * @type {number}
   *
   * @see _durations.transition
   */
  get transitionDuration() {
    return this._durations.transition;
  }

  set transitionDuration(value) {
    isValidType("number", { transitionDuration: value });

    if (this._durations.transition !== value) {
      this._durations.transition = value;
      this._setCustomProps();
    }
  }

  /**
   * The duration time (in milliseconds) for the transition from hidden to shown states.
   *
   * If showDuration is set to -1, the transitionDuration value will be used instead.
   *
   * Setting this value will also set the --graupl-show-transition-duration CSS custom property on the tooltip.
   *
   * @type {number}
   *
   * @see _durations.show
   */
  get showDuration() {
    if (this._durations.show === -1) return this.transitionDuration;

    return this._durations.show;
  }

  set showDuration(value) {
    isValidType("number", { showDuration: value });

    if (this._durations.show !== value) {
      this._durations.show = value;
      this._setCustomProps();
    }
  }

  /**
   * The duration time (in milliseconds) for the transition from shown to hidden states.
   *
   * If hideDuration is set to -1, the transitionDuration value will be used instead.
   *
   * Setting this value will also set the --graupl-close-transition-duration CSS custom property on the tooltip.
   *
   * @type {number}
   *
   * @see _durations.hide
   */
  get hideDuration() {
    if (this._durations.hide === -1) return this.transitionDuration;

    return this._durations.hide;
  }

  set hideDuration(value) {
    isValidType("number", { hideDuration: value });

    if (this._durations.hide !== value) {
      this._durations.hide = value;
      this._setCustomProps();
    }
  }

  /**
   * The hidden state of the tooltip.
   *
   * @readonly
   *
   * @type {boolean}
   *
   * @see _hidden
   */
  get isHidden() {
    return this._hidden.value;
  }

  /**
   * Sets the IDs of the tooltip and its children if they do not already exist.
   *
   * The generated IDs use the key and follow the format:
   *  - tooltip: `tooltip-${key}`
   *  - button: `tooltip-button-${key}`
   */
  _setIds() {
    this.dom.tooltip.id = this.dom.tooltip.id || `tooltip-${this.key}`;
    this.dom.tooltipButton.id =
      this.dom.tooltipButton.id || `tooltip-button-${this.key}`;

    this._id = this.dom.tooltip.id;
  }

  /**
   * Reveals the tooltip.
   *
   * Adds the show class and removes the hide class from the tooltip.
   *
   * @protected
   *
   * @fires grauplTooltipShow
   *
   * @param {Object<boolean>} [options = {}]              - Options for revealing the tooltip.
   * @param {boolean}         [options.emit = true]       - Emit the show event once revealed.
   * @param {boolean}         [options.transition = true] - Respect the transition class.
   */
  _reveal({ emit = true, transition = true } = {}) {
    // If we're dealing with transition classes, then we need to utilize
    // requestAnimationFrame to add the transition class, remove the hide class,
    // add the show class, and finally remove the transition class.
    if (transition && this.transitionClass !== "") {
      addClass(this.transitionClass, this.dom.tooltip);

      requestAnimationFrame(() => {
        removeClass(this.hideClass, this.dom.tooltip);

        requestAnimationFrame(() => {
          addClass(this.showClass, this.dom.tooltip);

          requestAnimationFrame(() => {
            this._setTimeout(
              () => removeClass(this.transitionClass, this.dom.tooltip),
              this.showDuration
            );
          });
        });
      });
    } else {
      // Add the show class
      addClass(this.showClass, this.dom.tooltip);

      // Remove the hide class.
      removeClass(this.hideClass, this.dom.tooltip);
    }

    this.dom.tooltip.removeAttribute("inert");

    if (emit) {
      this._dispatchEvent("show", this.dom.tooltip);
    }
  }

  /**
   * Conceals the tooltip.
   *
   * Adds the hide class and removes the show class from the tooltip.
   *
   * @protected
   *
   * @fires grauplTooltipHide
   *
   * @param {Object<boolean>} [options = {}]              - Options for concealing the tooltip.
   * @param {boolean}         [options.emit = true]       - Emit the show event once concealed.
   * @param {boolean}         [options.transition = true] - Respect the transition class.
   */
  _conceal({ emit = true, transition = true } = {}) {
    // If we're dealing with transition classes, then we need to utilize
    // requestAnimationFrame to add the transition class, remove the show class,
    // add the hide class, and finally remove the transition class.
    if (transition && this.transitionClass !== "") {
      addClass(this.transitionClass, this.dom.tooltip);

      requestAnimationFrame(() => {
        removeClass(this.showClass, this.dom.tooltip);

        requestAnimationFrame(() => {
          addClass(this.hideClass, this.dom.tooltip);

          requestAnimationFrame(() => {
            this._setTimeout(
              () => removeClass(this.transitionClass, this.dom.tooltip),
              this.hideDuration
            );
          });
        });
      });
    } else {
      // Add the hide class
      addClass(this.hideClass, this.dom.tooltip);

      // Remove the show class.
      removeClass(this.showClass, this.dom.tooltip);
    }

    this.dom.tooltip.setAttribute("inert", "true");

    if (emit) {
      this._dispatchEvent("hide", this.dom.tooltip);
    }
  }

  /**
   * Sets custom props throughout the tooltip.
   *
   * The custom properties are:
   *   - `--graupl-tooltip-transition-duration`,
   *   - `--graupl-tooltip-show-transition-duration`, and
   *   - `--graupl-tooltip-hide-transition-duration`.
   *
   * The prefix of `graupl-` can be changed by setting the tooltip's prefix value.
   *
   * @protected
   */
  _setCustomProps() {
    this.dom.tooltip.style.setProperty(
      `--${this.prefix}tooltip-transition-duration`,
      `${this.transitionDuration}ms`
    );

    this.dom.tooltip.style.setProperty(
      `--${this.prefix}tooltip-show-transition-duration`,
      `${this.showDuration}ms`
    );

    this.dom.tooltip.style.setProperty(
      `--${this.prefix}tooltip-hide-transition-duration`,
      `${this.hideDuration}ms`
    );
  }

  /**
   * Handles click events throughout the tooltip for proper use.
   *
   * - Adds a `click` listener to the button that will hide the tooltip.
   *
   * @protected
   */
  _handleClick() {
    if (this.dom.tooltipButton === null) {
      return;
    }

    this._addEventListener("click", this.dom.tooltipButton, () => this.hide());
  }

  /**
   * Handles keydown events throughout the tooltip for proper use.
   *
   * This method exists to assist the _handleKeyup method.
   *
   * - Adds a `keydown` listener to the button (if it exists).
   *   - Blocks propagation on "Space" and "Enter" keys.
   */
  _handleKeydown() {
    if (this.dom.tooltipButton === null) {
      return;
    }

    this._addEventListener("keydown", this.dom.tooltipButton, (event) => {
      const key = keyPress(event);

      // Prevent default behavior for space and enter keys.
      if (key === "Space" || key === "Enter") {
        preventEvent(event);
      }
    });
  }

  /**
   * Handles keyup events throughout the tooltip for proper use.
   *
   * - Adds a `keyup` listener to the button (if it exists).
   *   - Hides the tooltip when the user hits "Space" or "Enter".
   */
  _handleKeyup() {
    if (this.dom.tooltipButton === null) {
      return;
    }

    this._addEventListener("keyup", this.dom.tooltipButton, (event) => {
      const key = keyPress(event);

      if (key === "Space" || key === "Enter") {
        this.hide();
      }
    });
  }

  /**
   * Handles the hover events throughout the tooltip for proper use.
   *
   * - Adds a `pointerover` listener to the tooltip to pause autoplay.
   * - Adds a `pointerleave` listener to the tooltip to resume autoplay.
   */
  _handleHover() {
    // Pause autoplay when anything in the tooltip is hovered.
    this._addEventListener("pointerover", this.dom.tooltip, () => {
      if (this.autoplay) {
        this._clearInterval();
      }
    });

    this._addEventListener("pointerleave", this.dom.tooltip, () => {
      if (this.autoplay) {
        this._setInterval(() => this.activateNextItem(), this.transitionDelay);
      }
    });
  }

  /**
   * Shows the tooltip.
   *
   * Sets the tooltip's focus state to "self", calls reveal, and sets isHidden to `false`.
   *
   * @param {Object<boolean>} [options = {}]                  - Options for showing the tooltip.
   * @param {boolean}         [options.force = false]         - Whether to force the show action.
   * @param {boolean}         [options.preserveState = false] - Whether to preserve the hidden state.
   */
  show({ force = false, preserveState = false } = {}) {
    if (!this.isHidden && !force) return;

    // Set the focus state.
    this.focusState = "self";

    // Reveal the tooltip.
    this._reveal();

    // Set the hidden state.
    this._hidden.value = false;

    if (!preserveState) {
      this._hidden.commit();
    }
  }

  /**
   * Hides the tooltip.
   *
   * Sets the tooltip's focus state to "none", calls conceal, and sets isHidden to `true`.
   *
   * @param {Object<boolean>} [options = {}]                  - Options for hiding the tooltip.
   * @param {boolean}         [options.force = false]         - Whether to force the hide action.
   * @param {boolean}         [options.preserveState = false] - Whether to preserve the hidden state.
   */
  hide({ force = false, preserveState = false } = {}) {
    if (this.isHidden && !force) return;

    // Set the focus state.
    this.focusState = "none";

    // Conceal the tooltip.
    this._conceal();

    // Set the hidden state.
    this._hidden.value = true;

    if (!preserveState) {
      this._hidden.commit();
    }
  }
}

export default Tooltip;
