/**
 * @file
 * The Disclosure class.
 */

import { isValidClassList, isValidType, isTag } from "../validate.js";
import { addClass, removeClass } from "../domHelpers.js";
import { keyPress, preventEvent } from "../eventHandlers.js";
import TransactionalValue from "../TransactionalValue.js";
import Component from "../Component.js";

/**
 * The event that is triggered when the disclosure is shown.
 *
 * @event grauplDisclosureExpand
 *
 * @type {CustomEvent}
 *
 * @property {boolean}            bubbles           - A flag to bubble the event
 * @property {Object<Disclosure>} detail            - The details object containing the disclosure itself.
 * @property {Disclosure}         detail.disclosure - The disclosure.
 */

/**
 * The event that is triggered when the disclosure is hidden.
 *
 * @event grauplDisclosureCollapse
 *
 * @type {CustomEvent}
 *
 * @property {boolean}            bubbles           - A flag to bubble the event
 * @property {Object<Disclosure>} detail            - The details object containing the disclosure itself.
 * @property {Disclosure}         detail.disclosure - The disclosure.
 */

/**
 * The event that is triggered when the disclosure is locked.
 *
 * @event grauplDisclosureLock
 *
 * @type {CustomEvent}
 *
 * @property {boolean}            bubbles           - A flag to bubble the event
 * @property {Object<Disclosure>} detail            - The details object containing the disclosure itself.
 * @property {Disclosure}         detail.disclosure - The disclosure.
 */

/**
 * The event that is triggered when the disclosure is unlocked.
 *
 * @event grauplDisclosureUnlock
 *
 * @type {CustomEvent}
 *
 * @property {boolean}            bubbles           - A flag to bubble the event
 * @property {Object<Disclosure>} detail            - The details object containing the disclosure itself.
 * @property {Disclosure}         detail.disclosure - The disclosure.
 */

/**
 * The Disclosure component.
 *
 * @extends Component
 *
 * Protected fields are documented below.
 *
 * @property {Object<HTMLElement>}         _dom                         - The DOM elements within the disclosure.
 * @property {HTMLElement}                 _dom.controller              - The disclosure controller element.
 * @property {HTMLElement}                 _dom.disclosure              - The disclosure element.
 * @property {HTMLElement}                 _dom.content                 - The disclosure content element.
 * @property {string}                      _rootDOMElement              - The root DOM element of the disclosure.
 * @property {string[]}                    _protectedDOMElements        - The DOM elements within the disclosure that cannot be reset or generated by the disclosure itself.
 * @property {Object<string>}              _selectors                   - The query selectors used by the disclosure.
 * @property {string}                      _selectors.content           - The query selector for the disclosure content.
 * @property {Object<string, string[]>}    _classes                     - The CSS classes to apply when the disclosure is in various states.
 * @property {string|string[]}             _classes.locked              - The class(es) to apply when the disclosure is locked.
 * @property {string|string[]}             _classes.unlocked            - The class(es) to apply when the disclosure is unlocked.
 * @property {string|string[]}             _classes.open                - The class(es) to apply when the disclosure is open.
 * @property {string|string[]}             _classes.close               - The class(es) to apply when the disclosure is closed.
 * @property {string|string[]}             _classes.transition          - The class(es) to apply when the disclosure is transitioning between states.
 * @property {string|string[]}             _classes.initialize          - The class(es) to apply when the disclosure is initializing.
 * @property {Object<number>}              _durations                   - The duration times (in milliseconds) for various aspects throughout the disclosure.
 * @property {number}                      _durations.transition        - The duration time (in milliseconds) for the transition between open and closed states.
 * @property {number}                      _durations.open              - The duration time (in milliseconds) for the transition from closed to open states.
 * @property {number}                      _durations.close             - The duration time (in milliseconds) for the transition from open to closed states.
 * @property {TransactionalValue<boolean>} _open                        - The open state of the disclosure.
 * @property {boolean}                     _openInsideBreakpoint        - A flag to open the disclosure when inside the breakpoint.
 * @property {boolean}                     _openOutsideBreakpoint       - A flag to open the disclosure when outside the breakpoint.
 * @property {boolean}                     _closeInsideBreakpoint       - A flag to close the disclosure when inside the breakpoint.
 * @property {boolean}                     _closeOutsideBreakpoint      - A flag to close the disclosure when outside the breakpoint.
 * @property {boolean}                     _lockInsideBreakpoint        - A flag to lock the disclosure in its current state when inside the breakpoint.
 * @property {boolean}                     _lockOutsideBreakpoint       - A flag to lock the disclosure in its current state when outside the breakpoint.
 * @property {boolean}                     _unlockInsideBreakpoint      - A flag to unlock the disclosure when inside the breakpoint.
 * @property {boolean}                     _unlockOutsideBreakpoint     - A flag to unlock the disclosure when outside the breakpoint.
 * @property {TransactionalValue<boolean>} _locked                      - The locked state of the disclosure.
 * @property {boolean}                     _closeOnBlur                 - Whether to close the disclosure when it loses focus in the DOM.
 * @property {Function}                    _mediaQueryListEventCallback - The callback for media query list events.
 * @property {string}                      _storageKey                  - The key used for storage.
 * @property {boolean}                     _shouldStore                 - A flag to check if the component should be stored in the StorageManager.
 * @property {Object<CustomEvent>}         _events                      - Custom events that can be triggered throughout the disclosure.
 * @property {grauplDisclosureExpand}      _events.expand               - The event triggered when the disclosure is expanded.
 * @property {grauplDisclosureCollapse}    _events.collapse             - The event triggered when the disclosure is collapsed.
 * @property {grauplDisclosureLock}        _events.lock                 - The event triggered when the disclosure is locked.
 * @property {grauplDisclosureUnlock}      _events.unlock               - The event triggered when the disclosure is unlocked.
 * @property {Object<object>}              _elements                    - The instantiated elements within the disclosure.
 * @property {Object<number>}              _delays                      - The delay times (in milliseconds) for various aspects throughout the disclosure.
 * @property {string}                      _focusState                  - The current state of the disclosure's focus.
 * @property {string}                      _currentEvent                - The last type of event triggered within the disclosure.
 * @property {string}                      _breakpoint                  - The breakpoint that the disclosure will call media query list events.
 * @property {string}                      _mediaQueryString            - The media query to use to trigger media query list events.
 * @property {MediaQueryList|null}         _mediaQueryList              - The MediaQueryList for the disclosure.
 * @property {Object<Function>}            _intervals                   - Intervals throughout the disclosure.
 * @property {Object<Function>}            _timeouts                    - Timeouts throughout the disclosure.
 * @property {object[]}                    _listeners                   - Event listeners throughout the disclosure.
 * @property {string}                      _prefix                      - The prefix used for CSS custom properties and attributes.
 * @property {string}                      _key                         - The key used to generate IDs throughout the disclosure.
 * @property {string}                      _name                        - The component name of the disclosure.
 * @property {string}                      _id                          - The main ID of the disclosure.
 * @property {boolean}                     _valid                       - The validity state of the disclosure.
 * @property {boolean}                     _initialized                 - The initialized state of the disclosure.
 * @property {string[]}                    _errors                      - The errors found throughout the disclosure.
 */
class Disclosure extends Component {
  _rootDOMElement = "disclosure";
  _protectedDOMElements = ["controller"];
  _open = new TransactionalValue(false);
  _openInsideBreakpoint = false;
  _openOutsideBreakpoint = false;
  _closeInsideBreakpoint = false;
  _closeOutsideBreakpoint = false;
  _lockInsideBreakpoint = false;
  _lockOutsideBreakpoint = false;
  _unlockInsideBreakpoint = false;
  _unlockOutsideBreakpoint = false;
  _locked = new TransactionalValue(false);
  _shouldOpen = false;
  _closeOnBlur = false;
  _storageKey = "disclosures";
  _name = "Disclosure";
  _mediaQueryListEventCallback = (event) => {
    if (event.matches) {
      if (this.unlockInsideBreakpoint) {
        this.unlock();
      }

      if (this.isOpen && this.closeInsideBreakpoint) {
        if (this.isLocked) {
          this.unlock();
        }
        this.close({ preserveState: true });
      } else if (!this.isOpen && this.openInsideBreakpoint) {
        if (this.isLocked) {
          this.unlock();
        }
        this.open();
      }

      if (this.lockInsideBreakpoint) {
        this.lock();
      }
    } else {
      if (this.unlockOutsideBreakpoint) {
        this.unlock();
      }

      if (this.isOpen && this.closeOutsideBreakpoint) {
        if (this.isLocked) {
          this.unlock();
        }
        this.close({ preserveState: true });
      } else if (!this.isOpen && this.openOutsideBreakpoint) {
        if (this.isLocked) {
          this.unlock();
        }
        this.open();
      }

      if (this.lockOutsideBreakpoint) {
        this.lock();
      }
    }
  };

  /**
   * Constructs a new `Disclosure`.
   *
   * @param {object}             [options = {}]                                            - The options for generating the disclosure.
   * @param {HTMLElement}        options.disclosureElement                                 - The disclosure element in the DOM.
   * @param {HTMLElement}        options.controllerElement                                 - The disclosure toggle element in the DOM.
   * @param {string}             [options.disclosureContentSelector = .disclosure-content] - The query selector string for the disclosure content.
   * @param {?(string|string[])} [options.lockedClass = locked]                            - The class(es) to apply when the disclosure is locked.
   * @param {?(string|string[])} [options.unlockedClass = unlocked]                        - The class(es) to apply when the disclosure is unlocked.
   * @param {?(string|string[])} [options.openClass = show]                                - The class to apply when a disclosure is "open".
   * @param {?(string|string[])} [options.closeClass = hide]                               - The class to apply when a disclosure is "closed".
   * @param {?(string|string[])} [options.transitionClass = transitioning]                 - The class to apply when a disclosure is transitioning between "open" and "closed" states.
   * @param {number}             [options.transitionDuration = 250]                        - The duration of the transition between "open" and "closed" states (in milliseconds).
   * @param {boolean}            [options.openDuration = -1]                               - The duration of the transition from "closed" to "open" states (in milliseconds).
   * @param {boolean}            [options.closeDuration = -1]                              - The duration of the transition from "open" to "closed" states (in milliseconds).
   * @param {boolean}            [options.closeOnBlur = false]                             - Whether to close the disclosure when it loses focus in the dom.
   * @param {?string}            [options.minWidth = ""]                                   - The width of the screen that the disclosure will automatically open/close itself.
   * @param {boolean}            [options.autoOpen = false]                                - Whether to automatically open when above the minWidth.
   * @param {?string}            [options.breakpoint = ""]                                 - The breakpoint that the disclosure will automatically open/close itself.
   * @param {boolean}            [options.openInsideBreakpoint = false]                    - A flag to open the disclosure when inside the breakpoint.
   * @param {boolean}            [options.openOutsideBreakpoint = false]                   - A flag to open the disclosure when outside the breakpoint.
   * @param {boolean}            [options.closeInsideBreakpoint = false]                   - A flag to close the disclosure when inside the breakpoint.
   * @param {boolean}            [options.closeOutsideBreakpoint = false]                  - A flag to close the disclosure when outside the breakpoint.
   * @param {boolean}            [options.lockInsideBreakpoint = false]                    - A flag to lock the disclosure when inside the breakpoint.
   * @param {boolean}            [options.lockOutsideBreakpoint = false]                   - A flag to lock the disclosure when outside the breakpoint.
   * @param {boolean}            [options.unlockInsideBreakpoint = false]                  - A flag to unlock the disclosure when inside the breakpoint.
   * @param {boolean}            [options.unlockOutsideBreakpoint = false]                 - A flag to unlock the disclosure when outside the breakpoint.
   * @param {boolean}            [options.locked = false]                                  - A flag to lock the disclosure in its current state.
   * @param {?string}            [options.mediaQuery = ""]                                 - The media query to use when automatically opening/closing the disclosure.
   * @param {?string}            [options.prefix = graupl-]                                - The prefix used for CSS custom properties and attributes.
   * @param {?string}            [options.key = null]                                      - The key used to generate IDs throughout the disclosure.
   * @param {?(string|string[])} [options.initializeClass = initializing]                  - The class(es) to apply when the disclosure is initializing.
   * @param {boolean}            [options.initialize = false]                              - A flag to initialize the disclosure immediately upon creation.
   */
  constructor({
    disclosureElement,
    controllerElement,
    disclosureContentSelector = ".disclosure-content",
    lockedClass = "locked",
    unlockedClass = "unlocked",
    openClass = "show",
    closeClass = "hide",
    transitionClass = "transitioning",
    transitionDuration = 250,
    openDuration = -1,
    closeDuration = -1,
    closeOnBlur = false,
    minWidth = "",
    breakpoint = "",
    autoOpen = false,
    openInsideBreakpoint = false,
    openOutsideBreakpoint = false,
    closeInsideBreakpoint = false,
    closeOutsideBreakpoint = false,
    lockInsideBreakpoint = false,
    lockOutsideBreakpoint = false,
    unlockInsideBreakpoint = false,
    unlockOutsideBreakpoint = false,
    locked = false,
    mediaQuery = "",
    prefix = "graupl-",
    key = null,
    initializeClass = "initializing",
    initialize = false,
  } = {}) {
    super({
      prefix,
      key,
      initializeClass,
    });

    // Set the DOM elements.
    this._dom.disclosure = disclosureElement;
    this._dom.controller = controllerElement;

    // Set the DOM selectors.
    this._selectors.content = disclosureContentSelector;

    // Set the classes.
    this._classes.locked = lockedClass || "";
    this._classes.unlocked = unlockedClass || "";
    this._classes.open = openClass || "";
    this._classes.close = closeClass || "";
    this._classes.transition = transitionClass || "";

    // Set the durations.
    this._durations.transition = transitionDuration;
    this._durations.open = openDuration;
    this._durations.close = closeDuration;

    // Set close on blur.
    this._closeOnBlur = closeOnBlur;

    // @todo Remove minWidth and autoOpen options in favor of breakpoint, openInsideBreakpoint, openOutsideBreakpoint, closeInsideBreakpoint, and closeOutsideBreakpoint options.
    if (minWidth !== "") {
      console.warn(
        "`minWidth` is deprecated and will be removed in a future release. Please set `breakpoint` instead."
      );

      if (breakpoint === "") {
        breakpoint = minWidth;
      }
    }

    if (autoOpen && breakpoint !== "") {
      console.warn(
        "`autoOpen` is deprecated and will be removed in a future release. Please set `openOutsideBreakpoint` and `closeInsideBreakpoint` to `true` instead."
      );

      openOutsideBreakpoint = autoOpen;
      closeInsideBreakpoint = autoOpen;
    }

    // Set collapse width and auto open functionality.
    this._breakpoint = breakpoint || "";
    this._shouldOpen = autoOpen;
    this._openInsideBreakpoint = openInsideBreakpoint;
    this._openOutsideBreakpoint = openOutsideBreakpoint;
    this._closeInsideBreakpoint = closeInsideBreakpoint;
    this._closeOutsideBreakpoint = closeOutsideBreakpoint;
    this._lockInsideBreakpoint = lockInsideBreakpoint;
    this._lockOutsideBreakpoint = lockOutsideBreakpoint;
    this._unlockInsideBreakpoint = unlockInsideBreakpoint;
    this._unlockOutsideBreakpoint = unlockOutsideBreakpoint;
    this._mediaQueryString = mediaQuery || "";

    // Set the lock state.
    this._locked.value = locked;
    this._locked.commit();

    // Register custom events.
    this._registerEvent("expand", { detail: { disclosure: this } });
    this._registerEvent("collapse", { detail: { disclosure: this } });
    this._registerEvent("lock", { detail: { disclosure: this } });
    this._registerEvent("unlock", { detail: { disclosure: this } });

    // Set up custom initialization.
    this._addEventListener(
      "grauplComponentInitialize",
      this.rootDOMElement,
      () => {
        // Handle auto-opening disclosures with aria-expanded set to true or
        // those that _should_ open.
        if (
          this.dom.controller.getAttribute("aria-expanded") === "true" ||
          (this.openOutsideBreakpoint &&
            !window.matchMedia(this.mediaQuery).matches) ||
          (this.openInsideBreakpoint &&
            window.matchMedia(this.mediaQuery).matches)
        ) {
          this.open();
        } else {
          this.close();
        }

        // Handle auto-locking disclosures that should be locked.
        if (
          this.isLocked ||
          (this.lockInsideBreakpoint &&
            window.matchMedia(this.mediaQuery).matches) ||
          (this.lockOutsideBreakpoint &&
            !window.matchMedia(this.mediaQuery).matches)
        ) {
          this.lock();
        }
      }
    );

    // Set up custom validation.
    this._addEventListener(
      "grauplComponentValidate",
      this.rootDOMElement,
      () => {
        // Boolean checks.
        const booleans = {
          closeOnBlur: this._closeOnBlur,
          openInsideBreakpoint: this._openInsideBreakpoint,
          openOutsideBreakpoint: this._openOutsideBreakpoint,
          closeInsideBreakpoint: this._closeInsideBreakpoint,
          closeOutsideBreakpoint: this._closeOutsideBreakpoint,
          lockInsideBreakpoint: this._lockInsideBreakpoint,
          lockOutsideBreakpoint: this._lockOutsideBreakpoint,
          unlockInsideBreakpoint: this._unlockInsideBreakpoint,
          unlockOutsideBreakpoint: this._unlockOutsideBreakpoint,
          locked: this._locked.value,
        };

        // Check the booleans.
        const booleanChecks = isValidType("boolean", booleans, {
          shouldThrow: false,
        });

        // Handle boolean check failure.
        if (!booleanChecks.status) {
          this._errors = [...this._errors, ...booleanChecks.errors];
          this._valid = false;
        }
      }
    );

    if (initialize) {
      this.initialize();
    }
  }

  /**
   * The class(es) to apply when the disclosure is locked.
   *
   * @type {string|string[]}
   *
   * @see _classes.locked
   */
  get lockedClass() {
    return this._classes.locked;
  }

  set lockedClass(value) {
    isValidClassList({ lockedClass: value });

    if (this._classes.locked !== value) {
      this._classes.locked = value;
    }
  }

  /**
   * The class(es) to apply when the disclosure is unlocked.
   *
   * @type {string|string[]}
   *
   * @see _classes.unlocked
   */
  get unlockedClass() {
    return this._classes.unlocked;
  }

  set unlockedClass(value) {
    isValidClassList({ unlockedClass: value });

    if (this._classes.unlocked !== value) {
      this._classes.unlocked = value;
    }
  }

  /**
   * The class(es) to apply when the disclosure is open.
   *
   * @type {string|string[]}
   *
   * @see _classes.open
   */
  get openClass() {
    return this._classes.open;
  }

  set openClass(value) {
    isValidClassList({ openClass: value });

    if (this._classes.open !== value) {
      this._classes.open = value;
    }
  }

  /**
   * The class(es) to apply when the disclosure is closed.
   *
   * @type {string|string[]}
   *
   * @see _classes.close
   */
  get closeClass() {
    return this._classes.close;
  }

  set closeClass(value) {
    isValidClassList({ closeClass: value });

    if (this._classes.close !== value) {
      this._classes.close = value;
    }
  }

  /**
   * The class(es) to apply when the disclosure is transitioning between open and closed.
   *
   * @type {string|string[]}
   *
   * @see _classes.transition
   */
  get transitionClass() {
    return this._classes.transition;
  }

  set transitionClass(value) {
    isValidClassList({ transitionClass: value });

    if (this._classes.transition !== value) {
      this._classes.transition = value;
    }
  }

  /**
   * The duration time (in milliseconds) for the transition between open and closed states.
   *
   * Setting this value will also set the --graupl-transition-duration CSS custom property on the disclosure.
   *
   * @type {number}
   *
   * @see _durations.transition
   */
  get transitionDuration() {
    return this._durations.transition;
  }

  set transitionDuration(value) {
    isValidType("number", { transitionDuration: value });

    if (this._durations.transition !== value) {
      this._durations.transition = value;
      this._setCustomProps();
    }
  }

  /**
   * The duration time (in milliseconds) for the transition from closed to open states.
   *
   * If openDuration is set to -1, the transitionDuration value will be used instead.
   *
   * Setting this value will also set the --graupl-open-transition-duration CSS custom property on the disclosure.
   *
   * @type {number}
   *
   * @see _durations.open
   */
  get openDuration() {
    if (this._durations.open === -1) return this.transitionDuration;

    return this._durations.open;
  }

  set openDuration(value) {
    isValidType("number", { openDuration: value });

    if (this._durations.open !== value) {
      this._durations.open = value;
      this._setCustomProps();
    }
  }

  /**
   * The duration time (in milliseconds) for the transition from open to closed states.
   *
   * If closeDuration is set to -1, the transitionDuration value will be used instead.
   *
   * Setting this value will also set the --graupl-close-transition-duration CSS custom property on the disclosure.
   *
   * @type {number}
   *
   * @see _durations.close
   */
  get closeDuration() {
    if (this._durations.close === -1) return this.transitionDuration;

    return this._durations.close;
  }

  set closeDuration(value) {
    isValidType("number", { closeDuration: value });

    if (this._durations.close !== value) {
      this._durations.close = value;
      this._setCustomProps();
    }
  }

  /**
   * Whether to close the disclosure when it loses focus in the DOM.
   *
   * @type {boolean}
   *
   * @see _closeOnBlur
   */
  get closeOnBlur() {
    return this._closeOnBlur;
  }

  set closeOnBlur(value) {
    isValidType("boolean", { closeOnBlur: value });

    if (this._closeOnBlur !== value) {
      this._closeOnBlur = value;
    }
  }

  /**
   * The open state of the disclosure.
   *
   * @readonly
   *
   * @type {boolean}
   *
   * @see _open
   */
  get isOpen() {
    return this._open.value;
  }

  /**
   * The open state of the disclosure that the user specifically triggered.
   *
   * @readonly
   *
   * @type {boolean}
   *
   * @see _open
   */
  get hasOpened() {
    return this._open.committed;
  }

  /**
   * A flag to open the disclosure when inside the breakpoint.
   *
   * @type {boolean}
   *
   * @see _openInsideBreakpoint
   */
  get openInsideBreakpoint() {
    return this._openInsideBreakpoint;
  }

  set openInsideBreakpoint(value) {
    isValidType("boolean", { openInsideBreakpoint: value });

    if (this._openInsideBreakpoint !== value) {
      this._openInsideBreakpoint = value;
    }
  }

  /**
   * A flag to open the disclosure when outside the breakpoint.
   *
   * @type {boolean}
   *
   * @see _openOutsideBreakpoint
   */
  get openOutsideBreakpoint() {
    return this._openOutsideBreakpoint;
  }

  set openOutsideBreakpoint(value) {
    isValidType("boolean", { openOutsideBreakpoint: value });

    if (this._openOutsideBreakpoint !== value) {
      this._openOutsideBreakpoint = value;
    }
  }

  /**
   * A flag to close the disclosure when inside the breakpoint.
   *
   * @type {boolean}
   *
   * @see _closeInsideBreakpoint
   */
  get closeInsideBreakpoint() {
    return this._closeInsideBreakpoint;
  }

  set closeInsideBreakpoint(value) {
    isValidType("boolean", { closeInsideBreakpoint: value });

    if (this._closeInsideBreakpoint !== value) {
      this._closeInsideBreakpoint = value;
    }
  }

  /**
   * A flag to close the disclosure when outside the breakpoint.
   *
   * @type {boolean}
   *
   * @see _closeOutsideBreakpoint
   */
  get closeOutsideBreakpoint() {
    return this._closeOutsideBreakpoint;
  }

  set closeOutsideBreakpoint(value) {
    isValidType("boolean", { closeOutsideBreakpoint: value });

    if (this._closeOutsideBreakpoint !== value) {
      this._closeOutsideBreakpoint = value;
    }
  }

  /**
   * A flag to lock the disclosure in its current state when inside the breakpoint.
   *
   * @type {boolean}
   *
   * @see _lockInsideBreakpoint
   */
  get lockInsideBreakpoint() {
    return this._lockInsideBreakpoint;
  }

  set lockInsideBreakpoint(value) {
    isValidType("boolean", { lockInsideBreakpoint: value });

    if (this._lockInsideBreakpoint !== value) {
      this._lockInsideBreakpoint = value;
    }
  }

  /**
   * A flag to lock the disclosure in its current state when outside the breakpoint.
   *
   * @type {boolean}
   *
   * @see _lockOutsideBreakpoint
   */
  get lockOutsideBreakpoint() {
    return this._lockOutsideBreakpoint;
  }

  set lockOutsideBreakpoint(value) {
    isValidType("boolean", { lockOutsideBreakpoint: value });

    if (this._lockOutsideBreakpoint !== value) {
      this._lockOutsideBreakpoint = value;
    }
  }

  /**
   * A flag to indicate if the disclosure is locked.
   *
   * @readonly
   *
   * @type {boolean}
   *
   * @see _locked
   */
  get isLocked() {
    return this._locked.value;
  }

  /**
   * The committed lock preference for the disclosure.
   *
   * @readonly
   *
   * @type {boolean}
   *
   * @see _locked
   */
  get shouldBeLocked() {
    return this._locked.committed;
  }

  /**
   * Sets the IDs throughout the disclosure.
   *
   * The generated IDs use the key and follow the format:
   *  - disclosure: `disclosure-${key}`
   *  - controller: `disclosure-controller-${key}`
   *
   * @protected
   */
  _setIds() {
    this.dom.disclosure.id = this.dom.disclosure.id || `disclosure-${this.key}`;
    this.dom.controller.id =
      this.dom.controller.id || `disclosure-controller-${this.key}`;

    this._id = this.dom.disclosure.id;
  }

  /**
   * Sets ARIA attributes throughout the disclosure.
   *
   * The first steps are to ensure that the controller has `aria-expanded` set to "false"
   * if it's not already explicitly set to "true".
   *
   * Then, set the `aria-controls` attribute on the controller to the disclosure's ID.
   *
   * Finally, ensure the controller element has a role of "button" if it is not a native button element.
   *
   * @protected
   */
  _setAriaAttributes() {
    // If the controller element doesn't have aria-expanded set to true, set it to false.
    if (this.dom.controller.getAttribute("aria-expanded") !== "true") {
      this.dom.controller.setAttribute("aria-expanded", "false");
    }

    // Set the aria-controls attribute on the controller to the disclosure's ID.
    this.dom.controller.setAttribute("aria-controls", this.dom.disclosure.id);

    // If the controller element is not a button, set its role to button.
    if (
      !isTag(
        "button",
        { controller: this.dom.controller },
        { shouldThrow: false }
      ).status
    ) {
      this.dom.controller.setAttribute("role", "button");
    }
  }

  /**
   * Sets custom props throughout the disclosure.
   *
   * The custom properties are:
   *   - `--graupl-disclosure-transition-duration`,
   *   - `--graupl-disclosure-open-transition-duration`, and
   *   - `--graupl-disclosure-close-transition-duration`.
   *
   * The prefix of `graupl-` can be changed by setting the disclosure's prefix value.
   *
   * @protected
   */
  _setCustomProps() {
    this.dom.disclosure.style.setProperty(
      `--${this.prefix}disclosure-transition-duration`,
      `${this.transitionDuration}ms`
    );

    this.dom.disclosure.style.setProperty(
      `--${this.prefix}disclosure-open-transition-duration`,
      `${this.openDuration}ms`
    );

    this.dom.disclosure.style.setProperty(
      `--${this.prefix}disclosure-close-transition-duration`,
      `${this.closeDuration}ms`
    );
  }

  /**
   * Sets all DOM elements within the disclosure.
   *
   * Utilizes _setDOMElementType and
   * _resetDOMElementType.
   *
   * @protected
   */
  _setDOMElements() {
    this._resetDOMElementType("content");
    this._setDOMElementType("content", { context: this.dom.disclosure });
  }

  /**
   * Expands the disclosure.
   *
   * Sets the controller's `aria-expanded` to "true", adds the
   * open class to the disclosure, and removes the closed class from the disclosure.
   *
   * @protected
   *
   * @fires grauplDisclosureExpand
   *
   * @param {Object<boolean>} [options = {}]                            - Options for expanding the disclosure.
   * @param {boolean}         [options.emit = this.isInitialized]       - Emit the expand event once expanded.
   * @param {boolean}         [options.transition = this.isInitialized] - Respect the transition class.
   */
  _reveal({ emit = this.isInitialized, transition = this.isInitialized } = {}) {
    this.dom.controller.setAttribute("aria-expanded", "true");

    // If we're dealing with transition classes, then we need to utilize
    // requestAnimationFrame to add the transition class, remove the close class,
    // add the open class, and finally remove the transition class.
    if (transition && this.transitionlass !== "") {
      addClass(this.transitionClass, this.dom.disclosure);

      requestAnimationFrame(() => {
        removeClass(this.closeClass, this.dom.disclosure);

        requestAnimationFrame(() => {
          addClass(this.openClass, this.dom.disclosure);

          requestAnimationFrame(() => {
            setTimeout(() => {
              removeClass(this.transitionClass, this.dom.disclosure);
            }, this.openDuration);
          });
        });
      });
    } else {
      // Add the open class
      addClass(this.openClass, this.dom.disclosure);

      // Remove the close class.
      removeClass(this.closeClass, this.dom.disclosure);
    }

    this.dom.content.removeAttribute("inert");

    if (emit) {
      this._dispatchEvent("expand", this.dom.controller);
    }
  }

  /**
   * Collapses the disclosure.
   *
   * Sets the controller's `aria-expanded` to "false", adds the
   * close class to the disclosure, and removes the open class from the disclosure.
   *
   * @protected
   *
   * @fires grauplDisclosureCollapse
   *
   * @param {Object<boolean>} [options = {}]                            - Options for collapsing the disclosure.
   * @param {boolean}         [options.emit = this.isInitialized]       - Emit the collapse event once collapsed.
   * @param {boolean}         [options.transition = this.isInitialized] - Respect the transition class.
   */
  _conceal({
    emit = this.isInitialized,
    transition = this.isInitialized,
  } = {}) {
    this.dom.controller.setAttribute("aria-expanded", "false");

    // If we're dealing with transition classes, then we need to utilize
    // requestAnimationFrame to add the transition class, remove the open class,
    // add the close class, and finally remove the transition class.
    if (transition && this.transitionClass !== "") {
      addClass(this.transitionClass, this.dom.disclosure);

      requestAnimationFrame(() => {
        removeClass(this.openClass, this.dom.disclosure);

        requestAnimationFrame(() => {
          addClass(this.closeClass, this.dom.disclosure);

          requestAnimationFrame(() => {
            setTimeout(() => {
              removeClass(this.transitionClass, this.dom.disclosure);

              this.dom.content.innert = true;
            }, this.closeDuration);
          });
        });
      });
    } else {
      // Add the close class
      addClass(this.closeClass, this.dom.disclosure);

      // Remove the open class.
      removeClass(this.openClass, this.dom.disclosure);
    }

    this.dom.content.setAttribute("inert", "true");

    if (emit) {
      this._dispatchEvent("collapse", this.dom.controller);
    }
  }

  /**
   * Applies the locked state styling and dispatches the lock event.
   *
   * @protected
   *
   * @param {Object<boolean>} [options = {}]                      - Options for the lock side effects.
   * @param {boolean}         [options.emit = this.isInitialized] - Whether to emit the lock event.
   */
  _lock({ emit = this.isInitialized } = {}) {
    // Add the locked class
    addClass(this.lockedClass, this.dom.disclosure);

    // Remove the unlocked class.
    removeClass(this.unlockedClass, this.dom.disclosure);

    this.dom.controller.setAttribute("disabled", "true");

    if (emit) {
      this._dispatchEvent("lock", this.dom.disclosure);
    }
  }

  /**
   * Applies the unlocked state styling and dispatches the unlock event.
   *
   * @protected
   *
   * @param {Object<boolean>} [options = {}]                      - Options for the unlock side effects.
   * @param {boolean}         [options.emit = this.isInitialized] - Whether to emit the unlock event.
   */
  _unlock({ emit = this.isInitialized } = {}) {
    // Add the unlocked class
    addClass(this.unlockedClass, this.dom.disclosure);

    // Remove the locked class.
    removeClass(this.lockedClass, this.dom.disclosure);

    this.dom.controller.removeAttribute("disabled");

    if (emit) {
      this._dispatchEvent("unlock", this.dom.disclosure);
    }
  }

  /**
   * Handles focus events throughout the disclosure.
   *
   * - Adds a `focusout` listener to the disclosure so when the disclosure loses focus it will close.
   */
  _handleFocus() {
    this._addEventListener("focusout", this.dom.disclosure, (event) => {
      if (
        !this.closeOnBlur ||
        this.currentEvent !== "keyboard" ||
        event.relatedTarget === null ||
        this.dom.disclosure.contains(event.relatedTarget) ||
        this.dom.controller === event.relatedTarget
      ) {
        return;
      }

      this.close();
    });
  }

  /**
   * Handles click events throughout the disclosure.
   *
   * - Adds a `click` listener to the controller that toggles the disclosure.
   * - Adds a `click` listener to the `document` so if the user clicks outside the disclosure it will close.
   */
  _handleClick() {
    this._addEventListener("click", this.dom.controller, (event) => {
      this.currentEvent = "mouse";

      if (event.button !== 0) return;

      preventEvent(event);
      this.toggle();
    });

    this._addEventListener("click", document, (event) => {
      if (this.focusState !== "self" || !this.closeOnBlur) return;

      this.currentEvent = "mouse";

      if (
        !this.dom.disclosure.contains(event.target) &&
        this.dom.controller !== event.target
      ) {
        this.close();
      }
    });
  }

  /**
   * Handles keydown events throughout the disclosure.
   *
   * This method exists to assist the _handleKeyup method.
   *
   * - Adds a `keydown` listener to the controller.
   *   - Blocks propagation on "Space" and "Enter" keys.
   * - Adds a `keydown` listener to the disclosure.
   *   - Blocks propagation on "Escape" keys.
   */
  _handleKeydown() {
    this._addEventListener("keydown", this.dom.controller, (event) => {
      this.currentEvent = "keyboard";

      const key = keyPress(event);

      switch (key) {
        case "Space":
        case "Enter":
          preventEvent(event);

          break;
      }
    });

    this._addEventListener("keydown", this.dom.disclosure, (event) => {
      this.currentEvent = "keyboard";

      const key = keyPress(event);

      switch (key) {
        case "Escape":
          preventEvent(event);

          break;
      }
    });
  }

  /**
   * Handles keyup events throughout the disclosure.
   *
   * - Adds a `keyup` listener to the controller.
   *   - Toggles the disclosure on "Space" and "Enter" keys.
   * - Adds a `keyup` listener to the disclosure.
   *   - Closes the disclosure on "Escape" keys.
   */
  _handleKeyup() {
    this._addEventListener("keyup", this.dom.controller, (event) => {
      this.currentEvent = "keyboard";

      const key = keyPress(event);

      switch (key) {
        case "Space":
        case "Enter":
          this.toggle();

          preventEvent(event);

          break;
      }
    });

    this._addEventListener("keyup", this.dom.disclosure, (event) => {
      this.currentEvent = "keyboard";

      const key = keyPress(event);

      switch (key) {
        case "Escape":
          this.close();

          preventEvent(event);

          break;
      }
    });
  }

  /**
   * Opens the disclosure.
   *
   * Sets the disclosure's focus state to "self", calls expand, and sets isOpen to `true`.
   *
   * @param {Object<boolean>} [options = {}]                            - Options for opening the disclosure.
   * @param {boolean}         [options.force = false]                   - Whether to force the open action.
   * @param {boolean}         [options.emit = this.isInitialized]       - Whether to emit the expand event once opened.
   * @param {boolean}         [options.transition = this.isInitialized] - Respect the transition class.
   * @param {boolean}         [options.preserveState = false]           - Whether to preserve the open state.
   */
  open({
    force = false,
    emit = this.isInitialized,
    transition = this.isInitialized,
    preserveState = false,
  } = {}) {
    if (this.isOpen && !force) return;
    if (this.isLocked) return;

    // Set the focus state.
    this.focusState = "self";

    // Expand the disclosure.
    this._reveal({ emit, transition });

    // Set the open state.
    this._open.value = true;

    if (!preserveState) {
      // Commit the open state.
      this._open.commit();
    }
  }

  /**
   * Opens the disclosure without entering it.
   *
   * Sets the disclosure's focus state to "none", calls expand, and sets isOpen to `true`.
   *
   * @param {Object<boolean>} [options = {}]                            - Options for previewing the disclosure.
   * @param {boolean}         [options.force = false]                   - Whether to force the preview action.
   * @param {boolean}         [options.emit = this.isInitialized]       - Whether to emit the expand event once previewed.
   * @param {boolean}         [options.transition = this.isInitialized] - Respect the transition class.
   * @param {boolean}         [options.preserveState = false]           - Whether to preserve the open state.
   */
  preview({
    force = false,
    emit = this.isInitialized,
    transition = this.isInitialized,
    preserveState = false,
  } = {}) {
    if (this.isOpen && !force) return;
    if (this.isLocked) return;

    // Set the focus state.
    this.focusState = "none";

    // Expand the disclosure.
    this._reveal({ emit, transition });

    // Set the open state.
    this._open.value = true;

    if (!preserveState) {
      // Commit the open state.
      this._open.commit();
    }
  }

  /**
   * Closes the disclosure.
   *
   * Sets the disclosure's focus state to "none", calls collapse, and sets isOpen to `false`.
   *
   * @param {Object<boolean>} [options = {}]                            - Options for closing the disclosure.
   * @param {boolean}         [options.force = false]                   - Whether to force the close action.
   * @param {boolean}         [options.emit = this.isInitialized]       - Whether to emit the collapse event once closed.
   * @param {boolean}         [options.transition = this.isInitialized] - Respect the transition class.
   * @param {boolean}         [options.preserveState = false]           - Whether to preserve the open state.
   */
  close({
    force = false,
    emit = this.isInitialized,
    transition = this.isInitialized,
    preserveState = false,
  } = {}) {
    if (!this.isOpen && !force) return;
    if (this.isLocked) return;

    // Set the focus state.
    this.focusState = "none";

    // Collapse the disclosure.
    this._conceal({ emit, transition });

    // Set the open state.
    this._open.value = false;

    if (!preserveState) {
      // Commit the open state.
      this._open.commit();
    }
  }

  /**
   * Toggles the open state of the disclosure.
   *
   * @param {Object<boolean>} [options = {}]                            - Options for toggling the disclosure.
   * @param {boolean}         [options.force = false]                   - Whether to force the open or close action.
   * @param {boolean}         [options.emit = this.isInitialized]       - Whether to emit the expand/collapse event once toggled.
   * @param {boolean}         [options.transition = this.isInitialized] - Respect the transition class.
   * @param {boolean}         [options.preserveState = false]           - Whether to preserve the open state.
   */
  toggle({
    force = false,
    emit = this.isInitialized,
    transition = this.isInitialized,
    preserveState = false,
  } = {}) {
    if (this.isOpen) {
      this.close({ force, emit, transition, preserveState });
    } else {
      this.open({ force, emit, transition, preserveState });
    }
  }

  /**
   * Locks the disclosure.
   *
   * @param {Object<boolean>} [options = {}]                      - Options for locking the disclosure.
   * @param {boolean}         [options.force = false]             - Whether to force the lock action.
   * @param {boolean}         [options.emit = this.isInitialized] - Whether to emit the lock event.
   */
  lock({ force = false, emit = this.isInitialized } = {}) {
    // Only lock if the disclosure is unlocked.
    if (this.isLocked && !force) return;

    this._locked.value = true;
    this._lock({ emit });

    // Commit the locked preference.
    this._locked.commit();
  }

  /**
   * Unlocks the disclosure.
   *
   * @param {Object<boolean>} [options = {}]                      - Options for unlocking the disclosure.
   * @param {boolean}         [options.force = true]              - Whether to force the unlock action.
   * @param {boolean}         [options.emit = this.isInitialized] - Whether to emit the unlock event.
   */
  unlock({ force = false, emit = this.isInitialized } = {}) {
    // Only unlock if the disclosure is locked.
    if (!this.isLocked && !force) return;

    this._locked.value = false;
    this._unlock({ emit });

    this._locked.commit();
  }

  /**
   * Toggles the locked state of the disclosure.
   *
   * @param {Object<boolean>} [options = {}]                      - Options for toggling the lock state.
   * @param {boolean}         [options.force = false]             - Whether to force the toggle action.
   * @param {boolean}         [options.emit = this.isInitialized] - Whether to emit the lock/unlock event.
   */
  toggleLock({ force = false, emit = this.isInitialized } = {}) {
    if (this.isLocked) {
      this.unlock({ force, emit });
    } else {
      this.lock({ force, emit });
    }
  }
}

export default Disclosure;
