name: Pre-release

on:
  push:
    # Push events to match v*.*.*-alpha.*, v*.*.*-beta.*, and v*.*.*-rc.* where * is a number.
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-[a-zA-Z]+.[0-9]+'

permissions:
  contents: write
  id-token: write

jobs:
  test:
    uses: ./.github/workflows/test.yml

  release_github:
    # Prevent this action from running on forks.
    if: github.repository == 'graupl/graupl'
    needs: test
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install modules
        run: npm install

      # Get the version from the package.json
      - name: Get version
        id: get_version
        run: |
          export VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ env.VERSION }}
          prerelease: true

  publish_npm:
    # Prevent this action from running on forks.
    if: github.repository == 'graupl/graupl'
    needs: [release_github]
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          registry-url: 'https://registry.npmjs.org/'
          scope: '@graupl'

      - name: Install modules
        run: npm install

      # Get the prerelease type from the package.json, e.g., 'alpha', 'beta', or 'rc'.
      - name: Get prerelease type
        id: get_prerelease_type
        run: |
          export PRERELEASE_TYPE=$(node -p "require('./package.json').version.split('-')[1].split('.')[0]")
          echo "PRERELEASE_TYPE=$PRERELEASE_TYPE" >> $GITHUB_ENV

      - name: Publish workspaces to npm
        if: github.tag
        run: npm publish --workspaces --access public --tag ${{ env.PRERELEASE_TYPE }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to npm
        if: github.tag
        run: npm publish --access public --tag ${{ env.PRERELEASE_TYPE }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish_github:
    # Prevent this action from running on forks.
    if: github.repository == 'graupl/graupl'
    needs: [release_github]
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@graupl'

      - name: Install modules
        run: npm install

      # Get the prerelease type from the package.json, e.g., 'alpha', 'beta', or 'rc'.
      - name: Get prerelease type
        id: get_prerelease_type
        run: |
          export PRERELEASE_TYPE=$(node -p "require('./package.json').version.split('-')[1].split('.')[0]")
          echo "PRERELEASE_TYPE=$PRERELEASE_TYPE" >> $GITHUB_ENV

      - name: Publish workspaces to GitHub Packages
        if: github.tag
        run: npm publish --workspaces --access public --tag ${{ env.PRERELEASE_TYPE }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GitHub Packages
        if: github.tag
        run: npm publish --access public --tag ${{ env.PRERELEASE_TYPE }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
