name: Tests

on:
  push:
    branches: [ '*.x' ]
  pull_request:
    branches: [ '*.x' ]
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - name: Install modules
        run: npm install

      - name: Run build
        run: npm run build

  eslint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - name: Install modules
        run: npm install

      - name: Run eslint
        run: npm run eslint

  stylelint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - name: Install modules
        run: npm install

      - name: Run stylelint
        run: npm run stylelint

  prettier:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - name: Install modules
        run: npm install

      - name: Run prettier
        run: npm run prettier -- --check

  vitest:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - name: Install modules
        run: npm install

      - name: Install Playwright Browsers
        run: npx --no playwright install --with-deps --only-shell

      - name: Run vitest
        run: npm run test:run
